//===============================================================================================
// <A4DN_GeneratedInformation>
// This code was generated using the Accelerator for .Net Code Generator.
// <A4DN_Template Name="BOS.Module.Entity.t4" Version="8.0.0.93" GeneratedDate="5/29/2024" />
// </A4DN_GeneratedInformation>
//===============================================================================================
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using A4DN.Core.BOS.Base;
using BOS.OrderManagement.Shared.Properties;
#if !SILVERLIGHT
using A4DN.Core.BOS.ValidationAttributes;  // Custom validation attributes
#endif

namespace BOS.ProductDataEntity
{
    /// <summary>
    /// Represents data. Contains metadata that facilitates validation and advanced databinding.
    /// </summary>
    [DataContract]
    public class ProductEntity : AB_BusinessObjectEntityBase
    {
        /// <summary>
        /// Entity information is defined in the lower level entity to maximize performance by making it static
        /// </summary>
        private static AB_EntityInfo _EntityInfo;
        /// <summary>
        /// Gets metadata information about the entity
        /// </summary>
        public override AB_EntityInfo ap_EntityInfo
        {
            get => _EntityInfo;
        }

        /// <summary>
        /// Initializes static members
        /// </summary>
        static private void RG_DoStaticInit()
        {
            // Set Message and Description Primary and Secondary Resources. 
            AB_BusinessObjectEntityBase.am_GetPropertyInfo(typeof(ProductEntity), typeof(BOS.OrderManagement.Properties.MessageResource), typeof(MessageResource), typeof(BOS.OrderManagement.Properties.DescriptionResource), typeof(DescriptionResource), out _EntityInfo); 
        }

        #region Properties

        [AB_Key(ap_IsAutoGenerated=true)] 
        [AB_DoNotCopy]
        [Display(Name = "PRODUCTINTERNALID", ResourceType = typeof(DescriptionResource))]
        [AB_Length(8)]
        [AB_AutoIncrement]
        [DataMember]
        public int? ProductInternalID //Map Field: YD1PIID
        {
            get => am_GetPropertyValue(ProductInternalIDProperty);
            set => am_SetPropertyValue(ProductInternalIDProperty, value);
        }
        public static AB_PropertyMetadata<int?> ProductInternalIDProperty = am_CreatePropertyMetaData<int?>(nameof(ProductInternalID), DescriptionResource.PRODUCTINTERNALID, null); 

        [Display(Name = "CODE", ResourceType = typeof(DescriptionResource))]
        [AB_Length(25)]
        [DataMember]
        public string Code //Map Field: YD1PCD
        {
            get => am_GetPropertyValue(CodeProperty);
            set => am_SetPropertyValue(CodeProperty, value);
        }
        public static AB_PropertyMetadata<string> CodeProperty = am_CreatePropertyMetaData<string>(nameof(Code), DescriptionResource.CODE, null); 

        [Display(Name = "NAME", ResourceType = typeof(DescriptionResource))]
        [AB_Length(50)]
        [AB_BroadcastMember("ProductName", AB_DataShouldBePassed.OnPreload)]
        [DataMember]
        public string Name //Map Field: YD1PNM
        {
            get => am_GetPropertyValue(NameProperty);
            set => am_SetPropertyValue(NameProperty, value);
        }
        public static AB_PropertyMetadata<string> NameProperty = am_CreatePropertyMetaData<string>(nameof(Name), DescriptionResource.NAME, null); 

        [Display(Name = "DESCRIPTION", ResourceType = typeof(DescriptionResource))]
        [AB_Length(256)]
        [DataMember]
        public string Description //Map Field: YD1PDS
        {
            get => am_GetPropertyValue(DescriptionProperty);
            set => am_SetPropertyValue(DescriptionProperty, value);
        }
        public static AB_PropertyMetadata<string> DescriptionProperty = am_CreatePropertyMetaData<string>(nameof(Description), DescriptionResource.DESCRIPTION, null); 

        [Display(Name = "CATEGORY", ResourceType = typeof(DescriptionResource))]
        [AB_Length(50)]
        [DataMember]
        public string Category //Map Field: YD1PCT
        {
            get => am_GetPropertyValue(CategoryProperty);
            set => am_SetPropertyValue(CategoryProperty, value);
        }
        public static AB_PropertyMetadata<string> CategoryProperty = am_CreatePropertyMetaData<string>(nameof(Category), DescriptionResource.CATEGORY, null); 

        [Display(Name = "STANDARDCOST", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [DataType(DataType.Currency)]
        [AB_ApplyStringFormat("C")]
        [DataMember]
        public decimal? StandardCost //Map Field: YD1PSTCS
        {
            get => am_GetPropertyValue(StandardCostProperty);
            set => am_SetPropertyValue(StandardCostProperty, value);
        }
        public static AB_PropertyMetadata<decimal?> StandardCostProperty = am_CreatePropertyMetaData<decimal?>(nameof(StandardCost), DescriptionResource.STANDARDCOST, null); 

        [Display(Name = "LISTPRICE", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [DataType(DataType.Currency)]
        [AB_ApplyStringFormat("C")]
        [DataMember]
        public decimal? ListPrice //Map Field: YD1PLSPR
        {
            get => am_GetPropertyValue(ListPriceProperty);
            set => am_SetPropertyValue(ListPriceProperty, value);
        }
        public static AB_PropertyMetadata<decimal?> ListPriceProperty = am_CreatePropertyMetaData<decimal?>(nameof(ListPrice), DescriptionResource.LISTPRICE, null); 

        [Display(Name = "REORDERLEVEL", ResourceType = typeof(DescriptionResource))]
        [AB_Length(4)]
        [DataMember]
        public int? ReorderLevel //Map Field: YD1PROLV
        {
            get => am_GetPropertyValue(ReorderLevelProperty);
            set => am_SetPropertyValue(ReorderLevelProperty, value);
        }
        public static AB_PropertyMetadata<int?> ReorderLevelProperty = am_CreatePropertyMetaData<int?>(nameof(ReorderLevel), DescriptionResource.REORDERLEVEL, null); 

        [Display(Name = "TARGETLEVEL", ResourceType = typeof(DescriptionResource))]
        [AB_Length(4)]
        [DataMember]
        public int? TargetLevel //Map Field: YD1PTGLV
        {
            get => am_GetPropertyValue(TargetLevelProperty);
            set => am_SetPropertyValue(TargetLevelProperty, value);
        }
        public static AB_PropertyMetadata<int?> TargetLevelProperty = am_CreatePropertyMetaData<int?>(nameof(TargetLevel), DescriptionResource.TARGETLEVEL, null); 

        [Display(Name = "MINIMUMREORDERQUANTITY", ResourceType = typeof(DescriptionResource))]
        [AB_Length(4)]
        [DataMember]
        public int? MinimumReorderQuantity //Map Field: YD1PMRQT
        {
            get => am_GetPropertyValue(MinimumReorderQuantityProperty);
            set => am_SetPropertyValue(MinimumReorderQuantityProperty, value);
        }
        public static AB_PropertyMetadata<int?> MinimumReorderQuantityProperty = am_CreatePropertyMetaData<int?>(nameof(MinimumReorderQuantity), DescriptionResource.MINIMUMREORDERQUANTITY, null); 

        [Display(Name = "DISCONTINUED", ResourceType = typeof(DescriptionResource))]
        [AB_Length(1)]
        [DataMember]
        public string Discontinued //Map Field: YD1PDC
        {
            get => am_GetPropertyValue(DiscontinuedProperty);
            set => am_SetPropertyValue(DiscontinuedProperty, value);
        }
        public static AB_PropertyMetadata<string> DiscontinuedProperty = am_CreatePropertyMetaData<string>(nameof(Discontinued), DescriptionResource.DISCONTINUED, null); 

        [Display(Name = "MEMO", ResourceType = typeof(DescriptionResource))]
        [AB_Length(100)]
        [DataMember]
        public string Memo //Map Field: YD1PM1
        {
            get => am_GetPropertyValue(MemoProperty);
            set => am_SetPropertyValue(MemoProperty, value);
        }
        public static AB_PropertyMetadata<string> MemoProperty = am_CreatePropertyMetaData<string>(nameof(Memo), DescriptionResource.MEMO, null); 

        [Display(Name = "IMAGEPATH", ResourceType = typeof(DescriptionResource))]
        [AB_Length(256)]
        [DataMember]
        public string ImagePath //Map Field: YD1PIMPT
        {
            get => am_GetPropertyValue(ImagePathProperty);
            set => am_SetPropertyValue(ImagePathProperty, value);
        }
        public static AB_PropertyMetadata<string> ImagePathProperty = am_CreatePropertyMetaData<string>(nameof(ImagePath), DescriptionResource.IMAGEPATH, null); 

        [Display(Name = "CREATEDATE", ResourceType = typeof(DescriptionResource))]
        [AB_ApplyDateFormat]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:d}", ApplyFormatInEditMode=true)]
        [AB_CreateDate]
        [DataMember]
        public DateTime? CreateDate //Map Field: YD1PCRDT
        {
            get => am_GetPropertyValue(CreateDateProperty);
            set => am_SetPropertyValue(CreateDateProperty, value);
        }
        public static AB_PropertyMetadata<DateTime?> CreateDateProperty = am_CreatePropertyMetaData<DateTime?>(nameof(CreateDate), DescriptionResource.CREATEDATE, null); 

        [Display(Name = "CREATETIME", ResourceType = typeof(DescriptionResource))]
        [AB_CreateTime]
        [DataMember]
        public TimeSpan? CreateTime //Map Field: YD1PCRTM
        {
            get => am_GetPropertyValue(CreateTimeProperty);
            set => am_SetPropertyValue(CreateTimeProperty, value);
        }
        public static AB_PropertyMetadata<TimeSpan?> CreateTimeProperty = am_CreatePropertyMetaData<TimeSpan?>(nameof(CreateTime), DescriptionResource.CREATETIME, null); 

        [Display(Name = "CREATEUSER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [AB_CreateUser]
        [DataMember]
        public string CreateUser //Map Field: YD1PCRUS
        {
            get => am_GetPropertyValue(CreateUserProperty);
            set => am_SetPropertyValue(CreateUserProperty, value);
        }
        public static AB_PropertyMetadata<string> CreateUserProperty = am_CreatePropertyMetaData<string>(nameof(CreateUser), DescriptionResource.CREATEUSER, null); 

        [Display(Name = "CREATEJOB", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [DataMember]
        public string CreateJob //Map Field: YD1PCRJB
        {
            get => am_GetPropertyValue(CreateJobProperty);
            set => am_SetPropertyValue(CreateJobProperty, value);
        }
        public static AB_PropertyMetadata<string> CreateJobProperty = am_CreatePropertyMetaData<string>(nameof(CreateJob), DescriptionResource.CREATEJOB, null); 

        [Display(Name = "CREATEJOBNUMBER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(6)]
        [DataMember]
        public string CreateJobNumber //Map Field: YD1PCRJN
        {
            get => am_GetPropertyValue(CreateJobNumberProperty);
            set => am_SetPropertyValue(CreateJobNumberProperty, value);
        }
        public static AB_PropertyMetadata<string> CreateJobNumberProperty = am_CreatePropertyMetaData<string>(nameof(CreateJobNumber), DescriptionResource.CREATEJOBNUMBER, null); 

        [Display(Name = "LASTCHANGEDATE", ResourceType = typeof(DescriptionResource))]
        [AB_ApplyDateFormat]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:d}", ApplyFormatInEditMode=true)]
        [AB_LastChangeDate]
        [DataMember]
        public DateTime? LastChangeDate //Map Field: YD1PLCDT
        {
            get => am_GetPropertyValue(LastChangeDateProperty);
            set => am_SetPropertyValue(LastChangeDateProperty, value);
        }
        public static AB_PropertyMetadata<DateTime?> LastChangeDateProperty = am_CreatePropertyMetaData<DateTime?>(nameof(LastChangeDate), DescriptionResource.LASTCHANGEDATE, null); 

        [Display(Name = "LASTCHANGETIME", ResourceType = typeof(DescriptionResource))]
        [AB_LastChangeTime]
        [DataMember]
        public TimeSpan? LastChangeTime //Map Field: YD1PLCTM
        {
            get => am_GetPropertyValue(LastChangeTimeProperty);
            set => am_SetPropertyValue(LastChangeTimeProperty, value);
        }
        public static AB_PropertyMetadata<TimeSpan?> LastChangeTimeProperty = am_CreatePropertyMetaData<TimeSpan?>(nameof(LastChangeTime), DescriptionResource.LASTCHANGETIME, null); 

        [Display(Name = "LASTCHANGEUSER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [AB_LastChangeUser]
        [DataMember]
        public string LastChangeUser //Map Field: YD1PLCUS
        {
            get => am_GetPropertyValue(LastChangeUserProperty);
            set => am_SetPropertyValue(LastChangeUserProperty, value);
        }
        public static AB_PropertyMetadata<string> LastChangeUserProperty = am_CreatePropertyMetaData<string>(nameof(LastChangeUser), DescriptionResource.LASTCHANGEUSER, null); 

        [Display(Name = "LASTCHANGEJOB", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [DataMember]
        public string LastChangeJob //Map Field: YD1PLCJB
        {
            get => am_GetPropertyValue(LastChangeJobProperty);
            set => am_SetPropertyValue(LastChangeJobProperty, value);
        }
        public static AB_PropertyMetadata<string> LastChangeJobProperty = am_CreatePropertyMetaData<string>(nameof(LastChangeJob), DescriptionResource.LASTCHANGEJOB, null); 

        [Display(Name = "LASTCHANGEJOBNUMBER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(6)]
        [DataMember]
        public string LastChangeJobNumber //Map Field: YD1PLCJN
        {
            get => am_GetPropertyValue(LastChangeJobNumberProperty);
            set => am_SetPropertyValue(LastChangeJobNumberProperty, value);
        }
        public static AB_PropertyMetadata<string> LastChangeJobNumberProperty = am_CreatePropertyMetaData<string>(nameof(LastChangeJobNumber), DescriptionResource.LASTCHANGEJOBNUMBER, null); 


        #endregion //Properties

        #region Property Overrides

        // Title
        public override string ap_Title
        {
            get
            {
                if (string.IsNullOrEmpty(base.ap_Title))
                {
                    StringBuilder title = new StringBuilder();
                    switch (ap_TitleMode)
                    {
                        case AB_TitleMode.New:
                        case AB_TitleMode.NewFor:
                        case AB_TitleMode.Copy:
                            title.AppendFormat("{0}", MessageResource.TITLENEW);
                            break;
                        case AB_TitleMode.Display:
                            title.AppendFormat("{0}", MessageResource.TITLEDISPLAY);
                            break;
                        case AB_TitleMode.Open:
                            title.AppendFormat("{0}", MessageResource.TITLEOPEN);
                            break;
                        case AB_TitleMode.Subbrowser:
                            title.AppendFormat("{0}", MessageResource.TITLESUBBROWSER);
                            break;
                        case AB_TitleMode.Default:
                            title.AppendFormat("{0} ", MessageResource.TITLEOPEN);
                            break;
                    }
 
                    if (!string.IsNullOrWhiteSpace(Name))
                    {
                        title.AppendFormat(" - {0}", Name);
                    }
  
                    return title.ToString();
                }
                return base.ap_Title;
            }
            set
            {
                base.ap_Title = value;
            }
        }

        // Message Field
        public override string ap_MessageField
        {
            get
            {
                if (string.IsNullOrEmpty(base.ap_MessageField))
                {
                    return "\"" + ap_Title + "\"";
                }

                return base.ap_MessageField;
            }
            set
            {
                base.ap_MessageField = value;
            }
        }

        // Unique Name
        public override string ap_UniqueName
        {
            get
            {
                if (string.IsNullOrEmpty(base.ap_UniqueName))
                {
                    return "Product - ";
                }

                return base.ap_UniqueName;
            }
            set
            {
                base.ap_UniqueName = value;
            }
        }

        #endregion //Property Overrides
        /// <summary>
        /// Static constructor
        /// </summary>
        static ProductEntity()
        {
            RG_DoStaticInit();
        }


    }
}