//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOS.OrderManagement.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DescriptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOS.OrderManagement.Shared.Properties.DescriptionResource", typeof(DescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string ADDITEM {
            get {
                return ResourceManager.GetString("ADDITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string ADDRESS1 {
            get {
                return ResourceManager.GetString("ADDRESS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string ADDRESS2 {
            get {
                return ResourceManager.GetString("ADDRESS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        public static string ADDRESS3 {
            get {
                return ResourceManager.GetString("ADDRESS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Stamps.
        /// </summary>
        public static string AUDITSTAMPTABTEXT {
            get {
                return ResourceManager.GetString("AUDITSTAMPTABTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Discount.
        /// </summary>
        public static string AVERAGEDISCOUNT {
            get {
                return ResourceManager.GetString("AVERAGEDISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Order Discount.
        /// </summary>
        public static string AVERAGEORDERDISCOUNT {
            get {
                return ResourceManager.GetString("AVERAGEORDERDISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Order Quantity.
        /// </summary>
        public static string AVERAGEORDERQUANTITY {
            get {
                return ResourceManager.GetString("AVERAGEORDERQUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Order Subtotal.
        /// </summary>
        public static string AVERAGEORDERSUBTOTAL {
            get {
                return ResourceManager.GetString("AVERAGEORDERSUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Order Total.
        /// </summary>
        public static string AVERAGEORDERTOTAL {
            get {
                return ResourceManager.GetString("AVERAGEORDERTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Order Unit Price.
        /// </summary>
        public static string AVERAGEORDERUNITPRICE {
            get {
                return ResourceManager.GetString("AVERAGEORDERUNITPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string BASIC {
            get {
                return ResourceManager.GetString("BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BILLINGADDRESS {
            get {
                return ResourceManager.GetString("BILLINGADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address 1.
        /// </summary>
        public static string BILLINGADDRESS1 {
            get {
                return ResourceManager.GetString("BILLINGADDRESS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address 2.
        /// </summary>
        public static string BILLINGADDRESS2 {
            get {
                return ResourceManager.GetString("BILLINGADDRESS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address 3.
        /// </summary>
        public static string BILLINGADDRESS3 {
            get {
                return ResourceManager.GetString("BILLINGADDRESS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address Block.
        /// </summary>
        public static string BILLINGADDRESSBLOCK {
            get {
                return ResourceManager.GetString("BILLINGADDRESSBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address Line.
        /// </summary>
        public static string BILLINGADDRESSLINE {
            get {
                return ResourceManager.GetString("BILLINGADDRESSLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Country.
        /// </summary>
        public static string BILLINGCOUNTRY {
            get {
                return ResourceManager.GetString("BILLINGCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Postal Code.
        /// </summary>
        public static string BILLINGPOSTALCODE {
            get {
                return ResourceManager.GetString("BILLINGPOSTALCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Stamps.
        /// </summary>
        public static string CHANGESTAMPS {
            get {
                return ResourceManager.GetString("CHANGESTAMPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        public static string COMPLETION {
            get {
                return ResourceManager.GetString("COMPLETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact First Name.
        /// </summary>
        public static string CONTACTFIRSTNAME {
            get {
                return ResourceManager.GetString("CONTACTFIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Full Name.
        /// </summary>
        public static string CONTACTFULLNAME {
            get {
                return ResourceManager.GetString("CONTACTFULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string CONTACTINFO {
            get {
                return ResourceManager.GetString("CONTACTINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Last Name.
        /// </summary>
        public static string CONTACTLASTNAME {
            get {
                return ResourceManager.GetString("CONTACTLASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Middle Name.
        /// </summary>
        public static string CONTACTMIDDLENAME {
            get {
                return ResourceManager.GetString("CONTACTMIDDLENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Nick Name.
        /// </summary>
        public static string CONTACTNICKNAME {
            get {
                return ResourceManager.GetString("CONTACTNICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CREATEDATE {
            get {
                return ResourceManager.GetString("CREATEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job.
        /// </summary>
        public static string CREATEJOB {
            get {
                return ResourceManager.GetString("CREATEJOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job Number.
        /// </summary>
        public static string CREATEJOBNUMBER {
            get {
                return ResourceManager.GetString("CREATEJOBNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Customer.
        /// </summary>
        public static string CREATENEWCUSTOMER {
            get {
                return ResourceManager.GetString("CREATENEWCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Shipping Address.
        /// </summary>
        public static string CREATENEWSHIPPINGADDRESS {
            get {
                return ResourceManager.GetString("CREATENEWSHIPPINGADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Stamps.
        /// </summary>
        public static string CREATESTAMPS {
            get {
                return ResourceManager.GetString("CREATESTAMPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Time.
        /// </summary>
        public static string CREATETIME {
            get {
                return ResourceManager.GetString("CREATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CREATEUSER {
            get {
                return ResourceManager.GetString("CREATEUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating New Customer.
        /// </summary>
        public static string CREATINGNEWCUSTOMER {
            get {
                return ResourceManager.GetString("CREATINGNEWCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating New Order.
        /// </summary>
        public static string CREATINGNEWORDER {
            get {
                return ResourceManager.GetString("CREATINGNEWORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating New Order Items.
        /// </summary>
        public static string CREATINGNEWORDERITEMS {
            get {
                return ResourceManager.GetString("CREATINGNEWORDERITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating New Shipping Order.
        /// </summary>
        public static string CREATINGNEWSHIPPINGADDRESS {
            get {
                return ResourceManager.GetString("CREATINGNEWSHIPPINGADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CUSTOMER {
            get {
                return ResourceManager.GetString("CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Billing Address Line.
        /// </summary>
        public static string CUSTOMERBILLINGADDRESSLINE {
            get {
                return ResourceManager.GetString("CUSTOMERBILLINGADDRESSLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Contact Full Name.
        /// </summary>
        public static string CUSTOMERCONTACTFULLNAME {
            get {
                return ResourceManager.GetString("CUSTOMERCONTACTFULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Count.
        /// </summary>
        public static string CUSTOMERCOUNT {
            get {
                return ResourceManager.GetString("CUSTOMERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Internal ID.
        /// </summary>
        public static string CUSTOMERINTERNALID {
            get {
                return ResourceManager.GetString("CUSTOMERINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CUSTOMERNAME {
            get {
                return ResourceManager.GetString("CUSTOMERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number.
        /// </summary>
        public static string CUSTOMERNUMBER {
            get {
                return ResourceManager.GetString("CUSTOMERNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Telephone.
        /// </summary>
        public static string CUSTOMERTELEPHONE {
            get {
                return ResourceManager.GetString("CUSTOMERTELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Memo.
        /// </summary>
        public static string DELIVERYMEMO {
            get {
                return ResourceManager.GetString("DELIVERYMEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DETAILTABTEXT {
            get {
                return ResourceManager.GetString("DETAILTABTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string DISCONTINUED {
            get {
                return ResourceManager.GetString("DISCONTINUED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounted Order Count.
        /// </summary>
        public static string DISCOUNTEDORDERCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNTEDORDERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount (Percent).
        /// </summary>
        public static string DISCOUNTPERCENT {
            get {
                return ResourceManager.GetString("DISCOUNTPERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Customer Information.
        /// </summary>
        public static string ENTERCUSTOMERINFORMATION {
            get {
                return ResourceManager.GetString("ENTERCUSTOMERINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Order Information.
        /// </summary>
        public static string ENTERORDERINFORMATION {
            get {
                return ResourceManager.GetString("ENTERORDERINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Order Item Information.
        /// </summary>
        public static string ENTERORDERITEMINFORMATION {
            get {
                return ResourceManager.GetString("ENTERORDERITEMINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Shipping Address Information.
        /// </summary>
        public static string ENTERSHIPPINGADDRESSINFORMATION {
            get {
                return ResourceManager.GetString("ENTERSHIPPINGADDRESSINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating New Customer.
        /// </summary>
        public static string ERRORCREATINGNEWCUSTOMER {
            get {
                return ResourceManager.GetString("ERRORCREATINGNEWCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating New Order.
        /// </summary>
        public static string ERRORCREATINGNEWORDER {
            get {
                return ResourceManager.GetString("ERRORCREATINGNEWORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating New Order Items.
        /// </summary>
        public static string ERRORCREATINGNEWORDERITEMS {
            get {
                return ResourceManager.GetString("ERRORCREATINGNEWORDERITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating New Shipping Order.
        /// </summary>
        public static string ERRORCREATINGNEWSHIPPINGADDRESS {
            get {
                return ResourceManager.GetString("ERRORCREATINGNEWSHIPPINGADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Customer.
        /// </summary>
        public static string EXISTINGCUSTOMER {
            get {
                return ResourceManager.GetString("EXISTINGCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Shipping Address.
        /// </summary>
        public static string EXISTINGSHIPPINGADDRESS {
            get {
                return ResourceManager.GetString("EXISTINGSHIPPINGADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended.
        /// </summary>
        public static string EXTENDED {
            get {
                return ResourceManager.GetString("EXTENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string FALSEFLAG {
            get {
                return ResourceManager.GetString("FALSEFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Order Date.
        /// </summary>
        public static string FIRSTORDERDATE {
            get {
                return ResourceManager.GetString("FIRSTORDERDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Order Time.
        /// </summary>
        public static string FIRSTORDERTIME {
            get {
                return ResourceManager.GetString("FIRSTORDERTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FULLNAME {
            get {
                return ResourceManager.GetString("FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Discount.
        /// </summary>
        public static string HIGHESTDISCOUNT {
            get {
                return ResourceManager.GetString("HIGHESTDISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Order Subtotal.
        /// </summary>
        public static string HIGHESTORDERSUBTOTAL {
            get {
                return ResourceManager.GetString("HIGHESTORDERSUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Order Total.
        /// </summary>
        public static string HIGHESTORDERTOTAL {
            get {
                return ResourceManager.GetString("HIGHESTORDERTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Order Unit Price.
        /// </summary>
        public static string HIGHESTORDERUNITPRICE {
            get {
                return ResourceManager.GetString("HIGHESTORDERUNITPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDs.
        /// </summary>
        public static string IDS {
            get {
                return ResourceManager.GetString("IDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Path.
        /// </summary>
        public static string IMAGEPATH {
            get {
                return ResourceManager.GetString("IMAGEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Order Count.
        /// </summary>
        public static string INCOMPLETEORDERCOUNT {
            get {
                return ResourceManager.GetString("INCOMPLETEORDERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a Parent Customer.
        /// </summary>
        public static string ISAPARENTCUSTOMER {
            get {
                return ResourceManager.GetString("ISAPARENTCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a Sub-Customer.
        /// </summary>
        public static string ISASUBCUSTOMER {
            get {
                return ResourceManager.GetString("ISASUBCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Parent Customer.
        /// </summary>
        public static string ISPARENTCUSTOMER {
            get {
                return ResourceManager.GetString("ISPARENTCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Parent Customer.
        /// </summary>
        public static string ISPARTENTCUSTOMER {
            get {
                return ResourceManager.GetString("ISPARTENTCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Sub-Customer.
        /// </summary>
        public static string ISSUBCUSTOMER {
            get {
                return ResourceManager.GetString("ISSUBCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string ITEMS {
            get {
                return ResourceManager.GetString("ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest Order Quantity.
        /// </summary>
        public static string LARGESTORDERQUANTITY {
            get {
                return ResourceManager.GetString("LARGESTORDERQUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change Date.
        /// </summary>
        public static string LASTCHANGEDATE {
            get {
                return ResourceManager.GetString("LASTCHANGEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change Job.
        /// </summary>
        public static string LASTCHANGEJOB {
            get {
                return ResourceManager.GetString("LASTCHANGEJOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change Job Number.
        /// </summary>
        public static string LASTCHANGEJOBNUMBER {
            get {
                return ResourceManager.GetString("LASTCHANGEJOBNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change Time.
        /// </summary>
        public static string LASTCHANGETIME {
            get {
                return ResourceManager.GetString("LASTCHANGETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change User.
        /// </summary>
        public static string LASTCHANGEUSER {
            get {
                return ResourceManager.GetString("LASTCHANGEUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order Date.
        /// </summary>
        public static string LASTORDERDATE {
            get {
                return ResourceManager.GetString("LASTORDERDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order Date Time.
        /// </summary>
        public static string LASTORDERDATETIME {
            get {
                return ResourceManager.GetString("LASTORDERDATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order ID.
        /// </summary>
        public static string LASTORDERID {
            get {
                return ResourceManager.GetString("LASTORDERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order Status.
        /// </summary>
        public static string LASTORDERSTATUS {
            get {
                return ResourceManager.GetString("LASTORDERSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order Time.
        /// </summary>
        public static string LASTORDERTIME {
            get {
                return ResourceManager.GetString("LASTORDERTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Used Shipping Address ID.
        /// </summary>
        public static string LASTUSEDSHIPPINGADDRESSID {
            get {
                return ResourceManager.GetString("LASTUSEDSHIPPINGADDRESSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Used Shipping Address Line.
        /// </summary>
        public static string LASTUSEDSHIPPINGADDRESSLINE {
            get {
                return ResourceManager.GetString("LASTUSEDSHIPPINGADDRESSLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Used Shipping Address Name.
        /// </summary>
        public static string LASTUSEDSHIPPINGADDRESSNAME {
            get {
                return ResourceManager.GetString("LASTUSEDSHIPPINGADDRESSNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name.
        /// </summary>
        public static string LEGALNAME {
            get {
                return ResourceManager.GetString("LEGALNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Price.
        /// </summary>
        public static string LISTPRICE {
            get {
                return ResourceManager.GetString("LISTPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Management.
        /// </summary>
        public static string LOGONSYSTEMNAME {
            get {
                return ResourceManager.GetString("LOGONSYSTEMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Management Logon.
        /// </summary>
        public static string LOGONTITLETEXT {
            get {
                return ResourceManager.GetString("LOGONTITLETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest Discount.
        /// </summary>
        public static string LOWESTDISCOUNT {
            get {
                return ResourceManager.GetString("LOWESTDISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest Order Subtotal.
        /// </summary>
        public static string LOWESTORDERSUBTOTAL {
            get {
                return ResourceManager.GetString("LOWESTORDERSUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest Order Total.
        /// </summary>
        public static string LOWESTORDERTOTAL {
            get {
                return ResourceManager.GetString("LOWESTORDERTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest Order Unit Price.
        /// </summary>
        public static string LOWESTORDERUNITPRICE {
            get {
                return ResourceManager.GetString("LOWESTORDERUNITPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string MEMO {
            get {
                return ResourceManager.GetString("MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Reorder Quantity.
        /// </summary>
        public static string MINIMUMREORDERQUANTITY {
            get {
                return ResourceManager.GetString("MINIMUMREORDERQUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Order Items.
        /// </summary>
        public static string NOORDERITEMS {
            get {
                return ResourceManager.GetString("NOORDERITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records.
        /// </summary>
        public static string NORECORDS {
            get {
                return ResourceManager.GetString("NORECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string ORDER {
            get {
                return ResourceManager.GetString("ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Confirmation.
        /// </summary>
        public static string ORDERCONFIRMATION {
            get {
                return ResourceManager.GetString("ORDERCONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Count.
        /// </summary>
        public static string ORDERCOUNT {
            get {
                return ResourceManager.GetString("ORDERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string ORDERDATE {
            get {
                return ResourceManager.GetString("ORDERDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered Items Count.
        /// </summary>
        public static string ORDEREDITEMSCOUNT {
            get {
                return ResourceManager.GetString("ORDEREDITEMSCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered Products Count.
        /// </summary>
        public static string ORDEREDPRODUCTSCOUNT {
            get {
                return ResourceManager.GetString("ORDEREDPRODUCTSCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Internal ID.
        /// </summary>
        public static string ORDERINTERNALID {
            get {
                return ResourceManager.GetString("ORDERINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Item.
        /// </summary>
        public static string ORDERITEM {
            get {
                return ResourceManager.GetString("ORDERITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Item Count.
        /// </summary>
        public static string ORDERITEMCOUNT {
            get {
                return ResourceManager.GetString("ORDERITEMCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Item Internal ID.
        /// </summary>
        public static string ORDERITEMINTERNALID {
            get {
                return ResourceManager.GetString("ORDERITEMINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Memo.
        /// </summary>
        public static string ORDERMEMO {
            get {
                return ResourceManager.GetString("ORDERMEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Price.
        /// </summary>
        public static string ORDERPRICE {
            get {
                return ResourceManager.GetString("ORDERPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Information.
        /// </summary>
        public static string ORDERSINFORMATION {
            get {
                return ResourceManager.GetString("ORDERSINFORMATION", resourceCulture);
            }
        }
        
        ///   Looks up a localized string similar to Order Successfully Created.
        /// </summary>
        public static string ORDERSUCCESSFULLYCREATED {
            get {
                return ResourceManager.GetString("ORDERSUCCESSFULLYCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Time.
        /// </summary>
        public static string ORDERTIME {
            get {
                return ResourceManager.GetString("ORDERTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Wizard.
        /// </summary>
        public static string ORDERWIZARD {
            get {
                return ResourceManager.GetString("ORDERWIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string PARENT {
            get {
                return ResourceManager.GetString("PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Company Name.
        /// </summary>
        public static string PARENTCOMPANYNAME {
            get {
                return ResourceManager.GetString("PARENTCOMPANYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Customer Address Line.
        /// </summary>
        public static string PARENTCUSTOMERADDRESSLINE {
            get {
                return ResourceManager.GetString("PARENTCUSTOMERADDRESSLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Customer Contact Full Name.
        /// </summary>
        public static string PARENTCUSTOMERCONTACTFULLNAME {
            get {
                return ResourceManager.GetString("PARENTCUSTOMERCONTACTFULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Customer Name.
        /// </summary>
        public static string PARENTCUSTOMERNAME {
            get {
                return ResourceManager.GetString("PARENTCUSTOMERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Customer Number.
        /// </summary>
        public static string PARENTCUSTOMERNUMBER {
            get {
                return ResourceManager.GetString("PARENTCUSTOMERNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Customer Telephone.
        /// </summary>
        public static string PARENTCUSTOMERTELEPHONE {
            get {
                return ResourceManager.GetString("PARENTCUSTOMERTELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Internal ID.
        /// </summary>
        public static string PARENTINTERNALID {
            get {
                return ResourceManager.GetString("PARENTINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        public static string PARENTNAME {
            get {
                return ResourceManager.GetString("PARENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Relationship.
        /// </summary>
        public static string PARENTRELATIONSHIP {
            get {
                return ResourceManager.GetString("PARENTRELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Pick Customer.
        /// </summary>
        public static string PLEASEPICKCUSTOMER {
            get {
                return ResourceManager.GetString("PLEASEPICKCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Pick Shipping Address.
        /// </summary>
        public static string PLEASEPICKSHIPPINGADDRESS {
            get {
                return ResourceManager.GetString("PLEASEPICKSHIPPINGADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Products.
        /// </summary>
        public static string POPULARPRODUCTS {
            get {
                return ResourceManager.GetString("POPULARPRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string POSTALCODE {
            get {
                return ResourceManager.GetString("POSTALCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Complete.
        /// </summary>
        public static string PROCESSINGCOMPLETE {
            get {
                return ResourceManager.GetString("PROCESSINGCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proccessing Started.
        /// </summary>
        public static string PROCESSINGSTARTED {
            get {
                return ResourceManager.GetString("PROCESSINGSTARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string PRODUCTCODE {
            get {
                return ResourceManager.GetString("PRODUCTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Internal ID.
        /// </summary>
        public static string PRODUCTINTERNALID {
            get {
                return ResourceManager.GetString("PRODUCTINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string PRODUCTNAME {
            get {
                return ResourceManager.GetString("PRODUCTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Ordered Count.
        /// </summary>
        public static string PRODUCTSORDEREDCOUNT {
            get {
                return ResourceManager.GetString("PRODUCTSORDEREDCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Number.
        /// </summary>
        public static string PURCHASEORDERNUMBERID {
            get {
                return ResourceManager.GetString("PURCHASEORDERNUMBERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Points.
        /// </summary>
        public static string PURCHASEPOINTS {
            get {
                return ResourceManager.GetString("PURCHASEPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QUANTITY {
            get {
                return ResourceManager.GetString("QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Orders.
        /// </summary>
        public static string RECENTORDERS {
            get {
                return ResourceManager.GetString("RECENTORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        public static string REMOVEITEM {
            get {
                return ResourceManager.GetString("REMOVEITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string REORDERLEVEL {
            get {
                return ResourceManager.GetString("REORDERLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Person Internal ID.
        /// </summary>
        public static string SALESPERSONINTERNALID {
            get {
                return ResourceManager.GetString("SALESPERSONINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Person Name.
        /// </summary>
        public static string SALESPERSONNAME {
            get {
                return ResourceManager.GetString("SALESPERSONNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string SHIPPING {
            get {
                return ResourceManager.GetString("SHIPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string SHIPPINGADDRESS {
            get {
                return ResourceManager.GetString("SHIPPINGADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Block.
        /// </summary>
        public static string SHIPPINGADDRESSBLOCK {
            get {
                return ResourceManager.GetString("SHIPPINGADDRESSBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Count.
        /// </summary>
        public static string SHIPPINGADDRESSCOUNT {
            get {
                return ResourceManager.GetString("SHIPPINGADDRESSCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Internal ID.
        /// </summary>
        public static string SHIPPINGADDRESSINTERNALID {
            get {
                return ResourceManager.GetString("SHIPPINGADDRESSINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Line.
        /// </summary>
        public static string SHIPPINGADDRESSLINE {
            get {
                return ResourceManager.GetString("SHIPPINGADDRESSLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address List.
        /// </summary>
        public static string SHIPPINGADDRESSLIST {
            get {
                return ResourceManager.GetString("SHIPPINGADDRESSLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Name.
        /// </summary>
        public static string SHIPPINGADDRESSNAME {
            get {
                return ResourceManager.GetString("SHIPPINGADDRESSNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallest Order Quantity.
        /// </summary>
        public static string SMALLESTORDERQUANTITY {
            get {
                return ResourceManager.GetString("SMALLESTORDERQUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Existing.
        /// </summary>
        public static string SPECIFYEXISTING {
            get {
                return ResourceManager.GetString("SPECIFYEXISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Existing Shipping Address.
        /// </summary>
        public static string SPECIFYEXISTINGSHIPPINGADDRESS {
            get {
                return ResourceManager.GetString("SPECIFYEXISTINGSHIPPINGADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Cost.
        /// </summary>
        public static string STANDARDCOST {
            get {
                return ResourceManager.GetString("STANDARDCOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Customer Count.
        /// </summary>
        public static string SUBCUSTOMERCOUNT {
            get {
                return ResourceManager.GetString("SUBCUSTOMERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Customer List.
        /// </summary>
        public static string SUBCUSTOMERLIST {
            get {
                return ResourceManager.GetString("SUBCUSTOMERLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Level.
        /// </summary>
        public static string TARGETLEVEL {
            get {
                return ResourceManager.GetString("TARGETLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string TELEPHONE {
            get {
                return ResourceManager.GetString("TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string TOTALCOST {
            get {
                return ResourceManager.GetString("TOTALCOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string TRUEFLAG {
            get {
                return ResourceManager.GetString("TRUEFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Discount.
        /// </summary>
        public static string UNITDISCOUNT {
            get {
                return ResourceManager.GetString("UNITDISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UNITPRICE {
            get {
                return ResourceManager.GetString("UNITPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Internal ID.
        /// </summary>
        public static string WAREHOUSEINTERNALID {
            get {
                return ResourceManager.GetString("WAREHOUSEINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Name.
        /// </summary>
        public static string WAREHOUSENAME {
            get {
                return ResourceManager.GetString("WAREHOUSENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string WEATHER {
            get {
                return ResourceManager.GetString("WEATHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string WIZARDSTART {
            get {
                return ResourceManager.GetString("WIZARDSTART", resourceCulture);
            }
        }
    }
}
