//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOS.OrderManagement.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DescriptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOS.OrderManagement.Shared.Properties.DescriptionResource", typeof(DescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string ADDRESS1 {
            get {
                return ResourceManager.GetString("ADDRESS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string ADDRESS2 {
            get {
                return ResourceManager.GetString("ADDRESS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string ADDRESS3 {
            get {
                return ResourceManager.GetString("ADDRESS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Stamps.
        /// </summary>
        public static string AUDITSTAMPTABTEXT {
            get {
                return ResourceManager.GetString("AUDITSTAMPTABTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string BASIC {
            get {
                return ResourceManager.GetString("BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BILLINGADDRESS {
            get {
                return ResourceManager.GetString("BILLINGADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address 1.
        /// </summary>
        public static string BILLINGADDRESS1 {
            get {
                return ResourceManager.GetString("BILLINGADDRESS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address 2.
        /// </summary>
        public static string BILLINGADDRESS2 {
            get {
                return ResourceManager.GetString("BILLINGADDRESS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address 3.
        /// </summary>
        public static string BILLINGADDRESS3 {
            get {
                return ResourceManager.GetString("BILLINGADDRESS3", resourceCulture);
            }
        }

        ///   Looks up a localized string similar to Billing Address Block.
        /// </summary>
        public static string BILLINGADDRESSBLOCK {
            get {
                return ResourceManager.GetString("BILLINGADDRESSBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address Block.
        /// </summary>
        public static string BILLINGADDRESSBLOCK {
            get {
                return ResourceManager.GetString("BILLINGADDRESSBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Country.
        /// </summary>
        public static string BILLINGCOUNTRY {
            get {
                return ResourceManager.GetString("BILLINGCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Postal Code.
        /// </summary>
        public static string BILLINGPOSTALCODE {
            get {
                return ResourceManager.GetString("BILLINGPOSTALCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Postal Code.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact First Name.
        /// </summary>
        public static string CONTACTFIRSTNAME {
            get {
                return ResourceManager.GetString("CONTACTFIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Full Name.
        /// </summary>
        public static string CONTACTFULLNAME {
            get {
                return ResourceManager.GetString("CONTACTFULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Last Name.
        /// </summary>
        public static string CONTACTLASTNAME {
            get {
                return ResourceManager.GetString("CONTACTLASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Middle Name.
        /// </summary>
        public static string CONTACTMIDDLENAME {
            get {
                return ResourceManager.GetString("CONTACTMIDDLENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Nick Name.
        /// </summary>
        public static string CONTACTNICKNAME {
            get {
                return ResourceManager.GetString("CONTACTNICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CREATEDATE {
            get {
                return ResourceManager.GetString("CREATEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job.
        /// </summary>
        public static string CREATEJOB {
            get {
                return ResourceManager.GetString("CREATEJOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job Number.
        /// </summary>
        public static string CREATEJOBNUMBER {
            get {
                return ResourceManager.GetString("CREATEJOBNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Time.
        /// </summary>
        public static string CREATETIME {
            get {
                return ResourceManager.GetString("CREATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CREATEUSER {
            get {
                return ResourceManager.GetString("CREATEUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Internal ID.
        /// </summary>
        public static string CUSTOMERINTERNALID {
            get {
                return ResourceManager.GetString("CUSTOMERINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CUSTOMERNAME {
            get {
                return ResourceManager.GetString("CUSTOMERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Memo.
        /// </summary>
        public static string DELIVERYMEMO {
            get {
                return ResourceManager.GetString("DELIVERYMEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DETAILTABTEXT {
            get {
                return ResourceManager.GetString("DETAILTABTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string DISCONTINUED {
            get {
                return ResourceManager.GetString("DISCONTINUED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DISCOUNTPERCENT {
            get {
                return ResourceManager.GetString("DISCOUNTPERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended.
        /// </summary>
        public static string EXTENDED {
            get {
                return ResourceManager.GetString("EXTENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string FALSEFLAG {
            get {
                return ResourceManager.GetString("FALSEFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FULLNAME {
            get {
                return ResourceManager.GetString("FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Path.
        /// </summary>
        public static string IMAGEPATH {
            get {
                return ResourceManager.GetString("IMAGEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a Sub-Customer.
        /// </summary>
        public static string ISASUBCUSTOMER {
            get {
                return ResourceManager.GetString("ISASUBCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change Date.
        /// </summary>
        public static string LASTCHANGEDATE {
            get {
                return ResourceManager.GetString("LASTCHANGEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change Job.
        /// </summary>
        public static string LASTCHANGEJOB {
            get {
                return ResourceManager.GetString("LASTCHANGEJOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change Job Number.
        /// </summary>
        public static string LASTCHANGEJOBNUMBER {
            get {
                return ResourceManager.GetString("LASTCHANGEJOBNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change Time.
        /// </summary>
        public static string LASTCHANGETIME {
            get {
                return ResourceManager.GetString("LASTCHANGETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change User.
        /// </summary>
        public static string LASTCHANGEUSER {
            get {
                return ResourceManager.GetString("LASTCHANGEUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name.
        /// </summary>
        public static string LEGALNAME {
            get {
                return ResourceManager.GetString("LEGALNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Price.
        /// </summary>
        public static string LISTPRICE {
            get {
                return ResourceManager.GetString("LISTPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Management.
        /// </summary>
        public static string LOGONSYSTEMNAME {
            get {
                return ResourceManager.GetString("LOGONSYSTEMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Management Logon.
        /// </summary>
        public static string LOGONTITLETEXT {
            get {
                return ResourceManager.GetString("LOGONTITLETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string MEMO {
            get {
                return ResourceManager.GetString("MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Reorder Quantity.
        /// </summary>
        public static string MINIMUMREORDERQUANTITY {
            get {
                return ResourceManager.GetString("MINIMUMREORDERQUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records.
        /// </summary>
        public static string NORECORDS {
            get {
                return ResourceManager.GetString("NORECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string ORDERDATE {
            get {
                return ResourceManager.GetString("ORDERDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Internal ID.
        /// </summary>
        public static string ORDERINTERNALID {
            get {
                return ResourceManager.GetString("ORDERINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Item Internal ID.
        /// </summary>
        public static string ORDERITEMINTERNALID {
            get {
                return ResourceManager.GetString("ORDERITEMINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Memo.
        /// </summary>
        public static string ORDERMEMO {
            get {
                return ResourceManager.GetString("ORDERMEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Time.
        /// </summary>
        public static string ORDERTIME {
            get {
                return ResourceManager.GetString("ORDERTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Internal ID.
        /// </summary>
        public static string PARENTINTERNALID {
            get {
                return ResourceManager.GetString("PARENTINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        public static string PARENTNAME {
            get {
                return ResourceManager.GetString("PARENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Relationship.
        /// </summary>
        public static string PARENTRELATIONSHIP {
            get {
                return ResourceManager.GetString("PARENTRELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Products.
        /// </summary>
        public static string POPULARPRODUCTS {
            get {
                return ResourceManager.GetString("POPULARPRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string POSTALCODE {
            get {
                return ResourceManager.GetString("POSTALCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string PRODUCTCODE {
            get {
                return ResourceManager.GetString("PRODUCTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Internal ID.
        /// </summary>
        public static string PRODUCTINTERNALID {
            get {
                return ResourceManager.GetString("PRODUCTINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string PRODUCTNAME {
            get {
                return ResourceManager.GetString("PRODUCTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Number/ID.
        /// </summary>
        public static string PURCHASEORDERNUMBERID {
            get {
                return ResourceManager.GetString("PURCHASEORDERNUMBERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Points.
        /// </summary>
        public static string PURCHASEPOINTS {
            get {
                return ResourceManager.GetString("PURCHASEPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QUANTITY {
            get {
                return ResourceManager.GetString("QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Orders.
        /// </summary>
        public static string RECENTORDERS {
            get {
                return ResourceManager.GetString("RECENTORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string REORDERLEVEL {
            get {
                return ResourceManager.GetString("REORDERLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Person Internal ID.
        /// </summary>
        public static string SALESPERSONINTERNALID {
            get {
                return ResourceManager.GetString("SALESPERSONINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Person Name.
        /// </summary>
        public static string SALESPERSONNAME {
            get {
                return ResourceManager.GetString("SALESPERSONNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Internal ID.
        /// </summary>
        public static string SHIPPINGADDRESSINTERNALID {
            get {
                return ResourceManager.GetString("SHIPPINGADDRESSINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Name.
        /// </summary>
        public static string SHIPPINGADDRESSNAME {
            get {
                return ResourceManager.GetString("SHIPPINGADDRESSNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Cost.
        /// </summary>
        public static string STANDARDCOST {
            get {
                return ResourceManager.GetString("STANDARDCOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Level.
        /// </summary>
        public static string TARGETLEVEL {
            get {
                return ResourceManager.GetString("TARGETLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string TELEPHONE {
            get {
                return ResourceManager.GetString("TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string TRUEFLAG {
            get {
                return ResourceManager.GetString("TRUEFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string TRUEFLAG {
            get {
                return ResourceManager.GetString("TRUEFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UNITPRICE {
            get {
                return ResourceManager.GetString("UNITPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Internal ID.
        /// </summary>
        public static string WAREHOUSEINTERNALID {
            get {
                return ResourceManager.GetString("WAREHOUSEINTERNALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Name.
        /// </summary>
        public static string WAREHOUSENAME {
            get {
                return ResourceManager.GetString("WAREHOUSENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string WEATHER {
            get {
                return ResourceManager.GetString("WEATHER", resourceCulture);
            }
        }
    }
}
