//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOS.OrderManagement.Shared.Properties
{


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class MessageResource
	{

		private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        ///   Looks up a localized string similar to Establishing Re:new connection {0} of ESTABLISHINGCONNECTION.
        /// </summary>
        public static string ESTABLISHINGCONNECTION {
        get {
        return ResourceManager.GetString("ESTABLISHINGCONNECTION", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string TITLESUBBROWSER {
        get {
        return ResourceManager.GetString("TITLESUBBROWSER", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to {ModuleName} Detail.
        /// </summary>
        public static string TITLEOPEN {
        get {
        return ResourceManager.GetString("TITLEOPEN", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to {ModuleName}  Detail - New.
        /// </summary>
        public static string TITLENEW {
        get {
        return ResourceManager.GetString("TITLENEW", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to {ModuleName} Detail.
        /// </summary>
        public static string TITLEDISPLAY {
        get {
        return ResourceManager.GetString("TITLEDISPLAY", resourceCulture);
        }
        }
      

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal MessageResource()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if ((resourceMan == null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOS.OrderManagement.Shared.Properties.MessageResource", typeof(MessageResource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}
		
		// A4DN Resources
	}
}