//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOS.OrderManagement.ViewModels.ShippingAddress.ServiceProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeOffset", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateTimeOffset : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private short OffsetMinutesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                if ((this.DateTimeField.Equals(value) != true))
                {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short OffsetMinutes
        {
            get
            {
                return this.OffsetMinutesField;
            }
            set
            {
                if ((this.OffsetMinutesField.Equals(value) != true))
                {
                    this.OffsetMinutesField = value;
                    this.RaisePropertyChanged("OffsetMinutes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BOS.OrderManagement.ViewModels.ShippingAddress.ServiceProxy.IShippingAddressBPSer" +
        "viceContract")]
    public interface IShippingAddressBPServiceContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/Insert", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/InsertResponse")]
        A4DN.Core.BOS.Base.AB_InsertReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> Insert(A4DN.Core.BOS.Base.AB_InsertInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchInsert", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchInsertResponse")]
        A4DN.Core.BOS.Base.AB_BatchInsertReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> BatchInsert(A4DN.Core.BOS.Base.AB_BatchInsertInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/Fetch", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/FetchResponse")]
        A4DN.Core.BOS.Base.AB_FetchReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> Fetch(A4DN.Core.BOS.Base.AB_FetchInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/Delete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_PermDeleteReturnArgs Delete(A4DN.Core.BOS.Base.AB_PermDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs BatchDelete(A4DN.Core.BOS.Base.AB_BatchPermDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/SoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/SoftDeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_SoftDeleteReturnArgs SoftDelete(A4DN.Core.BOS.Base.AB_SoftDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchSoftDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs BatchSoftDelete(A4DN.Core.BOS.Base.AB_BatchSoftDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/RestoreSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/RestoreSoftDeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_RestoreSoftDeleteReturnArgs RestoreSoftDelete(A4DN.Core.BOS.Base.AB_RestoreSoftDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchRestoreSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchRestoreSoftDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs BatchRestoreSoftDelete(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/Select", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/SelectResponse")]
        A4DN.Core.BOS.Base.AB_SelectReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> Select(A4DN.Core.BOS.Base.AB_SelectInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/Update", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/UpdateResponse")]
        A4DN.Core.BOS.Base.AB_UpdateReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> Update(A4DN.Core.BOS.Base.AB_UpdateInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchUpdate", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/BatchUpdateResponse")]
        A4DN.Core.BOS.Base.AB_BatchUpdateReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> BatchUpdate(A4DN.Core.BOS.Base.AB_BatchUpdateInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/ProcessRequest", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/ProcessRequestResponse")]
        A4DN.Core.BOS.Base.AB_ProcessRequestReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> ProcessRequest(A4DN.Core.BOS.Base.AB_ProcessRequestInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/am_GetTitleService", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/am_GetTitleServiceResponse")]
        A4DN.Core.BOS.Base.AB_GetTitleReturnArgs am_GetTitleService(A4DN.Core.BOS.Base.AB_GetTitleInputArgs InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/am_GetMessageTextForRecordService", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_ShippingAddress" +
            "Entity/am_GetMessageTextForRecordServiceResponse")]
        A4DN.Core.BOS.Base.AB_GetMessageForRecordReturnArgs am_GetMessageTextForRecordService(A4DN.Core.BOS.Base.AB_GetMessageTextForRecordInputArgs InputArgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShippingAddressBPServiceContractChannel : BOS.OrderManagement.ViewModels.ShippingAddress.ServiceProxy.IShippingAddressBPServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShippingAddressBPServiceContractClient : System.ServiceModel.ClientBase<BOS.OrderManagement.ViewModels.ShippingAddress.ServiceProxy.IShippingAddressBPServiceContract>, BOS.OrderManagement.ViewModels.ShippingAddress.ServiceProxy.IShippingAddressBPServiceContract
    {
        
        public ShippingAddressBPServiceContractClient()
        {
        }
        
        public ShippingAddressBPServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ShippingAddressBPServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ShippingAddressBPServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ShippingAddressBPServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public A4DN.Core.BOS.Base.AB_InsertReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> Insert(A4DN.Core.BOS.Base.AB_InsertInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.Insert(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchInsertReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> BatchInsert(A4DN.Core.BOS.Base.AB_BatchInsertInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.BatchInsert(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_FetchReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> Fetch(A4DN.Core.BOS.Base.AB_FetchInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.Fetch(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_PermDeleteReturnArgs Delete(A4DN.Core.BOS.Base.AB_PermDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.Delete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs BatchDelete(A4DN.Core.BOS.Base.AB_BatchPermDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.BatchDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_SoftDeleteReturnArgs SoftDelete(A4DN.Core.BOS.Base.AB_SoftDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.SoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs BatchSoftDelete(A4DN.Core.BOS.Base.AB_BatchSoftDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.BatchSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_RestoreSoftDeleteReturnArgs RestoreSoftDelete(A4DN.Core.BOS.Base.AB_RestoreSoftDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.RestoreSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs BatchRestoreSoftDelete(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.BatchRestoreSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_SelectReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> Select(A4DN.Core.BOS.Base.AB_SelectInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.Select(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_UpdateReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> Update(A4DN.Core.BOS.Base.AB_UpdateInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.Update(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchUpdateReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> BatchUpdate(A4DN.Core.BOS.Base.AB_BatchUpdateInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.BatchUpdate(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_ProcessRequestReturnArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> ProcessRequest(A4DN.Core.BOS.Base.AB_ProcessRequestInputArgs<BOS.ShippingAddressDataEntity.ShippingAddressEntity> InputArgs)
        {
            return base.Channel.ProcessRequest(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_GetTitleReturnArgs am_GetTitleService(A4DN.Core.BOS.Base.AB_GetTitleInputArgs InputArgs)
        {
            return base.Channel.am_GetTitleService(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_GetMessageForRecordReturnArgs am_GetMessageTextForRecordService(A4DN.Core.BOS.Base.AB_GetMessageTextForRecordInputArgs InputArgs)
        {
            return base.Channel.am_GetMessageTextForRecordService(InputArgs);
        }
    }
}
