SET SCHEMA EASYBUYDEV;
CREATE OR REPLACE TABLE "WeatherAPI_Current"
( 
   "weatherid" FOR "WEATHERID" INTEGER,
    "app_temp" FOR "APP_TEMP" DECIMAL(5, 2),
    "aqi" FOR "AQI" INTEGER,
    "city_name" FOR "CITY_NAME" VARCHAR(100),
    "clouds" FOR "CLOUDS" INTEGER,
    "country_code" FOR "COUNTRY_CD" CHAR(2),
    "datetime" FOR "DATETIME" VARCHAR(16),
    "dewpt" FOR "DEWPT" DECIMAL(5, 2),
    "dhi" FOR "DHI" DECIMAL(7, 2),
    "dni" FOR "DNI" DECIMAL(7, 2),
    "elev_angle" FOR "ELEV_ANGL" DECIMAL(5, 2),
    "ghi" FOR "GHI" DECIMAL(7, 2),
    "gust" FOR "GUST" DECIMAL(7, 6),
    "h_angle" FOR "H_ANGLE" DECIMAL(5, 2),
    "lat" FOR "LAT" DECIMAL(7, 4),
    "lon" FOR "LON" DECIMAL(8, 4),
    "zipcode" FOR "ZIPCODE" CHAR(11),
    "ob_time" FOR "OB_TIME" TIMESTAMP,
    "pod" FOR "POD" CHAR(1),
    "precip" FOR "PRECIP" DECIMAL(5, 2),
    "pres" FOR "PRES" DECIMAL(6, 1),
    "rh" FOR "RH" INTEGER,
    "slp" FOR "SLP" DECIMAL(9, 5),
    "snow" FOR "SNOW" DECIMAL(5, 2),
    "solar_rad" FOR "SOLAR_RAD" DECIMAL(6, 1),
    "sources" FOR "SOURCES" VARCHAR(100),
    "state_code" FOR "STATE_CD" CHAR(2),
    "station" FOR "STATION" VARCHAR(10),
    "sunrise" FOR "SUNRISE" TIME,
    "sunset" FOR "SUNSET" TIME,
    "temp" FOR "TEMP" DECIMAL(5, 2),
    "timezone" FOR "TIMEZONE" VARCHAR(50),
    "ts" FOR "TS" BIGINT,
    "uv" FOR "UV" DECIMAL(7, 6),
    "vis" FOR "VIS" DECIMAL(5, 2),
    "weather_code" FOR "WEATHER_CD" INTEGER,
    "weather_description" FOR "WTHR_DESC" VARCHAR(100),
    "weather_icon" FOR "WTHR_ICO" VARCHAR(10),
    "wind_cdir" FOR "WIND_CDIR" CHAR(2),
    "wind_cdir_full" FOR "WIND_CD_FU" VARCHAR(10),
    "wind_dir" FOR "WIND_DIR" INTEGER,
    "wind_spd" FOR "WIND_SPD" DECIMAL(7, 6)
);

LABEL ON TABLE "WeatherAPI_Current"
   IS 'Weather API - Current';

LABEL ON COLUMN "WeatherAPI" (
    "weatherid" IS 'Weather ID',
    "app_temp" IS 'App Temp',
    "aqi" IS 'AQI',
    "city_name" IS 'City Name',
    "clouds" IS 'Clouds',
    "country_code" IS 'Country Code',
    "datetime" IS 'Datetime',
    "dewpt" IS 'Dew Point',
    "dhi" IS 'Diffuse Horizontal Irradiance',
    "dni" IS 'Direct Normal Irradiance',
    "elev_angle" IS 'Solar Elevation Angle',
    "ghi" IS 'Global Horizontal Irradiance',
    "gust" IS 'Wind Gust',
    "h_angle" IS 'Solar Hour Angle',
    "lat" IS 'Latitude',
    "lon" IS 'Longitude',
    "zipcode" IS 'Zip Code',
    "ob_time" IS 'Observation Time',
    "pod" IS 'Part of Day',
    "precip" IS 'Precipitation',
    "pres" IS 'Pressure',
    "rh" IS 'Relative Humidity',
    "slp" IS 'Sea Level Pressure',
    "snow" IS 'Snow',
    "solar_rad" IS 'Solar Radiation',
    "sources" IS 'Sources',
    "state_code" IS 'State Code',
    "station" IS 'Station',
    "sunrise" IS 'Sunrise',
    "sunset" IS 'Sunset',
    "temp" IS 'Temperature',
    "timezone" IS 'Timezone',
    "ts" IS 'Timestamp',
    "uv" IS 'UV Index',
    "vis" IS 'Visibility',
    "weather_code" IS 'Weather Code',
    "weather_description" IS 'Weather Description',
    "weather_icon" IS 'Weather Icon',
    "wind_cdir" IS 'Wind Direction',
    "wind_cdir_full" IS 'Wind Direction Full',
    "wind_dir" IS 'Wind Direction',
    "wind_spd" IS 'Wind Speed'
);