//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOS.OrderManagement.ViewModels.OrderItem.ServiceProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeOffset", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateTimeOffset : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private short OffsetMinutesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                if ((this.DateTimeField.Equals(value) != true))
                {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short OffsetMinutes
        {
            get
            {
                return this.OffsetMinutesField;
            }
            set
            {
                if ((this.OffsetMinutesField.Equals(value) != true))
                {
                    this.OffsetMinutesField = value;
                    this.RaisePropertyChanged("OffsetMinutes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BOS.OrderManagement.ViewModels.OrderItem.ServiceProxy.IOrderItemBPServiceContract" +
        "")]
    public interface IOrderItemBPServiceContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/Insert", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/InsertResponse")]
        A4DN.Core.BOS.Base.AB_InsertReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> Insert(A4DN.Core.BOS.Base.AB_InsertInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchInsert", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchInsertResponse")]
        A4DN.Core.BOS.Base.AB_BatchInsertReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> BatchInsert(A4DN.Core.BOS.Base.AB_BatchInsertInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/Fetch", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/FetchResponse")]
        A4DN.Core.BOS.Base.AB_FetchReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> Fetch(A4DN.Core.BOS.Base.AB_FetchInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/Delete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_PermDeleteReturnArgs Delete(A4DN.Core.BOS.Base.AB_PermDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs BatchDelete(A4DN.Core.BOS.Base.AB_BatchPermDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/SoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/SoftDeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_SoftDeleteReturnArgs SoftDelete(A4DN.Core.BOS.Base.AB_SoftDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchSoftDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs BatchSoftDelete(A4DN.Core.BOS.Base.AB_BatchSoftDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/RestoreSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/RestoreSoftDeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_RestoreSoftDeleteReturnArgs RestoreSoftDelete(A4DN.Core.BOS.Base.AB_RestoreSoftDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchRestoreSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchRestoreSoftDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs BatchRestoreSoftDelete(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/Select", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/SelectResponse")]
        A4DN.Core.BOS.Base.AB_SelectReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> Select(A4DN.Core.BOS.Base.AB_SelectInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/Update", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/UpdateResponse")]
        A4DN.Core.BOS.Base.AB_UpdateReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> Update(A4DN.Core.BOS.Base.AB_UpdateInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchUpdate", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/BatchUpdateResponse")]
        A4DN.Core.BOS.Base.AB_BatchUpdateReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> BatchUpdate(A4DN.Core.BOS.Base.AB_BatchUpdateInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/ProcessRequest", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/ProcessRequestResponse")]
        A4DN.Core.BOS.Base.AB_ProcessRequestReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> ProcessRequest(A4DN.Core.BOS.Base.AB_ProcessRequestInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/am_GetTitleService", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/am_GetTitleServiceResponse")]
        A4DN.Core.BOS.Base.AB_GetTitleReturnArgs am_GetTitleService(A4DN.Core.BOS.Base.AB_GetTitleInputArgs InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/am_GetMessageTextForRecordService", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderItemEntity" +
            "/am_GetMessageTextForRecordServiceResponse")]
        A4DN.Core.BOS.Base.AB_GetMessageForRecordReturnArgs am_GetMessageTextForRecordService(A4DN.Core.BOS.Base.AB_GetMessageTextForRecordInputArgs InputArgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderItemBPServiceContractChannel : BOS.OrderManagement.ViewModels.OrderItem.ServiceProxy.IOrderItemBPServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderItemBPServiceContractClient : System.ServiceModel.ClientBase<BOS.OrderManagement.ViewModels.OrderItem.ServiceProxy.IOrderItemBPServiceContract>, BOS.OrderManagement.ViewModels.OrderItem.ServiceProxy.IOrderItemBPServiceContract
    {
        
        public OrderItemBPServiceContractClient()
        {
        }
        
        public OrderItemBPServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public OrderItemBPServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public OrderItemBPServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public OrderItemBPServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public A4DN.Core.BOS.Base.AB_InsertReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> Insert(A4DN.Core.BOS.Base.AB_InsertInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.Insert(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchInsertReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> BatchInsert(A4DN.Core.BOS.Base.AB_BatchInsertInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.BatchInsert(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_FetchReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> Fetch(A4DN.Core.BOS.Base.AB_FetchInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.Fetch(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_PermDeleteReturnArgs Delete(A4DN.Core.BOS.Base.AB_PermDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.Delete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs BatchDelete(A4DN.Core.BOS.Base.AB_BatchPermDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.BatchDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_SoftDeleteReturnArgs SoftDelete(A4DN.Core.BOS.Base.AB_SoftDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.SoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs BatchSoftDelete(A4DN.Core.BOS.Base.AB_BatchSoftDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.BatchSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_RestoreSoftDeleteReturnArgs RestoreSoftDelete(A4DN.Core.BOS.Base.AB_RestoreSoftDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.RestoreSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs BatchRestoreSoftDelete(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.BatchRestoreSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_SelectReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> Select(A4DN.Core.BOS.Base.AB_SelectInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.Select(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_UpdateReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> Update(A4DN.Core.BOS.Base.AB_UpdateInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.Update(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchUpdateReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> BatchUpdate(A4DN.Core.BOS.Base.AB_BatchUpdateInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.BatchUpdate(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_ProcessRequestReturnArgs<BOS.OrderItemDataEntity.OrderItemEntity> ProcessRequest(A4DN.Core.BOS.Base.AB_ProcessRequestInputArgs<BOS.OrderItemDataEntity.OrderItemEntity> InputArgs)
        {
            return base.Channel.ProcessRequest(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_GetTitleReturnArgs am_GetTitleService(A4DN.Core.BOS.Base.AB_GetTitleInputArgs InputArgs)
        {
            return base.Channel.am_GetTitleService(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_GetMessageForRecordReturnArgs am_GetMessageTextForRecordService(A4DN.Core.BOS.Base.AB_GetMessageTextForRecordInputArgs InputArgs)
        {
            return base.Channel.am_GetMessageTextForRecordService(InputArgs);
        }
    }
}
