//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOS.OrderManagement.ViewModels.Order.ServiceProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeOffset", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateTimeOffset : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private short OffsetMinutesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                if ((this.DateTimeField.Equals(value) != true))
                {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short OffsetMinutes
        {
            get
            {
                return this.OffsetMinutesField;
            }
            set
            {
                if ((this.OffsetMinutesField.Equals(value) != true))
                {
                    this.OffsetMinutesField = value;
                    this.RaisePropertyChanged("OffsetMinutes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BOS.OrderManagement.ViewModels.Order.ServiceProxy.IOrderBPServiceContract")]
    public interface IOrderBPServiceContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Ins" +
            "ert", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Ins" +
            "ertResponse")]
        A4DN.Core.BOS.Base.AB_InsertReturnArgs<BOS.OrderDataEntity.OrderEntity> Insert(A4DN.Core.BOS.Base.AB_InsertInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chInsert", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chInsertResponse")]
        A4DN.Core.BOS.Base.AB_BatchInsertReturnArgs<BOS.OrderDataEntity.OrderEntity> BatchInsert(A4DN.Core.BOS.Base.AB_BatchInsertInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Fet" +
            "ch", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Fet" +
            "chResponse")]
        A4DN.Core.BOS.Base.AB_FetchReturnArgs<BOS.OrderDataEntity.OrderEntity> Fetch(A4DN.Core.BOS.Base.AB_FetchInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Del" +
            "ete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Del" +
            "eteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_PermDeleteReturnArgs Delete(A4DN.Core.BOS.Base.AB_PermDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs BatchDelete(A4DN.Core.BOS.Base.AB_BatchPermDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Sof" +
            "tDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Sof" +
            "tDeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_SoftDeleteReturnArgs SoftDelete(A4DN.Core.BOS.Base.AB_SoftDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chSoftDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs BatchSoftDelete(A4DN.Core.BOS.Base.AB_BatchSoftDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Res" +
            "toreSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Res" +
            "toreSoftDeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_RestoreSoftDeleteReturnArgs RestoreSoftDelete(A4DN.Core.BOS.Base.AB_RestoreSoftDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chRestoreSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chRestoreSoftDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs BatchRestoreSoftDelete(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Sel" +
            "ect", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Sel" +
            "ectResponse")]
        A4DN.Core.BOS.Base.AB_SelectReturnArgs<BOS.OrderDataEntity.OrderEntity> Select(A4DN.Core.BOS.Base.AB_SelectInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Upd" +
            "ate", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Upd" +
            "ateResponse")]
        A4DN.Core.BOS.Base.AB_UpdateReturnArgs<BOS.OrderDataEntity.OrderEntity> Update(A4DN.Core.BOS.Base.AB_UpdateInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chUpdate", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Bat" +
            "chUpdateResponse")]
        A4DN.Core.BOS.Base.AB_BatchUpdateReturnArgs<BOS.OrderDataEntity.OrderEntity> BatchUpdate(A4DN.Core.BOS.Base.AB_BatchUpdateInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Pro" +
            "cessRequest", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/Pro" +
            "cessRequestResponse")]
        A4DN.Core.BOS.Base.AB_ProcessRequestReturnArgs<BOS.OrderDataEntity.OrderEntity> ProcessRequest(A4DN.Core.BOS.Base.AB_ProcessRequestInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/am_" +
            "GetTitleService", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/am_" +
            "GetTitleServiceResponse")]
        A4DN.Core.BOS.Base.AB_GetTitleReturnArgs am_GetTitleService(A4DN.Core.BOS.Base.AB_GetTitleInputArgs InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/am_" +
            "GetMessageTextForRecordService", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_OrderEntity/am_" +
            "GetMessageTextForRecordServiceResponse")]
        A4DN.Core.BOS.Base.AB_GetMessageForRecordReturnArgs am_GetMessageTextForRecordService(A4DN.Core.BOS.Base.AB_GetMessageTextForRecordInputArgs InputArgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderBPServiceContractChannel : BOS.OrderManagement.ViewModels.Order.ServiceProxy.IOrderBPServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderBPServiceContractClient : System.ServiceModel.ClientBase<BOS.OrderManagement.ViewModels.Order.ServiceProxy.IOrderBPServiceContract>, BOS.OrderManagement.ViewModels.Order.ServiceProxy.IOrderBPServiceContract
    {
        
        public OrderBPServiceContractClient()
        {
        }
        
        public OrderBPServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public OrderBPServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public OrderBPServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public OrderBPServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public A4DN.Core.BOS.Base.AB_InsertReturnArgs<BOS.OrderDataEntity.OrderEntity> Insert(A4DN.Core.BOS.Base.AB_InsertInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.Insert(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchInsertReturnArgs<BOS.OrderDataEntity.OrderEntity> BatchInsert(A4DN.Core.BOS.Base.AB_BatchInsertInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.BatchInsert(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_FetchReturnArgs<BOS.OrderDataEntity.OrderEntity> Fetch(A4DN.Core.BOS.Base.AB_FetchInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.Fetch(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_PermDeleteReturnArgs Delete(A4DN.Core.BOS.Base.AB_PermDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.Delete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs BatchDelete(A4DN.Core.BOS.Base.AB_BatchPermDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.BatchDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_SoftDeleteReturnArgs SoftDelete(A4DN.Core.BOS.Base.AB_SoftDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.SoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs BatchSoftDelete(A4DN.Core.BOS.Base.AB_BatchSoftDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.BatchSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_RestoreSoftDeleteReturnArgs RestoreSoftDelete(A4DN.Core.BOS.Base.AB_RestoreSoftDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.RestoreSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs BatchRestoreSoftDelete(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.BatchRestoreSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_SelectReturnArgs<BOS.OrderDataEntity.OrderEntity> Select(A4DN.Core.BOS.Base.AB_SelectInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.Select(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_UpdateReturnArgs<BOS.OrderDataEntity.OrderEntity> Update(A4DN.Core.BOS.Base.AB_UpdateInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.Update(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchUpdateReturnArgs<BOS.OrderDataEntity.OrderEntity> BatchUpdate(A4DN.Core.BOS.Base.AB_BatchUpdateInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.BatchUpdate(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_ProcessRequestReturnArgs<BOS.OrderDataEntity.OrderEntity> ProcessRequest(A4DN.Core.BOS.Base.AB_ProcessRequestInputArgs<BOS.OrderDataEntity.OrderEntity> InputArgs)
        {
            return base.Channel.ProcessRequest(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_GetTitleReturnArgs am_GetTitleService(A4DN.Core.BOS.Base.AB_GetTitleInputArgs InputArgs)
        {
            return base.Channel.am_GetTitleService(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_GetMessageForRecordReturnArgs am_GetMessageTextForRecordService(A4DN.Core.BOS.Base.AB_GetMessageTextForRecordInputArgs InputArgs)
        {
            return base.Channel.am_GetMessageTextForRecordService(InputArgs);
        }
    }
}
