//===============================================================================================
// <A4DN_GeneratedInformation>
// This code was generated using the Accelerator for .Net Code Generator.
// <A4DN_Template Name="BOS.Module.Entity.t4" Version="8.0.0.93" GeneratedDate="5/29/2024" />
// </A4DN_GeneratedInformation>
//===============================================================================================
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using A4DN.Core.BOS.Base;
using BOS.OrderManagement.Shared.Properties;
#if !SILVERLIGHT
using A4DN.Core.BOS.ValidationAttributes;  // Custom validation attributes
#endif

namespace BOS.OrderDataEntity
{
    /// <summary>
    /// Represents data. Contains metadata that facilitates validation and advanced databinding.
    /// </summary>
    [DataContract]
    public class OrderEntity : AB_BusinessObjectEntityBase
    {
        /// <summary>
        /// Entity information is defined in the lower level entity to maximize performance by making it static
        /// </summary>
        private static AB_EntityInfo _EntityInfo;
        /// <summary>
        /// Gets metadata information about the entity
        /// </summary>
        public override AB_EntityInfo ap_EntityInfo
        {
            get => _EntityInfo;
        }

        /// <summary>
        /// Initializes static members
        /// </summary>
        static private void RG_DoStaticInit()
        {
            // Set Message and Description Primary and Secondary Resources. 
            AB_BusinessObjectEntityBase.am_GetPropertyInfo(typeof(OrderEntity), typeof(BOS.OrderManagement.Properties.MessageResource), typeof(MessageResource), typeof(BOS.OrderManagement.Properties.DescriptionResource), typeof(DescriptionResource), out _EntityInfo); 
        }

        #region Properties

        [AB_Key(ap_IsAutoGenerated=true)] 
        [AB_DoNotCopy]
        [Display(Name = "ORDERINTERNALID", ResourceType = typeof(DescriptionResource))]
        [AB_Length(8)]
        [AB_AutoIncrement]
        [DataMember]
        public int? OrderInternalID //Map Field: YD1OIID
        {
            get => am_GetPropertyValue(OrderInternalIDProperty);
            set => am_SetPropertyValue(OrderInternalIDProperty, value);
        }
        public static AB_PropertyMetadata<int?> OrderInternalIDProperty = am_CreatePropertyMetaData<int?>(nameof(OrderInternalID), DescriptionResource.ORDERINTERNALID, null); 

        [AB_ReceivedBroadcastDataMember("CustomerInternalID")]
        [Display(Name = "CUSTOMERINTERNALID", ResourceType = typeof(DescriptionResource))]
        [AB_RequiredField]
        [AB_Length(8)]
        [DataMember]
        public int? CustomerInternalID //Map Field: YD1O1CID
        {
            get => am_GetPropertyValue(CustomerInternalIDProperty);
            set => am_SetPropertyValue(CustomerInternalIDProperty, value);
        }
        public static AB_PropertyMetadata<int?> CustomerInternalIDProperty = am_CreatePropertyMetaData<int?>(nameof(CustomerInternalID), DescriptionResource.CUSTOMERINTERNALID, null); 

        [Display(Name = "ORDERDATE", ResourceType = typeof(DescriptionResource))]
        [AB_ApplyDateFormat]
        [AB_DoNotCopy]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:d}", ApplyFormatInEditMode=true)]
        [DataMember]
        public DateTime? OrderDate //Map Field: YD1ODT
        {
            get => am_GetPropertyValue(OrderDateProperty);
            set => am_SetPropertyValue(OrderDateProperty, value);
        }
        public static AB_PropertyMetadata<DateTime?> OrderDateProperty = am_CreatePropertyMetaData<DateTime?>(nameof(OrderDate), DescriptionResource.ORDERDATE, null); 

        [Display(Name = "ORDERTIME", ResourceType = typeof(DescriptionResource))]
		[AB_DoNotCopy]
		[DataMember]
        public TimeSpan? OrderTime //Map Field: YD1OTM
        {
            get => am_GetPropertyValue(OrderTimeProperty);
            set => am_SetPropertyValue(OrderTimeProperty, value);
        }
        public static AB_PropertyMetadata<TimeSpan?> OrderTimeProperty = am_CreatePropertyMetaData<TimeSpan?>(nameof(OrderTime), DescriptionResource.ORDERTIME, null); 

        [Display(Name = "PURCHASEORDERNUMBERID", ResourceType = typeof(DescriptionResource))]
        [AB_Length(50)]
        [DataMember]
        [AB_RequiredField]
        public string PurchaseOrderNumberID //Map Field: YD1OPONO
        {
            get => am_GetPropertyValue(PurchaseOrderNumberIDProperty);
            set => am_SetPropertyValue(PurchaseOrderNumberIDProperty, value);
        }
        public static AB_PropertyMetadata<string> PurchaseOrderNumberIDProperty = am_CreatePropertyMetaData<string>(nameof(PurchaseOrderNumberID), DescriptionResource.PURCHASEORDERNUMBERID, null); 

        [Display(Name = "WAREHOUSEINTERNALID", ResourceType = typeof(DescriptionResource))]
        [AB_Length(8)]
        [DataMember]
        public int? WarehouseInternalID //Map Field: YD1O1WID
        {
            get => am_GetPropertyValue(WarehouseInternalIDProperty);
            set => am_SetPropertyValue(WarehouseInternalIDProperty, value);
        }
        public static AB_PropertyMetadata<int?> WarehouseInternalIDProperty = am_CreatePropertyMetaData<int?>(nameof(WarehouseInternalID), DescriptionResource.WAREHOUSEINTERNALID, null); 

        [Display(Name = "WAREHOUSENAME", ResourceType = typeof(DescriptionResource))]
        [AB_Length(50)]
        [DataMember]
        [AB_RequiredField]
        public string WarehouseName //Map Field: YD1O1WNM
        {
            get => am_GetPropertyValue(WarehouseNameProperty);
            set => am_SetPropertyValue(WarehouseNameProperty, value);
        }
        public static AB_PropertyMetadata<string> WarehouseNameProperty = am_CreatePropertyMetaData<string>(nameof(WarehouseName), DescriptionResource.WAREHOUSENAME, null); 

        [Display(Name = "DELIVERYMEMO", ResourceType = typeof(DescriptionResource))]
        [AB_Length(100)]
        [DataMember]
        public string DeliveryMemo //Map Field: YD1ODLM1
        {
            get => am_GetPropertyValue(DeliveryMemoProperty);
            set => am_SetPropertyValue(DeliveryMemoProperty, value);
        }
        public static AB_PropertyMetadata<string> DeliveryMemoProperty = am_CreatePropertyMetaData<string>(nameof(DeliveryMemo), DescriptionResource.DELIVERYMEMO, null); 

        [AB_ReceivedBroadcastDataMember("ShippingAddressInternalID")]
        [Display(Name = "SHIPPINGADDRESSINTERNALID", ResourceType = typeof(DescriptionResource))]
        [AB_RequiredField]
        [AB_Length(8)]
        [DataMember]
        public int? ShippingAddressInternalID //Map Field: YD1O1SID
        {
            get => am_GetPropertyValue(ShippingAddressInternalIDProperty);
            set => am_SetPropertyValue(ShippingAddressInternalIDProperty, value);
        }
        public static AB_PropertyMetadata<int?> ShippingAddressInternalIDProperty = am_CreatePropertyMetaData<int?>(nameof(ShippingAddressInternalID), DescriptionResource.SHIPPINGADDRESSINTERNALID, null); 

        [Display(Name = "ORDERMEMO", ResourceType = typeof(DescriptionResource))]
        [AB_Length(100)]
        [DataMember]
        public string OrderMemo //Map Field: YD1OM1
        {
            get => am_GetPropertyValue(OrderMemoProperty);
            set => am_SetPropertyValue(OrderMemoProperty, value);
        }
        public static AB_PropertyMetadata<string> OrderMemoProperty = am_CreatePropertyMetaData<string>(nameof(OrderMemo), DescriptionResource.ORDERMEMO, null); 

        [Display(Name = "STATUS", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [DataMember]
        public string Status //Map Field: YD1OST
        {
            get => am_GetPropertyValue(StatusProperty);
            set => am_SetPropertyValue(StatusProperty, value);
        }
        public static AB_PropertyMetadata<string> StatusProperty = am_CreatePropertyMetaData<string>(nameof(Status), DescriptionResource.STATUS, null); 

        [Display(Name = "SALESPERSONINTERNALID", ResourceType = typeof(DescriptionResource))]
        [AB_Length(8)]
        [DataMember]
        public int? SalesPersonInternalID //Map Field: YD1O1AID
        {
            get => am_GetPropertyValue(SalesPersonInternalIDProperty);
            set => am_SetPropertyValue(SalesPersonInternalIDProperty, value);
        }
        public static AB_PropertyMetadata<int?> SalesPersonInternalIDProperty = am_CreatePropertyMetaData<int?>(nameof(SalesPersonInternalID), DescriptionResource.SALESPERSONINTERNALID, null); 

        [Display(Name = "SALESPERSONNAME", ResourceType = typeof(DescriptionResource))]
        [AB_Length(50)]
        [DataMember]
        [AB_RequiredField]
        public string SalesPersonName //Map Field: YD1O1ANM
        {
            get => am_GetPropertyValue(SalesPersonNameProperty);
            set => am_SetPropertyValue(SalesPersonNameProperty, value);
        }
        public static AB_PropertyMetadata<string> SalesPersonNameProperty = am_CreatePropertyMetaData<string>(nameof(SalesPersonName), DescriptionResource.SALESPERSONNAME, null); 

        [Display(Name = "PURCHASEPOINTS", ResourceType = typeof(DescriptionResource))]
        [AB_Length(8)]
        [DataMember]
        public int? PurchasePoints //Map Field: YD1CPRPT
        {
            get => am_GetPropertyValue(PurchasePointsProperty);
            set => am_SetPropertyValue(PurchasePointsProperty, value);
        }
        public static AB_PropertyMetadata<int?> PurchasePointsProperty = am_CreatePropertyMetaData<int?>(nameof(PurchasePoints), DescriptionResource.PURCHASEPOINTS, null); 

        [Display(Name = "CREATEDATE", ResourceType = typeof(DescriptionResource))]
        [AB_ApplyDateFormat]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:d}", ApplyFormatInEditMode=true)]
        [AB_CreateDate]
        [DataMember]
        public DateTime? CreateDate //Map Field: YD1OCRDT
        {
            get => am_GetPropertyValue(CreateDateProperty);
            set => am_SetPropertyValue(CreateDateProperty, value);
        }
        public static AB_PropertyMetadata<DateTime?> CreateDateProperty = am_CreatePropertyMetaData<DateTime?>(nameof(CreateDate), DescriptionResource.CREATEDATE, null); 

        [Display(Name = "CREATETIME", ResourceType = typeof(DescriptionResource))]
        [AB_CreateTime]
        [DataMember]
        public TimeSpan? CreateTime //Map Field: YD1OCRTM
        {
            get => am_GetPropertyValue(CreateTimeProperty);
            set => am_SetPropertyValue(CreateTimeProperty, value);
        }
        public static AB_PropertyMetadata<TimeSpan?> CreateTimeProperty = am_CreatePropertyMetaData<TimeSpan?>(nameof(CreateTime), DescriptionResource.CREATETIME, null); 

        [Display(Name = "CREATEUSER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [AB_CreateUser]
        [DataMember]
        public string CreateUser //Map Field: YD1OCRUS
        {
            get => am_GetPropertyValue(CreateUserProperty);
            set => am_SetPropertyValue(CreateUserProperty, value);
        }
        public static AB_PropertyMetadata<string> CreateUserProperty = am_CreatePropertyMetaData<string>(nameof(CreateUser), DescriptionResource.CREATEUSER, null); 

        [Display(Name = "CREATEJOB", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [DataMember]
        public string CreateJob //Map Field: YD1OCRJB
        {
            get => am_GetPropertyValue(CreateJobProperty);
            set => am_SetPropertyValue(CreateJobProperty, value);
        }
        public static AB_PropertyMetadata<string> CreateJobProperty = am_CreatePropertyMetaData<string>(nameof(CreateJob), DescriptionResource.CREATEJOB, null); 

        [Display(Name = "CREATEJOBNUMBER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(6)]
        [DataMember]
        public string CreateJobNumber //Map Field: YD1OCRJN
        {
            get => am_GetPropertyValue(CreateJobNumberProperty);
            set => am_SetPropertyValue(CreateJobNumberProperty, value);
        }
        public static AB_PropertyMetadata<string> CreateJobNumberProperty = am_CreatePropertyMetaData<string>(nameof(CreateJobNumber), DescriptionResource.CREATEJOBNUMBER, null); 

        [Display(Name = "LASTCHANGEDATE", ResourceType = typeof(DescriptionResource))]
        [AB_ApplyDateFormat]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:d}", ApplyFormatInEditMode=true)]
        [AB_LastChangeDate]
        [DataMember]
        public DateTime? LastChangeDate //Map Field: YD1OLCDT
        {
            get => am_GetPropertyValue(LastChangeDateProperty);
            set => am_SetPropertyValue(LastChangeDateProperty, value);
        }
        public static AB_PropertyMetadata<DateTime?> LastChangeDateProperty = am_CreatePropertyMetaData<DateTime?>(nameof(LastChangeDate), DescriptionResource.LASTCHANGEDATE, null); 

        [Display(Name = "LASTCHANGETIME", ResourceType = typeof(DescriptionResource))]
        [AB_LastChangeTime]
        [DataMember]
        public TimeSpan? LastChangeTime //Map Field: YD1OLCTM
        {
            get => am_GetPropertyValue(LastChangeTimeProperty);
            set => am_SetPropertyValue(LastChangeTimeProperty, value);
        }
        public static AB_PropertyMetadata<TimeSpan?> LastChangeTimeProperty = am_CreatePropertyMetaData<TimeSpan?>(nameof(LastChangeTime), DescriptionResource.LASTCHANGETIME, null); 

        [Display(Name = "LASTCHANGEUSER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [AB_LastChangeUser]
        [DataMember]
        public string LastChangeUser //Map Field: YD1OLCUS
        {
            get => am_GetPropertyValue(LastChangeUserProperty);
            set => am_SetPropertyValue(LastChangeUserProperty, value);
        }
        public static AB_PropertyMetadata<string> LastChangeUserProperty = am_CreatePropertyMetaData<string>(nameof(LastChangeUser), DescriptionResource.LASTCHANGEUSER, null); 

        [Display(Name = "LASTCHANGEJOB", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [DataMember]
        public string LastChangeJob //Map Field: YD1OLCJB
        {
            get => am_GetPropertyValue(LastChangeJobProperty);
            set => am_SetPropertyValue(LastChangeJobProperty, value);
        }
        public static AB_PropertyMetadata<string> LastChangeJobProperty = am_CreatePropertyMetaData<string>(nameof(LastChangeJob), DescriptionResource.LASTCHANGEJOB, null); 

        [Display(Name = "LASTCHANGEJOBNUMBER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(6)]
        [DataMember]
        public string LastChangeJobNumber //Map Field: YD1OLCJN
        {
            get => am_GetPropertyValue(LastChangeJobNumberProperty);
            set => am_SetPropertyValue(LastChangeJobNumberProperty, value);
        }
        public static AB_PropertyMetadata<string> LastChangeJobNumberProperty = am_CreatePropertyMetaData<string>(nameof(LastChangeJobNumber), DescriptionResource.LASTCHANGEJOBNUMBER, null); 

        [AB_DropdownDisplay("~/Views/Customer/_CustomerDropdown.cshtml", new string[] { "Source: CustomerInternalID ,Target: CustomerInternalID" }, ap_ShowNewButton = true, ap_ShowOpenButton = true, ap_ShowSearchButton = true)]
        [Display(Name = "CUSTOMERNAME", ResourceType = typeof(DescriptionResource))]
        [AB_Length(50)]
        [AB_BroadcastMember(AB_DataShouldBePassed.OnPreload)]
        [DataMember]
        public string CustomerName //Map Field: YD1C.YD1CNM
        {
            get => am_GetPropertyValue(CustomerNameProperty);
            set => am_SetPropertyValue(CustomerNameProperty, value);
        }
        public static AB_PropertyMetadata<string> CustomerNameProperty = am_CreatePropertyMetaData<string>(nameof(CustomerName), DescriptionResource.CUSTOMERNAME, null); 

        [AB_DropdownDisplay("~/Views/ShippingAddress/_ShippingAddressDropdown.cshtml", new string[] { "Source: ShippingAddressInternalID ,Target: ShippingAddressInternalID" }, ap_ShowNewButton = true, ap_ShowOpenButton = true, ap_ShowSearchButton = true)]
        [Display(Name = "SHIPPINGADDRESSNAME", ResourceType = typeof(DescriptionResource))]
        [AB_Length(50)]
        [AB_BroadcastMember(AB_DataShouldBePassed.OnPreload)]
        [DataMember]
        public string ShippingAddressName //Map Field: YD1S.YD1SNM
        {
            get => am_GetPropertyValue(ShippingAddressNameProperty);
            set => am_SetPropertyValue(ShippingAddressNameProperty, value);
        }
        public static AB_PropertyMetadata<string> ShippingAddressNameProperty = am_CreatePropertyMetaData<string>(nameof(ShippingAddressName), DescriptionResource.SHIPPINGADDRESSNAME, null); 


        #endregion //Properties

        #region Property Overrides

        // Title
        public override string ap_Title
        {
            get
            {
                if (string.IsNullOrEmpty(base.ap_Title))
                {
                    StringBuilder title = new StringBuilder();
                    switch (ap_TitleMode)
                    {
                        case AB_TitleMode.New:
                        case AB_TitleMode.NewFor:
                        case AB_TitleMode.Copy:
                            title.AppendFormat("{0}", MessageResource.TITLENEW);
                            break;
                        case AB_TitleMode.Display:
                            title.AppendFormat("{0}", MessageResource.TITLEDISPLAY);
                            break;
                        case AB_TitleMode.Open:
                            title.AppendFormat("{0}", MessageResource.TITLEOPEN);
                            break;
                        case AB_TitleMode.Subbrowser:
                            title.AppendFormat("{0}", MessageResource.TITLESUBBROWSER);
                            break;
                        case AB_TitleMode.Default:
                            title.AppendFormat("{0} ", MessageResource.TITLEOPEN);
                            break;
                    }
 
                    if (OrderInternalID.HasValue)
                    {
                        title.AppendFormat(" - {0}", OrderInternalID.Value);
                    }
 
                    if (!string.IsNullOrWhiteSpace(CustomerName))
                    {
                        title.AppendFormat(" - {0}", CustomerName);
                    }

                    if (OrderDate.HasValue && OrderTime.HasValue)
                    {
                        title.AppendFormat(" - {0} {1}", OrderDate.Value.ToString("MM-dd-yyy"), OrderTime);
                    }

                    return title.ToString();
                }
                return base.ap_Title;
            }
            set
            {
                base.ap_Title = value;
            }
        }

        // Message Field
        public override string ap_MessageField
        {
            get
            {
                if (string.IsNullOrEmpty(base.ap_MessageField))
                {
                    return "\"" + ap_Title + "\"";
                }

                return base.ap_MessageField;
            }
            set
            {
                base.ap_MessageField = value;
            }
        }

        // Unique Name
        public override string ap_UniqueName
        {
            get
            {
                if (string.IsNullOrEmpty(base.ap_UniqueName))
                {
                    return "Order - ";
                }

                return base.ap_UniqueName;
            }
            set
            {
                base.ap_UniqueName = value;
            }
        }

        #endregion //Property Overrides
        /// <summary>
        /// Static constructor
        /// </summary>
        static OrderEntity()
        {
            RG_DoStaticInit();
        }


    }
}