//===============================================================================================
// <A4DN_GeneratedInformation>
// This code was generated using the Accelerator for .Net Code Generator.
// <A4DN_Template Name="BOS.Module.Entity.t4" Version="8.0.0.93" GeneratedDate="5/29/2024" />
// </A4DN_GeneratedInformation>
//===============================================================================================
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using A4DN.Core.BOS.Base;
using BOS.OrderManagement.Shared.Properties;
#if !SILVERLIGHT
using A4DN.Core.BOS.ValidationAttributes;  // Custom validation attributes
#endif

namespace BOS.OrderItemDataEntity
{
    /// <summary>
    /// Represents data. Contains metadata that facilitates validation and advanced databinding.
    /// </summary>
    [DataContract]
    public class OrderItemEntity : AB_BusinessObjectEntityBase
    {
        /// <summary>
        /// Entity information is defined in the lower level entity to maximize performance by making it static
        /// </summary>
        private static AB_EntityInfo _EntityInfo;
        /// <summary>
        /// Gets metadata information about the entity
        /// </summary>
        public override AB_EntityInfo ap_EntityInfo
        {
            get => _EntityInfo;
        }

        /// <summary>
        /// Initializes static members
        /// </summary>
        static private void RG_DoStaticInit()
        {
            // Set Message and Description Primary and Secondary Resources. 
            AB_BusinessObjectEntityBase.am_GetPropertyInfo(typeof(OrderItemEntity), typeof(BOS.OrderManagement.Properties.MessageResource), typeof(MessageResource), typeof(BOS.OrderManagement.Properties.DescriptionResource), typeof(DescriptionResource), out _EntityInfo); 
        }

        #region Properties

        [AB_Key(ap_IsAutoGenerated=true)] 
        [AB_DoNotCopy]
        [Display(Name = "ORDERITEMINTERNALID", ResourceType = typeof(DescriptionResource))]
        [AB_Length(12)]
        [DataMember]
        public int? OrderItemInternalID //Map Field: YD1IIID
        {
            get => am_GetPropertyValue(OrderItemInternalIDProperty);
            set => am_SetPropertyValue(OrderItemInternalIDProperty, value);
        }
        public static AB_PropertyMetadata<int?> OrderItemInternalIDProperty = am_CreatePropertyMetaData<int?>(nameof(OrderItemInternalID), DescriptionResource.ORDERITEMINTERNALID, null); 

        [AB_ReceivedBroadcastDataMember("OrderInternalID")]
        [AB_DropdownDisplay("~/Views/Order/_OrderDropdown.cshtml", new string[] { "Source: OrderInternalID ,Target: OrderInternalID" }, ap_ShowNewButton = true, ap_ShowOpenButton = true, ap_ShowSearchButton = true)]
        [Display(Name = "ORDERINTERNALID", ResourceType = typeof(DescriptionResource))]
        [AB_Length(8)]
        [DataMember]
        public int? OrderInternalID //Map Field: YD1I1OID
        {
            get => am_GetPropertyValue(OrderInternalIDProperty);
            set => am_SetPropertyValue(OrderInternalIDProperty, value);
        }
        public static AB_PropertyMetadata<int?> OrderInternalIDProperty = am_CreatePropertyMetaData<int?>(nameof(OrderInternalID), DescriptionResource.ORDERINTERNALID, null); 

        [AB_ReceivedBroadcastDataMember("ProductInternalID")]
        [Display(Name = "PRODUCTINTERNALID", ResourceType = typeof(DescriptionResource))]
        [AB_Length(8)]
        [DataMember]
        public int? ProductInternalID //Map Field: YD1I1PID
        {
            get => am_GetPropertyValue(ProductInternalIDProperty);
            set => am_SetPropertyValue(ProductInternalIDProperty, value);
        }
        public static AB_PropertyMetadata<int?> ProductInternalIDProperty = am_CreatePropertyMetaData<int?>(nameof(ProductInternalID), DescriptionResource.PRODUCTINTERNALID, null); 

        [Display(Name = "QUANTITY", ResourceType = typeof(DescriptionResource))]
        [AB_Length(4)]
        [DataMember]
        public int? Quantity //Map Field: YD1IQT
        {
            get => am_GetPropertyValue(QuantityProperty);
            set => am_SetPropertyValue(QuantityProperty, value);
        }
        public static AB_PropertyMetadata<int?> QuantityProperty = am_CreatePropertyMetaData<int?>(nameof(Quantity), DescriptionResource.QUANTITY, null); 

        [Display(Name = "UNITPRICE", ResourceType = typeof(DescriptionResource))]
        [AB_Length(8)]
        [DataType(DataType.Currency)]
        [AB_ApplyStringFormat("C")]
        [DataMember]
        public decimal? UnitPrice //Map Field: YD1IPRUN
        {
            get => am_GetPropertyValue(UnitPriceProperty);
            set => am_SetPropertyValue(UnitPriceProperty, value);
        }
        public static AB_PropertyMetadata<decimal?> UnitPriceProperty = am_CreatePropertyMetaData<decimal?>(nameof(UnitPrice), DescriptionResource.UNITPRICE, null); 

        [Display(Name = "DISCOUNTPERCENT", ResourceType = typeof(DescriptionResource))]
        [AB_Length(4)]
        [AB_ApplyStringFormat("P")]
        [DataMember]
        public decimal? DiscountPercent //Map Field: YD1IDSPC
        {
            get => am_GetPropertyValue(DiscountPercentProperty);
            set => am_SetPropertyValue(DiscountPercentProperty, value);
        }
        public static AB_PropertyMetadata<decimal?> DiscountPercentProperty = am_CreatePropertyMetaData<decimal?>(nameof(DiscountPercent), DescriptionResource.DISCOUNTPERCENT, null); 

        [Display(Name = "MEMO", ResourceType = typeof(DescriptionResource))]
        [AB_Length(100)]
        [DataMember]
        public string Memo //Map Field: YD1IM1
        {
            get => am_GetPropertyValue(MemoProperty);
            set => am_SetPropertyValue(MemoProperty, value);
        }
        public static AB_PropertyMetadata<string> MemoProperty = am_CreatePropertyMetaData<string>(nameof(Memo), DescriptionResource.MEMO, null); 

        [Display(Name = "CREATEDATE", ResourceType = typeof(DescriptionResource))]
        [AB_ApplyDateFormat]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:d}", ApplyFormatInEditMode=true)]
        [AB_CreateDate]
        [DataMember]
        public DateTime? CreateDate //Map Field: YD1ICRDT
        {
            get => am_GetPropertyValue(CreateDateProperty);
            set => am_SetPropertyValue(CreateDateProperty, value);
        }
        public static AB_PropertyMetadata<DateTime?> CreateDateProperty = am_CreatePropertyMetaData<DateTime?>(nameof(CreateDate), DescriptionResource.CREATEDATE, null); 

        [Display(Name = "CREATETIME", ResourceType = typeof(DescriptionResource))]
        [AB_CreateTime]
        [DataMember]
        public TimeSpan? CreateTime //Map Field: YD1ICRTM
        {
            get => am_GetPropertyValue(CreateTimeProperty);
            set => am_SetPropertyValue(CreateTimeProperty, value);
        }
        public static AB_PropertyMetadata<TimeSpan?> CreateTimeProperty = am_CreatePropertyMetaData<TimeSpan?>(nameof(CreateTime), DescriptionResource.CREATETIME, null); 

        [Display(Name = "CREATEUSER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [AB_CreateUser]
        [DataMember]
        public string CreateUser //Map Field: YD1ICRUS
        {
            get => am_GetPropertyValue(CreateUserProperty);
            set => am_SetPropertyValue(CreateUserProperty, value);
        }
        public static AB_PropertyMetadata<string> CreateUserProperty = am_CreatePropertyMetaData<string>(nameof(CreateUser), DescriptionResource.CREATEUSER, null); 

        [Display(Name = "CREATEJOB", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [DataMember]
        public string CreateJob //Map Field: YD1ICRJB
        {
            get => am_GetPropertyValue(CreateJobProperty);
            set => am_SetPropertyValue(CreateJobProperty, value);
        }
        public static AB_PropertyMetadata<string> CreateJobProperty = am_CreatePropertyMetaData<string>(nameof(CreateJob), DescriptionResource.CREATEJOB, null); 

        [Display(Name = "CREATEJOBNUMBER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(6)]
        [DataMember]
        public string CreateJobNumber //Map Field: YD1ICRJN
        {
            get => am_GetPropertyValue(CreateJobNumberProperty);
            set => am_SetPropertyValue(CreateJobNumberProperty, value);
        }
        public static AB_PropertyMetadata<string> CreateJobNumberProperty = am_CreatePropertyMetaData<string>(nameof(CreateJobNumber), DescriptionResource.CREATEJOBNUMBER, null); 

        [Display(Name = "LASTCHANGEDATE", ResourceType = typeof(DescriptionResource))]
        [AB_ApplyDateFormat]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:d}", ApplyFormatInEditMode=true)]
        [AB_LastChangeDate]
        [DataMember]
        public DateTime? LastChangeDate //Map Field: YD1ILCDT
        {
            get => am_GetPropertyValue(LastChangeDateProperty);
            set => am_SetPropertyValue(LastChangeDateProperty, value);
        }
        public static AB_PropertyMetadata<DateTime?> LastChangeDateProperty = am_CreatePropertyMetaData<DateTime?>(nameof(LastChangeDate), DescriptionResource.LASTCHANGEDATE, null); 

        [Display(Name = "LASTCHANGETIME", ResourceType = typeof(DescriptionResource))]
        [AB_LastChangeTime]
        [DataMember]
        public TimeSpan? LastChangeTime //Map Field: YD1ILCTM
        {
            get => am_GetPropertyValue(LastChangeTimeProperty);
            set => am_SetPropertyValue(LastChangeTimeProperty, value);
        }
        public static AB_PropertyMetadata<TimeSpan?> LastChangeTimeProperty = am_CreatePropertyMetaData<TimeSpan?>(nameof(LastChangeTime), DescriptionResource.LASTCHANGETIME, null); 

        [Display(Name = "LASTCHANGEUSER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [AB_LastChangeUser]
        [DataMember]
        public string LastChangeUser //Map Field: YD1ILCUS
        {
            get => am_GetPropertyValue(LastChangeUserProperty);
            set => am_SetPropertyValue(LastChangeUserProperty, value);
        }
        public static AB_PropertyMetadata<string> LastChangeUserProperty = am_CreatePropertyMetaData<string>(nameof(LastChangeUser), DescriptionResource.LASTCHANGEUSER, null); 

        [Display(Name = "LASTCHANGEJOB", ResourceType = typeof(DescriptionResource))]
        [AB_Length(10)]
        [DataMember]
        public string LastChangeJob //Map Field: YD1ILCJB
        {
            get => am_GetPropertyValue(LastChangeJobProperty);
            set => am_SetPropertyValue(LastChangeJobProperty, value);
        }
        public static AB_PropertyMetadata<string> LastChangeJobProperty = am_CreatePropertyMetaData<string>(nameof(LastChangeJob), DescriptionResource.LASTCHANGEJOB, null); 

        [Display(Name = "LASTCHANGEJOBNUMBER", ResourceType = typeof(DescriptionResource))]
        [AB_Length(6)]
        [DataMember]
        public string LastChangeJobNumber //Map Field: YD1ILCJN
        {
            get => am_GetPropertyValue(LastChangeJobNumberProperty);
            set => am_SetPropertyValue(LastChangeJobNumberProperty, value);
        }
        public static AB_PropertyMetadata<string> LastChangeJobNumberProperty = am_CreatePropertyMetaData<string>(nameof(LastChangeJobNumber), DescriptionResource.LASTCHANGEJOBNUMBER, null); 

        [AB_DropdownDisplay("~/Views/Product/_ProductDropdown.cshtml", new string[] { "Source: ProductInternalID ,Target: ProductInternalID" }, ap_ShowNewButton = true, ap_ShowOpenButton = true, ap_ShowSearchButton = true)]
        [Display(Name = "PRODUCTNAME", ResourceType = typeof(DescriptionResource))]
        [AB_Length(50)]
        [AB_BroadcastMember(AB_DataShouldBePassed.OnPreload)]
        [DataMember]
        public string ProductName //Map Field: YD1P.YD1PNM
        {
            get => am_GetPropertyValue(ProductNameProperty);
            set => am_SetPropertyValue(ProductNameProperty, value);
        }
        public static AB_PropertyMetadata<string> ProductNameProperty = am_CreatePropertyMetaData<string>(nameof(ProductName), DescriptionResource.PRODUCTNAME, null);

        [Display(Name = "PRODUCTCODE", ResourceType = typeof(DescriptionResource))]
        [AB_Length(25)]
        [DataMember]
        public string ProductCode //Map Field: YD1P.YD1PCD
        {
            get { return am_GetPropertyValue(ProductCodeProperty); }
            set { am_SetPropertyValue(ProductCodeProperty, value); }
        }
        public static AB_PropertyMetadata<string> ProductCodeProperty = am_CreatePropertyMetaData<string>("ProductCode", DescriptionResource.PRODUCTCODE, null);

        #endregion //Properties

        #region Property Overrides

        // Title
        public override string ap_Title
        {
            get
            {
                if (string.IsNullOrEmpty(base.ap_Title))
                {
                    StringBuilder title = new StringBuilder();
                    switch (ap_TitleMode)
                    {
                        case AB_TitleMode.New:
                        case AB_TitleMode.NewFor:
                        case AB_TitleMode.Copy:
                            title.AppendFormat("{0}", MessageResource.TITLENEW);
                            break;
                        case AB_TitleMode.Display:
                            title.AppendFormat("{0}", MessageResource.TITLEDISPLAY);
                            break;
                        case AB_TitleMode.Open:
                            title.AppendFormat("{0}", MessageResource.TITLEOPEN);
                            break;
                        case AB_TitleMode.Subbrowser:
                            title.AppendFormat("{0}", MessageResource.TITLESUBBROWSER);
                            break;
                        case AB_TitleMode.Default:
                            title.AppendFormat("{0} ", MessageResource.TITLEOPEN);
                            break;
                    }
 
                    if (OrderItemInternalID.HasValue)
                    {
                        title.AppendFormat(" - {0}", OrderItemInternalID.Value);
                    }
  
                    return title.ToString();
                }
                return base.ap_Title;
            }
            set
            {
                base.ap_Title = value;
            }
        }

        // Message Field
        public override string ap_MessageField
        {
            get
            {
                if (string.IsNullOrEmpty(base.ap_MessageField))
                {
                    return "\"" + ap_Title + "\"";
                }

                return base.ap_MessageField;
            }
            set
            {
                base.ap_MessageField = value;
            }
        }

        // Unique Name
        public override string ap_UniqueName
        {
            get
            {
                if (string.IsNullOrEmpty(base.ap_UniqueName))
                {
                    return "Order Item - ";
                }

                return base.ap_UniqueName;
            }
            set
            {
                base.ap_UniqueName = value;
            }
        }

        #endregion //Property Overrides
        /// <summary>
        /// Static constructor
        /// </summary>
        static OrderItemEntity()
        {
            RG_DoStaticInit();
        }


    }
}