/*******************************************************************************

CONFIDENTIAL AND PROPRIETARY INFORMATION

The receipt or possession of this document does not convey any rights to
reproduce, disclose its contents or manufacture, use or sell anything it may
describe.  Reproduction, disclosure, or use without the specific written
authorization of Surround Technologies, LLC is strictly forbidden.

Copyright ....: (C) Surround Technologies, LLC 1998 - 2021
                9197 Estero River Circle
                Estero, FL 33928
                973-743-1277
                http://www.surroundtech.com/
                 
================================================================================

Source File...: QDBSRC
Source Member.: IBM i DDL EasyBuyCyclesModern Schema.sql
Created by ...: Lee Paul
Created on ...: September 14, 2022
Object Type ..: Schema Definition
Description ..: Customer

BUILD COMMAND.:
RUNSQLSTM SRCFILE(EASYBUYDM3/QDBSRC) SRCMBR("Customer")
    COMMIT(*NONE) ERRLVL(20)

================================================================================
                             Amendment Details
                             -----------------
Date       Programmer      Description
---------- --------------- -----------------------------------------------------


*******************************************************************************/

CREATE SCHEMA "EasyBuyCycles" FOR EASYBUYDM3;
-- Set the Library Description on the IBM i
CALL QSYS2.QCMDEXC ('CHGLIB LIB(EASYBUYDM3) TYPE(*PROD) TEXT(''EasyBuy Cycles'')');


CREATE SCHEMA "EasyBuyCyclesDev" FOR EASYBUYDV3;
-- Set the Library Description on the IBM i
CALL QSYS2.QCMDEXC ('CHGLIB LIB(EASYBUYDV3) TYPE(*PROD) TEXT(''EasyBuy Cycles Developmnet'')');

SET SCHEMA "EasyBuyCycles";
-- SET SCHEMA "EasyBuyCyclesDev";

/*******************************************************************************

CONFIDENTIAL AND PROPRIETARY INFORMATION

The receipt or possession of this document does not convey any rights to
reproduce, disclose its contents or manufacture, use or sell anything it may
describe.  Reproduction, disclosure, or use without the specific written
authorization of Surround Technologies, LLC is strictly forbidden.

Copyright ....: (C) Surround Technologies, LLC 1998 - 2021
                9197 Estero River Circle
                Estero, FL 33928
                973-743-1277
                http://www.surroundtech.com/
                 
================================================================================

Source File...: QDBSRC
Source Member.: IBM i DDL EasyBuyCyclesModern Customer.sql
Created by ...: Lee Paul
Created on ...: September 14, 2022
Object Type ..: Table Definition
Description ..: Customer

BUILD COMMAND.:
RUNSQLSTM SRCFILE(EASYBUYDM3/QDBSRC) SRCMBR("Customer")
    COMMIT(*NONE) ERRLVL(20)

================================================================================
                             Amendment Details
                             -----------------
Date       Programmer      Description
---------- --------------- -----------------------------------------------------


*******************************************************************************
Notes:

To see the next identity value use the following SQL 
SELECT NEXT_IDENTITY_VALUE
    FROM QSYS2.SYSPARTITIONSTAT
    WHERE Table_Schema = 'EasyBuyCycles'
          AND Table_Name = 'Customer'

To see the last Value in the table use the following SQL
SELECT MAX("InternalID")
    FROM "EasyBuyCycles"."Customer";

To set the Customer Table Autoincrementing Identity Value use the follwing SQL
ALTER TABLE "EasyBuyCycles"."Customer"
   ALTER COLUMN "InternalID" RESTART WITH <the number you want>

*******************************************************************************/

-- SET SCHEMA "EasyBuyCycles";
-- SET SCHEMA "EasyBuyCyclesDev";

-- ALTER TABLE "Customer"
--    DROP CONSTRAINT "PK_Customer",
--    DROP CONSTRAINT "FK_Customer_{ReferenceTable}";

DROP INDEX IF EXISTS "UQ_Customer_Name";
DROP INDEX IF EXISTS "IX_Customer_ParentInternalID_Name";
DROP INDEX IF EXISTS "IX_Customer_LegalName_Name";
DROP INDEX IF EXISTS "IX_Customer_ContactLastName_ContactFirstName_Name";
DROP INDEX IF EXISTS "IX_Customer_BillingPostalCode_Name";
DROP INDEX IF EXISTS "IX_Customer_Telephone_Name";
DROP INDEX IF EXISTS "IX_Customer_PurchasePoints_Name";

-- DROP VIEW IF EXISTS "VW_{ViewName}";

-- DROP ALIAS IF EXISTS "{AliasName}";

-- DROP TABLE IF EXISTS "Customer";
-- Warnng: Dropping a table will lose the data within it.

CREATE OR REPLACE TABLE "Customer"
    (
     "InternalID"           FOR "YD1CIID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(MINVALUE 5000 INCREMENT BY 1 CYCLE),
     "ParentInternalID"     FOR "YD1CPTID" INT,
     "ParentRelationship"   FOR "YD1CPTRL" NVARCHAR(20),
     "Name"                 FOR "YD1CNM" NVARCHAR(50) NOT NULL,
     "LegalName"            FOR "YD1CNMLG" NVARCHAR(50),
     "ContactLastName"      FOR "YD1CCNLN" NVARCHAR(50) NOT NULL,
     "ContactFirstName"     FOR "YD1CCNFN" NVARCHAR(50) NOT NULL,
     "ContactMiddleName"    FOR "YD1CCNMN" NVARCHAR(50),
     "ContactNickName"      FOR "YD1CCNNN" NVARCHAR(50),
     "BillingAddress1"      FOR "YD1CBLA1" NVARCHAR(30) NOT NULL,
     "BillingAddress2"      FOR "YD1CBLA2" NVARCHAR(30) NOT NULL,
     "BillingAddress3"      FOR "YD1CBLA3" NVARCHAR(30) NOT NULL,
     "BillingPostalCode"    FOR "YD1CBLPC" NVARCHAR(10) NOT NULL,
     "BillingCountry"       FOR "YD1CBLCY" NVARCHAR(50) NOT NULL,
     "Telephone"            FOR "YD1CTL" NVARCHAR(20),
     "Email"                FOR "YD1CEM" NVARCHAR(50),
     "Memo"                 FOR "YD1CM1" NVARCHAR(100),
     "PurchasePoints"       FOR "YD1CPRPT" NUMERIC(8,0) DEFAULT 0,
    
     -- Audit Stamps
     "CreatedAt"            FOR "YD1CCRDT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "CreatedBy"            FOR "YD1CCRUS" VARCHAR(128) NOT NULL,
     "CreatedWith"          FOR "YD1CCRAP" VARCHAR(255) NOT NULL,
     "LastModifiedAt"       FOR "YD1CLCDT" TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL,
     "LastModifiedBy"       FOR "YD1CLCUS" VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER),
     "LastModifiedWith"     FOR "YD1CLCAP" VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME),

      -- Primary Key Constraint
      CONSTRAINT "PK_Customer"
         PRIMARY KEY ("InternalID"),

      -- Referential Foreign Key Constraints
      CONSTRAINT "FK_Customer_ParentCustomer"
         FOREIGN KEY ("ParentInternalID")
         REFERENCES "Customer"("InternalID")
         ON DELETE RESTRICT ON UPDATE RESTRICT
   )
RCDFMT YD1CPR
ON REPLACE PRESERVE ROWS;

-- Table Description
LABEL ON TABLE "Customer"
   IS 'Customer';

-- Column Labels - Description (50 Chars)
LABEL ON COLUMN "Customer" (
     "InternalID"           TEXT IS 'Internal ID',
     "ParentInternalID"     TEXT IS 'Parent Internal ID',
     "ParentRelationship"   TEXT IS 'Parent Relationship',
     "Name"                 TEXT IS 'Name',
     "LegalName"            TEXT IS 'Legal Name',
     "ContactLastName"      TEXT IS 'Contact Last Name',
     "ContactFirstName"     TEXT IS 'Contact First Name',
     "ContactMiddleName"    TEXT IS 'Contact Middle Name',
     "ContactNickName"      TEXT IS 'Contact Nick Name',
     "BillingAddress1"      TEXT IS 'Billing Address 1',
     "BillingAddress2"      TEXT IS 'Billing Address 2',
     "BillingAddress3"      TEXT IS 'Billing Address 3',
     "BillingPostalCode"    TEXT IS 'Billing Postal Code',
     "BillingCountry"       TEXT IS 'Billing Country',
     "Telephone"            TEXT IS 'Telephone',
     "Email"                TEXT IS 'Email',
     "Memo"                 TEXT IS 'Memo',
     "PurchasePoints"       TEXT IS 'Purchase Points',

     "CreatedAt"            TEXT IS 'Created At',
     "CreatedBy"            TEXT IS 'Created By',
     "CreatedWith"          TEXT IS 'Created With',
     "LastModifiedAt"       TEXT IS 'Modified At',
     "LastModifiedBy"       TEXT IS 'Modified By',
     "LastModifiedWith"     TEXT IS 'Modified With'
     );

-- Column Labels - Column Headings (3 x 20 Chars)
LABEL ON COLUMN "Customer" (
--                             |1-------------------2-------------------3-------------------|
     "InternalID"           IS 'Internal ID',
     "ParentInternalID"     IS 'Parent              Internal ID',
     "ParentRelationship"   IS 'Parent              Relationship',
     "Name"                 IS 'Name',
     "LegalName"            IS 'Legal Name',
     "ContactLastName"      IS 'Contact             Last Name',
     "ContactFirstName"     IS 'Contact             First Name',
     "ContactMiddleName"    IS 'Contact             Middle Name',
     "ContactNickName"      IS 'Contact             Nick Name',
     "BillingAddress1"      IS 'Billing             Address 1',
     "BillingAddress2"      IS 'Billing             Address 2',
     "BillingAddress3"      IS 'Billing             Address 3',
     "BillingPostalCode"    IS 'Billing             Postal Code',
     "BillingCountry"       IS 'Billing             Country',
     "Telephone"            IS 'Telephone',
     "Email"                IS 'Email',
     "Memo"                 IS 'Memo',
     "PurchasePoints"       IS 'Purchase Points',

     "CreatedAt"            IS 'Created At',
     "CreatedBy"            IS 'Created By',
     "CreatedWith"          IS 'Created With',
     "LastModifiedAt"       IS 'Modified At',
     "LastModifiedBy"       IS 'Modified By',
     "LastModifiedWith"     IS 'Modified With'
     );

-- Grant Table Access
GRANT DELETE, INSERT, SELECT, UPDATE
ON "Customer" TO PUBLIC WITH GRANT OPTION ;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE
ON "Customer" TO QPGMR WITH GRANT OPTION ;

-- Unique Indexes
CREATE UNIQUE INDEX "UQ_Customer_Name"
   FOR SYSTEM NAME "YD1CIXU1" ON "Customer" (
   "Name"
   );
LABEL ON INDEX "UQ_Customer_Name"
   IS 'Name';

-- Indexes
CREATE INDEX "IX_Customer_ParentInternalID_Name"
   FOR SYSTEM NAME "YD1CIX02"
   ON "Customer" (
   "ParentInternalID", "Name"
   );
LABEL ON INDEX "IX_Customer_ParentInternalID_Name"
   IS 'Parrent Internal ID';

CREATE INDEX "IX_Customer_LegalName_Name"
   FOR SYSTEM NAME "YD1CIX03"
   ON "Customer" (
   "LegalName", "Name"
   );
LABEL ON INDEX "IX_Customer_LegalName_Name"
   IS 'Legal Name';

CREATE INDEX "IX_Customer_ContactLastName_ContactFirstName_Name"
   FOR SYSTEM NAME "YD1CIX04"
   ON "Customer" (
   "ContactLastName", "ContactFirstName", "Name"
   );
LABEL ON INDEX "IX_Customer_ContactLastName_ContactFirstName_Name"
   IS 'Contact Last and First Names';

CREATE INDEX "IX_Customer_BillingPostalCode_Name"
   FOR SYSTEM NAME "YD1CIX05"
   ON "Customer" (
   "BillingPostalCode", "Name"
   );
LABEL ON INDEX "IX_Customer_BillingPostalCode_Name"
   IS 'Billing Postal Code';

CREATE INDEX "IX_Customer_Telephone_Name"
   FOR SYSTEM NAME "YD1CIX06"
   ON "Customer" (
   "Telephone", "Name"
   );
LABEL ON INDEX "IX_Customer_Telephone_Name"
   IS 'Telephone';

CREATE INDEX "IX_Customer_PurchasePoints_Name"
   FOR SYSTEM NAME "YD1CIX07"
   ON "Customer" (
   "PurchasePoints", "Name"
   );
LABEL ON INDEX "IX_Customer_PurchasePoints_Name"
   IS 'Purchase Points';

-- Views
-- CREATE OR REPLACE VIEW "VW_AccountTable_<Descriptors>"
--     FOR SYSTEM NAME "FACCTV01" AS
--          < View Definition >
-- ;
-- LABEL ON TABLE "VVW_AccountTable_<Descriptors>"
--    IS 'View Description';

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> TEXT IS 'View Column Description'
--      );

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> IS 'View Column Description'
--      );

-- GRANT SELECT
-- ON "VW_AccountTable_<Descriptors>" TO PUBLIC WITH GRANT OPTION ;

-- GRANT ALTER, REFERENCES, SELECT
-- ON "VW_AccountTable_<Descriptors>" TO QPGMR WITH GRANT OPTION ;
   
-- Aliases
-- CREATE OR REPLACE ALIAS {AliasName} FOR "AccountTable";

-- Triggers
CREATE OR REPLACE TRIGGER "Customer_InsertStamps"
   NO CASCADE BEFORE INSERT ON "Customer"
   REFERENCING NEW AS NEW_ROW
   FOR EACH ROW MODE DB2ROW
   SET NEW_ROW."CreatedBy" = COALESCE(NEW_ROW."CreatedBy", SESSION_USER),
       NEW_ROW."CreatedWith" = COALESCE(NEW_ROW."CreatedWith", CURRENT CLIENT_APPLNAME);

-- SET SCHEMA DEFAULT;

/*******************************************************************************

CONFIDENTIAL AND PROPRIETARY INFORMATION

The receipt or possession of this document does not convey any rights to
reproduce, disclose its contents or manufacture, use or sell anything it may
describe.  Reproduction, disclosure, or use without the specific written
authorization of Surround Technologies, LLC is strictly forbidden.

Copyright ....: (C) Surround Technologies, LLC 1998 - 2021
                9197 Estero River Circle
                Estero, FL 33928
                973-743-1277
                http://www.surroundtech.com/
                 
================================================================================

Source File...: QDBSRC
Source Member.: IBM i DDL EasyBuyCyclesModern ShippingAddress.sql
Created by ...: Lee Paul
Created on ...: September 14, 2022
Object Type ..: Table Definition
Description ..: Shipping Address

BUILD COMMAND.:
RUNSQLSTM SRCFILE(EASYBUYDM3/QDBSRC) SRCMBR("ShpAddr")
    COMMIT(*NONE) ERRLVL(20)

================================================================================
                             Amendment Details
                             -----------------
Date       Programmer      Description
---------- --------------- -----------------------------------------------------


*******************************************************************************
Notes:

To see the next identity value use the following SQL 
SELECT NEXT_IDENTITY_VALUE
    FROM QSYS2.SYSPARTITIONSTAT
    WHERE Table_Schema = 'EasyBuyCycles'
          AND Table_Name = 'Customer'

To see the last Value in the table use the following SQL
SELECT MAX("InternalID")
    FROM "EasyBuyCycles"."Customer";

To set the Customer Table Autoincrementing Identity Value use the follwing SQL
ALTER TABLE "EasyBuyCycles"."Customer"
   ALTER COLUMN "InternalID" RESTART WITH <the number you want>

*******************************************************************************/

-- SET SCHEMA "EasyBuyCycles";
-- SET SCHEMA "EasyBuyCyclesDev";

-- ALTER TABLE "ShippingAddress"
--    DROP CONSTRAINT "PK_ShippingAddress",
--    DROP CONSTRAINT "FK_ShippingAddress_{ReferenceTable}";

DROP INDEX IF EXISTS "UQ_ShippingAddress_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_PostalCode_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_ContactLastName_ContactFirstName_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_Telephone_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_Email_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_CustomerInternalID_Name";

-- DROP VIEW IF EXISTS "VW_{ViewName}_{ViewDescriptor}";

-- DROP ALIAS IF EXISTS "{AliasName}";

-- DROP TABLE IF EXISTS "ShippingAddress";
-- Warnng: Dropping a table will lose the data within it.

CREATE OR REPLACE TABLE "ShippingAddress"
    FOR SYSTEM NAME "ShpAddr"  (
     "InternalID"           FOR "YD1SIID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(MINVALUE 5000 INCREMENT BY 1 CYCLE),
     "CustomerInternalID"   FOR "YD1S1CID" INT NOT NULL,
     "Name"                 FOR "YD1SNM" NVARCHAR(50) NOT NULL,
     "ContactLastName"      FOR "YD1SCNLN" NVARCHAR(50) NOT NULL,
     "ContactFirstName"     FOR "YD1SCNFN" NVARCHAR(50) NOT NULL,
     "ContactMiddleName"    FOR "YD1SCNMN" NVARCHAR(50),
     "ContactNickName"      FOR "YD1SCNNN" NVARCHAR(50),
     "Address1"             FOR "YD1SSHA1" NVARCHAR(30) NOT NULL,
     "Address2"             FOR "YD1SSHA2" NVARCHAR(30) NOT NULL,
     "Address3"             FOR "YD1SSHA3" NVARCHAR(30) NOT NULL,
     "PostalCode"           FOR "YD1SSHPC" NVARCHAR(10) NOT NULL,
     "Country"              FOR "YD1SSHCY" NVARCHAR(50) NOT NULL,
     "Telephone"            FOR "YD1STL" NVARCHAR(20),
     "Email"                FOR "YD1SEM" NVARCHAR(50),
     "Memo"                 FOR "YD1SM1" NVARCHAR(100),
     "PurchasePoints"       FOR "YD1SPRPT" NUMERIC(8,0),
    
     -- Audit Stamps
     "CreatedAt"            FOR "YD1SCRDT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "CreatedBy"            FOR "YD1SCRUS" VARCHAR(128) NOT NULL,
     "CreatedWith"          FOR "YD1SCRAP" VARCHAR(255) NOT NULL,
     "LastModifiedAt"       FOR "YD1SLCDT" TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL,
     "LastModifiedBy"       FOR "YD1SLCUS" VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER),
     "LastModifiedWith"     FOR "YD1SLCAP" VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME),

      -- Primary Key Constraint
      CONSTRAINT "PK_ShippingAddress"
         PRIMARY KEY ("InternalID"),

      -- Referential Foreign Key Constraints
      CONSTRAINT "FK_ShippingAddress_Customer"
         FOREIGN KEY ("CustomerInternalID")
         REFERENCES "Customer"("InternalID")
         ON DELETE RESTRICT ON UPDATE RESTRICT
   )
RCDFMT YD1SPR
ON REPLACE PRESERVE ROWS;

-- Table Description
LABEL ON TABLE "ShippingAddress"
   IS 'Shipping Address';

-- Column Labels - Description (50 Chars)
LABEL ON COLUMN "ShippingAddress" (
     "InternalID"           TEXT IS 'Internal ID',
     "CustomerInternalID"   TEXT IS 'Customer Internal ID',
     "Name"                 TEXT IS 'Name',
     "ContactLastName"      TEXT IS 'Contact Last Name',
     "ContactFirstName"     TEXT IS 'Contact First Name',
     "ContactMiddleName"    TEXT IS 'Contact Middle Name',
     "ContactNickName"      TEXT IS 'Contact Nick Name',
     "Address1"             TEXT IS 'Address 1',
     "Address2"             TEXT IS 'Address 2',
     "Address3"             TEXT IS 'Address 3',
     "PostalCode"           TEXT IS 'Postal Code',
     "Country"              TEXT IS 'Country',
     "Telephone"            TEXT IS 'Telephone',
     "Email"                TEXT IS 'Email',
     "Memo"                 TEXT IS 'Memo',
     "PurchasePoints"       TEXT IS 'Purchase Points',

     "CreatedAt"            TEXT IS 'Created At',
     "CreatedBy"            TEXT IS 'Created By',
     "CreatedWith"          TEXT IS 'Created With',
     "LastModifiedAt"       TEXT IS 'Modified At',
     "LastModifiedBy"       TEXT IS 'Modified By',
     "LastModifiedWith"     TEXT IS 'Modified With'
     );

-- Column Labels - Column Headings (3 x 20 Chars)
LABEL ON COLUMN "ShippingAddress" (
--                             |1-------------------2-------------------3-------------------|
     "InternalID"           IS 'Internal ID',
     "CustomerInternalID"   IS 'Customer            Internal ID',
     "Name"                 IS 'Name',
     "ContactLastName"      IS 'Contact             Last Name',
     "ContactFirstName"     IS 'Contact             First Name',
     "ContactMiddleName"    IS 'Contact             Middle Name',
     "ContactNickName"      IS 'Contact             Nick Name',
     "Address1"             IS 'Address 1',
     "Address2"             IS 'Address 2',
     "Address3"             IS 'Address 3',
     "PostalCode"           IS 'Postal Code',
     "Country"              IS 'Country',
     "Telephone"            IS 'Telephone',
     "Email"                IS 'Email',
     "Memo"                 IS 'Memo',
     "PurchasePoints"       IS 'Purchase Points',

     "CreatedAt"            IS 'Created At',
     "CreatedBy"            IS 'Created By',
     "CreatedWith"          IS 'Created With',
     "LastModifiedAt"       IS 'Modified At',
     "LastModifiedBy"       IS 'Modified By',
     "LastModifiedWith"     IS 'Modified With'
     );

-- Grant Table Access
GRANT DELETE, INSERT, SELECT, UPDATE
ON "ShippingAddress" TO PUBLIC WITH GRANT OPTION ;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE
ON "ShippingAddress" TO QPGMR WITH GRANT OPTION ;

-- Unique Indexes
CREATE UNIQUE INDEX "UQ_ShippingAddress_Name"
   FOR SYSTEM NAME "YD1SIXU1" ON "ShippingAddress" (
   "Name"
   );
LABEL ON INDEX "UQ_ShippingAddress_Name"
   IS 'Shipping Address Name';

-- Indexes
CREATE INDEX "IX_ShippingAddress_PostalCode_Name"
   FOR SYSTEM NAME "YD1SIX02"
   ON "ShippingAddress" (
   "PostalCode", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_PostalCode_Name"
   IS 'Postal Code, Name';

CREATE INDEX "IX_ShippingAddress_ContactLastName_ContactFirstName_Name"
   FOR SYSTEM NAME "YD1SIX03"
   ON "ShippingAddress" (
   "ContactLastName", "ContactFirstName", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_ContactLastName_ContactFirstName_Name"
   IS 'Contact Last and First Name, Name';

CREATE INDEX "IX_ShippingAddress_Telephone_Name"
   FOR SYSTEM NAME "YD1SIX04"
   ON "ShippingAddress" (
   "Telephone", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_Telephone_Name"
   IS 'Telephone, Name';

CREATE INDEX "IX_ShippingAddress_Email_Name"
   FOR SYSTEM NAME "YD1SIX05"
   ON "ShippingAddress" (
   "Email", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_Email_Name"
   IS 'Email, Name';

CREATE INDEX "IX_ShippingAddress_CustomerInternalID_Name"
   FOR SYSTEM NAME "YD1SIX06"
   ON "ShippingAddress" (
   "CustomerInternalID", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_CustomerInternalID_Name"
   IS 'Customer ID, Name';

-- Views
-- CREATE OR REPLACE VIEW "VW_AccountTable_<Descriptors>"
--     FOR SYSTEM NAME "FACCTV01" AS
--          < View Definition >
-- ;
-- LABEL ON TABLE "VVW_AccountTable_<Descriptors>"
--    IS 'View Description';

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> TEXT IS 'View Column Description'
--      );

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> IS 'View Column Description'
--      );

-- GRANT SELECT
-- ON "VW_AccountTable_<Descriptors>" TO PUBLIC WITH GRANT OPTION ;

-- GRANT ALTER, REFERENCES, SELECT
-- ON "VW_AccountTable_<Descriptors>" TO QPGMR WITH GRANT OPTION ;
   
-- Aliases
-- CREATE OR REPLACE ALIAS {AliasName} FOR "AccountTable";

-- Triggers
CREATE OR REPLACE TRIGGER "ShippingAddress_InsertStamps"
   NO CASCADE BEFORE INSERT ON "ShippingAddress"
   REFERENCING NEW AS NEW_ROW
   FOR EACH ROW MODE DB2ROW
   SET NEW_ROW."CreatedBy" = COALESCE(NEW_ROW."CreatedBy", SESSION_USER),
       NEW_ROW."CreatedWith" = COALESCE(NEW_ROW."CreatedWith", CURRENT CLIENT_APPLNAME);

-- SET SCHEMA DEFAULT;

/*******************************************************************************

CONFIDENTIAL AND PROPRIETARY INFORMATION

The receipt or possession of this document does not convey any rights to
reproduce, disclose its contents or manufacture, use or sell anything it may
describe.  Reproduction, disclosure, or use without the specific written
authorization of Surround Technologies, LLC is strictly forbidden.

Copyright ....: (C) Surround Technologies, LLC 1998 - 2021
                9197 Estero River Circle
                Estero, FL 33928
                973-743-1277
                http://www.surroundtech.com/
                 
================================================================================

Source File...: QDBSRC
Source Member.: "Product"
Created by ...: Lee Paul
Created on ...: August 29, 2021
Object Type ..: Table Definition
Description ..: Product

BUILD COMMAND.:
RUNSQLSTM SRCFILE(EASYBUYDM3/QDBSRC) SRCMBR("Product")
    COMMIT(*NONE) ERRLVL(20)

================================================================================
                             Amendment Details
                             -----------------
Date       Programmer      Description
---------- --------------- -----------------------------------------------------


*******************************************************************************
Notes:

To see the next identity value use the following SQL 
SELECT NEXT_IDENTITY_VALUE
    FROM QSYS2.SYSPARTITIONSTAT
    WHERE Table_Schema = 'EasyBuyCycles'
          AND Table_Name = 'Customer'

To see the last Value in the table use the following SQL
SELECT MAX("InternalID")
    FROM "EasyBuyCycles"."Customer";

To set the Customer Table Autoincrementing Identity Value use the follwing SQL
ALTER TABLE "EasyBuyCycles"."Customer"
   ALTER COLUMN "InternalID" RESTART WITH <the number you want>

*******************************************************************************/

-- SET SCHEMA "EasyBuyCycles";
-- SET SCHEMA "EasyBuyCyclesDev";

-- ALTER TABLE "Product"
--    DROP CONSTRAINT "PK_Product",
--    DROP CONSTRAINT "FK_Product_{ReferenceTable}";

DROP INDEX IF EXISTS "UQ_Product_Name";
DROP INDEX IF EXISTS "UQ_Product_Code";
DROP INDEX IF EXISTS "IX_Product_Description_Name";
DROP INDEX IF EXISTS "IX_Product_Category_Name";
DROP INDEX IF EXISTS "IX_Product_Discontinued_Name";
DROP INDEX IF EXISTS "IX_Product_ListPrice_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_";

-- DROP VIEW IF EXISTS "VW_{ViewName}_{ViewDescriptor}";

-- DROP ALIAS IF EXISTS "{AliasName}";

-- DROP TABLE IF EXISTS "Product";
-- Warnng: Dropping a table will lose the data within it.

CREATE OR REPLACE TABLE "Product"
    (
     "InternalID"           FOR "YD1PIID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(MINVALUE 5000 INCREMENT BY 1 CYCLE),
     "Code"                 FOR "YD1PCD" NVARCHAR(25) NOT NULL,
     "Name"                 FOR "YD1PNM" NVARCHAR(50) NOT NULL,
     "Description"          FOR "YD1PDS" NVARCHAR(256),
     "Category"             FOR "YD1PCT" NVARCHAR(50),
     "StandardCost"         FOR "YD1PSTCS" NUMERIC(10,2),
     "ListPrice"            FOR "YD1PLSPR" NUMERIC(10,2) NOT NULL,
     "ReorderLevel"         FOR "YD1PROLV" NUMERIC(4,0),
     "TargetLevel"          FOR "YD1PTGLV" NUMERIC(4,0),
     "MinimumReorderQuantity" FOR "YD1PMRQT" NUMERIC(4,0),
     "Discontinued"         FOR "YD1PDC" CHAR(1),
     "Memo"                 FOR "YD1PM1" NVARCHAR(100),
     "ImagePath"            FOR "YD1PIMPT" NVARCHAR(256),
    
     -- Audit Stamps
     "CreatedAt"            FOR "YD1SCRDT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "CreatedBy"            FOR "YD1SCRUS" VARCHAR(128) NOT NULL,
     "CreatedWith"          FOR "YD1SCRAP" VARCHAR(255) NOT NULL,
     "LastModifiedAt"       FOR "YD1SLCDT" TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL,
     "LastModifiedBy"       FOR "YD1SLCUS" VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER),
     "LastModifiedWith"     FOR "YD1SLCAP" VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME),


      -- Primary Key Constraint
      CONSTRAINT "PK_Product"
         PRIMARY KEY ("InternalID")

      -- Referential Constraints
      -- CONSTRAINT FK_Product_{ReferenceTable}
      --    FOREIGN KEY ({ForeignKeys})
      --    REFERENCES {ReferenceTable}({ReferenceColumns})
      --    {OnDeleteAction} {OnUpdateAction}
   )
RCDFMT YD1PPR
ON REPLACE PRESERVE ROWS;

-- Table Description
LABEL ON TABLE "Product"
   IS 'Product';

-- Column Labels - Description (50 Chars)
LABEL ON COLUMN "Product" (
     "InternalID"           TEXT IS 'Internal ID',
     "Code"                 TEXT IS 'Code',
     "Name"                 TEXT IS 'Name',
     "Description"          TEXT IS 'Description',
     "Category"             TEXT IS 'Category',
     "StandardCost"         TEXT IS 'Standard Cost',
     "ListPrice"            TEXT IS 'List Price',
     "ReorderLevel"         TEXT IS 'Reorder Level',
     "TargetLevel"          TEXT IS 'Target Level',
     "MinimumReorderQuantity" TEXT IS 'Minimum Reorder Quantity',
     "Discontinued"         TEXT IS 'Discontinued',
     "Memo"                 TEXT IS 'Memo',
     "ImagePath"            TEXT IS 'Image Path',

     "CreatedAt"            TEXT IS 'Created At',
     "CreatedBy"            TEXT IS 'Created By',
     "CreatedWith"          TEXT IS 'Created With',
     "LastModifiedAt"       TEXT IS 'Modified At',
     "LastModifiedBy"       TEXT IS 'Modified By',
     "LastModifiedWith"     TEXT IS 'Modified With'
     );

-- Column Labels - Column Headings (3 x 20 Chars)
LABEL ON COLUMN "Product" (
--                             |1-------------------2-------------------3-------------------|
     "InternalID"           IS 'Internal ID',
     "Code"                 IS 'Code',
     "Name"                 IS 'Name',
     "Description"          IS 'Description',
     "Category"             IS 'Category',
     "StandardCost"         IS 'Standard Cost',
     "ListPrice"            IS 'List Price',
     "ReorderLevel"         IS 'Reorder Level',
     "TargetLevel"          IS 'Target Level',
     "MinimumReorderQuantity" IS 'Minimum             Reorder Quantity',
     "Discontinued"         IS 'Discontinued',
     "Memo"                 IS 'Memo',
     "ImagePath"            IS 'Image Path',

     "CreatedAt"            IS 'Created At',
     "CreatedBy"            IS 'Created By',
     "CreatedWith"          IS 'Created With',
     "LastModifiedAt"       IS 'Modified At',
     "LastModifiedBy"       IS 'Modified By',
     "LastModifiedWith"     IS 'Modified With'
     );

-- Grant Table Access
GRANT DELETE, INSERT, SELECT, UPDATE
ON "Product" TO PUBLIC WITH GRANT OPTION ;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE
ON "Product" TO QPGMR WITH GRANT OPTION ;

-- Unique Indexes
CREATE UNIQUE INDEX "UQ_Product_Name"
   FOR SYSTEM NAME "YD1PIXU1" ON "Product" (
   "Name"
   );
LABEL ON INDEX "UQ_Product_Name"
   IS 'Product Name';

CREATE UNIQUE INDEX "UQ_Product_Code"
   FOR SYSTEM NAME "YD1PIXU2" ON "Product" (
   "Code"
   );
LABEL ON INDEX "UQ_Product_Code"
   IS 'Product Code';

-- Indexes
CREATE INDEX "IX_Product_Description_Name"
   FOR SYSTEM NAME "YD1PIX03"
   ON "Product" (
   "Description", "Name"
   );
LABEL ON INDEX "IX_Product_Description_Name"
   IS 'Description, Name';

CREATE INDEX "IX_Product_Category_Name"
   FOR SYSTEM NAME "YD1PIX04"
   ON "Product" (
   "Category", "Name"
   );
LABEL ON INDEX "IX_Product_Category_Name"
   IS 'Category, Name';

CREATE INDEX "IX_Product_Discontinued_Name"
   FOR SYSTEM NAME "YD1PIX05"
   ON "Product" (
   "Discontinued", "Name"
   );
LABEL ON INDEX "IX_Product_Discontinued_Name"
   IS 'Discontinued, Name';

CREATE INDEX "IX_Product_ListPrice_Name"
   FOR SYSTEM NAME "YD1PIX06"
   ON "Product" (
   "ListPrice", "Name"
   );
LABEL ON INDEX "IX_Product_ListPrice_Name"
   IS 'List Price, Name';

-- Views
-- CREATE OR REPLACE VIEW "VW_AccountTable_<Descriptors>"
--     FOR SYSTEM NAME "FACCTV01" AS
--          < View Definition >
-- ;
-- LABEL ON TABLE "VVW_AccountTable_<Descriptors>"
--    IS 'View Description';

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> TEXT IS 'View Column Description'
--      );

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> IS 'View Column Description'
--      );

-- GRANT SELECT
-- ON "VW_AccountTable_<Descriptors>" TO PUBLIC WITH GRANT OPTION ;

-- GRANT ALTER, REFERENCES, SELECT
-- ON "VW_AccountTable_<Descriptors>" TO QPGMR WITH GRANT OPTION ;
   
-- Aliases
-- CREATE OR REPLACE ALIAS {AliasName} FOR "AccountTable";

-- Triggers
CREATE OR REPLACE TRIGGER "Product_InsertStamps"
   NO CASCADE BEFORE INSERT ON "Product"
   REFERENCING NEW AS NEW_ROW
   FOR EACH ROW MODE DB2ROW
   SET NEW_ROW."CreatedBy" = COALESCE(NEW_ROW."CreatedBy", SESSION_USER),
       NEW_ROW."CreatedWith" = COALESCE(NEW_ROW."CreatedWith", CURRENT CLIENT_APPLNAME);

-- SET SCHEMA DEFAULT;

/*******************************************************************************

CONFIDENTIAL AND PROPRIETARY INFORMATION

The receipt or possession of this document does not convey any rights to
reproduce, disclose its contents or manufacture, use or sell anything it may
describe.  Reproduction, disclosure, or use without the specific written
authorization of Surround Technologies, LLC is strictly forbidden.

Copyright ....: (C) Surround Technologies, LLC 1998 - 2021
                9197 Estero River Circle
                Estero, FL 33928
                973-743-1277
                http://www.surroundtech.com/
                 
================================================================================

Source File...: QDBSRC
Source Member.: "Order"
Created by ...: Lee Paul
Created on ...: August 29, 2021
Object Type ..: Table Definition
Description ..: Order

BUILD COMMAND.:
RUNSQLSTM SRCFILE(EASYBUYDM3/QDBSRC) SRCMBR("Order")
    COMMIT(*NONE) ERRLVL(20)

================================================================================
                             Amendment Details
                             -----------------
Date       Programmer      Description
---------- --------------- -----------------------------------------------------


*******************************************************************************
Notes:

To see the next identity value use the following SQL 
SELECT NEXT_IDENTITY_VALUE
    FROM QSYS2.SYSPARTITIONSTAT
    WHERE Table_Schema = 'EasyBuyCycles'
          AND Table_Name = 'Customer'

To see the last Value in the table use the following SQL
SELECT MAX("InternalID")
    FROM "EasyBuyCycles"."Customer";

To set the Customer Table Autoincrementing Identity Value use the follwing SQL
ALTER TABLE "EasyBuyCycles"."Customer"
   ALTER COLUMN "InternalID" RESTART WITH <the number you want>

*******************************************************************************/

-- SET SCHEMA "EasyBuyCycles";
-- SET SCHEMA "EasyBuyCyclesDev";

-- ALTER TABLE "Order"
--    DROP CONSTRAINT "PK_Order",
--    DROP CONSTRAINT "FK_Order_{ReferenceTable}";

-- DROP INDEX IF EXISTS "UQ_Order_{IndexDescriptor}";
DROP INDEX IF EXISTS "IX_Order_OrderDateTime_InternalID";
DROP INDEX IF EXISTS "IX_Order_CustomerInternalID_InternalID";
DROP INDEX IF EXISTS "IX_Order_CustomerInternalID_OrderDateTime_InternalID";
DROP INDEX IF EXISTS "IX_Order_CustomerInternalID_ PO_OrderDateTime_InternalID";
DROP INDEX IF EXISTS "IX_Order_PO_OrderDateTime_InternalID";
DROP INDEX IF EXISTS "IX_Order_SalesPersonName_OrderDateTime_InternalID";
DROP INDEX IF EXISTS "IX_Order_WarehouseName_OrderDateTime_InternalID";
DROP INDEX IF EXISTS "IX_Order_Status_OrderDateTime_InternalID";
DROP INDEX IF EXISTS "IX_Order_CustomerInternalID_Status_OrderDateTime_InternalID";
DROP INDEX IF EXISTS "IX_Order_ShippingAddressInternalID_OrderDateTime_InternalID";

-- DROP VIEW IF EXISTS "VW_{ViewName}_{ViewDescriptor}";

-- DROP ALIAS IF EXISTS "{AliasName}";

-- DROP TABLE IF EXISTS "Order";
-- Warnng: Dropping a table will lose the data within it.

CREATE OR REPLACE TABLE "Order"
    (
     "InternalID"           FOR "YD1OIID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(MINVALUE 5000 INCREMENT BY 1 CYCLE),
     "CustomerInternalID"   FOR "YD1O1CID" INT NOT NULL,
     "OrderDateTime"        FOR "YD1ODT" TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "PurchaseOrderNumber"  FOR "YD1OPONO" CHAR(50) NOT NULL,
     "WarehouseInternalID"  FOR "YD1O1WID" INT,
     "WarehouseName"        FOR "YD1O1WNM" NVARCHAR(50) NOT NULL,
     "DeliveryMemo"         FOR "YD1ODLM1" NVARCHAR(100),
     "ShippingAddressInternalID" FOR "YD1O1SID" INT,
     "OrderMemo"            FOR "YD1OM1" NVARCHAR(100),
     "Status"               FOR "YD1OST" NVARCHAR(10),
     "SalesPersonInternalID" FOR "YD1O1AID" INT,
     "SalesPersonName"      FOR "YD1O1ANM" NVARCHAR(50) NOT NULL,
     "PurchasePoints"       FOR "YD1CPRPT" NUMERIC(8,0),
    
     -- Audit Stamps
     "CreatedAt"            FOR "YD1SCRDT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "CreatedBy"            FOR "YD1SCRUS" VARCHAR(128) NOT NULL,
     "CreatedWith"          FOR "YD1SCRAP" VARCHAR(255) NOT NULL,
     "LastModifiedAt"       FOR "YD1SLCDT" TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL,
     "LastModifiedBy"       FOR "YD1SLCUS" VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER),
     "LastModifiedWith"     FOR "YD1SLCAP" VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME),

      -- Primary Key Constraint
      CONSTRAINT "PK_Order"
         PRIMARY KEY ("InternalID"),

      -- Referential Foreign Key Constraints
      CONSTRAINT "FK_Order_Customer"
         FOREIGN KEY ("CustomerInternalID")
         REFERENCES "Customer"("InternalID")
         ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT "FK_Order_ShippingAddress"
         FOREIGN KEY ("ShippingAddressInternalID")
         REFERENCES "ShippingAddress"("InternalID")
         ON DELETE RESTRICT ON UPDATE RESTRICT
   )
RCDFMT YD1OPR
ON REPLACE PRESERVE ROWS;

-- Table Description
LABEL ON TABLE "Order"
   IS 'Order';

-- Column Labels - Description (50 Chars)
LABEL ON COLUMN "Order" (
     "InternalID"           TEXT IS 'Internal ID',
     "CustomerInternalID"   TEXT IS 'Customer Internal ID',
     "OrderDateTime"        TEXT IS 'Order Date and Time',
     "PurchaseOrderNumber"  TEXT IS 'Purchase Order Number',
     "WarehouseInternalID"  TEXT IS 'Warehouse Internal ID',
     "WarehouseName"        TEXT IS 'Warehouse Name',
     "DeliveryMemo"         TEXT IS 'Delivery Memo',
     "ShippingAddressInternalID" TEXT IS 'Shipping Address Internal ID',
     "OrderMemo"            TEXT IS 'Order Memo',
     "Status"               TEXT IS 'Status',
     "SalesPersonInternalID" TEXT IS 'Sales Person Internal ID',
     "SalesPersonName"      TEXT IS 'Sales Person Name',
     "PurchasePoints"       TEXT IS 'Purchase Points',

     "CreatedAt"            TEXT IS 'Created At',
     "CreatedBy"            TEXT IS 'Created By',
     "CreatedWith"          TEXT IS 'Created With',
     "LastModifiedAt"       TEXT IS 'Modified At',
     "LastModifiedBy"       TEXT IS 'Modified By',
     "LastModifiedWith"     TEXT IS 'Modified With'
     );

-- Column Labels - Column Headings (3 x 20 Chars)
LABEL ON COLUMN "Order" (
--                             |1-------------------2-------------------3-------------------|
     "InternalID"           IS 'Internal ID',
     "CustomerInternalID"   IS 'Customer            Internal ID',
     "OrderDateTime"        IS 'Order Date          And Time',
     "PurchaseOrderNumber"  IS 'Purchase Order      Number',
     "WarehouseInternalID"  IS 'Warehouse           Internal ID',
     "WarehouseName"        IS 'Warehouse           Name',
     "DeliveryMemo"         IS 'Delivery Memo',
     "ShippingAddressInternalID" IS 'Shipping Address    Internal ID',
     "OrderMemo"            IS 'Order Memo',
     "Status"               IS 'Status',
     "SalesPersonInternalID" IS 'Sales Person        Internal ID',
     "SalesPersonName"      IS 'Sales Person        Name',
     "PurchasePoints"       IS 'Purchase Points',

     "CreatedAt"            IS 'Created At',
     "CreatedBy"            IS 'Created By',
     "CreatedWith"          IS 'Created With',
     "LastModifiedAt"       IS 'Modified At',
     "LastModifiedBy"       IS 'Modified By',
     "LastModifiedWith"     IS 'Modified With'
     );

-- Grant Table Access
GRANT DELETE, INSERT, SELECT, UPDATE
ON "Order" TO PUBLIC WITH GRANT OPTION ;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE
ON "Order" TO QPGMR WITH GRANT OPTION ;

-- Unique Indexes
-- CREATE UNIQUE |WHERE NOT NULL| INDEX "UQ_Order_#"
--    FOR SYSTEM NAME "{IndexSystemName}"
--    ON "Order" (
--    {IndexColumns}
--    WHERE {FilterCondition}
--    );
-- LABEL ON INDEX "UQ_Order_#"
--    IS '{IndexColumnDescriptions}';


-- Indexes
CREATE INDEX "IX_Order_OrderDateTime_InternalID"
   FOR SYSTEM NAME "YD1OIX01"
   ON "Order" (
   "OrderDateTime" DESC, "InternalID"
   );
LABEL ON INDEX "IX_Order_OrderDateTime_InternalID"
   IS 'Order Date/Time';

CREATE INDEX "IX_Order_CustomerInternalID_OrderDateTime_InternalID"
   FOR SYSTEM NAME "YD1OIX02"
   ON "Order" (
   "CustomerInternalID", "OrderDateTime" DESC, "InternalID"
   );
LABEL ON INDEX "IX_Order_CustomerInternalID_OrderDateTime_InternalID"
   IS 'Customer Internal ID, Order Date/Time';

CREATE INDEX "IX_Order_CustomerInternalID_ PO_OrderDateTime_InternalID"
   FOR SYSTEM NAME "YD1OIX03"
   ON "Order" (
   "CustomerInternalID",  "PurchaseOrderNumber", "OrderDateTime" DESC,
   "InternalID"
   );
LABEL ON INDEX "IX_Order_CustomerInternalID_ PO_OrderDateTime_InternalID"
   IS 'Customer Internal ID and PO No.';

CREATE INDEX "IX_Order_PO_OrderDateTime_InternalID"
   FOR SYSTEM NAME "YD1OIX04"
   ON "Order" (
   "PurchaseOrderNumber", "OrderDateTime" DESC, "InternalID"
   );
LABEL ON INDEX "IX_Order_PO_OrderDateTime_InternalID"
   IS 'PO No., Order Date/Time';

CREATE INDEX "IX_Order_SalesPersonName_OrderDateTime_InternalID"
   FOR SYSTEM NAME "YD1OIX05"
   ON "Order" (
   "SalesPersonName", "OrderDateTime" DESC, "InternalID"
   );
LABEL ON INDEX "IX_Order_SalesPersonName_OrderDateTime_InternalID"
   IS 'Sales Person Name, Order Date/Time';

CREATE INDEX "IX_Order_WarehouseName_OrderDateTime_InternalID"
   FOR SYSTEM NAME "YD1OIX06"
   ON "Order" (
   "WarehouseName", "OrderDateTime" DESC, "InternalID"
   );
LABEL ON INDEX "IX_Order_WarehouseName_OrderDateTime_InternalID"
   IS 'Warehouse Name';

CREATE INDEX "IX_Order_Status_OrderDateTime_InternalID"
   FOR SYSTEM NAME "YD1OIX07"
   ON "Order" (
   "Status", "OrderDateTime" DESC, "InternalID"
   );
LABEL ON INDEX "IX_Order_Status_OrderDateTime_InternalID"
   IS 'Status, Order Data/Time';

CREATE INDEX
   "IX_Order_CustomerInternalID_Status_OrderDateTime_InternalID"
   FOR SYSTEM NAME "YD1OIX08"
   ON "Order" (
   "CustomerInternalID", "Status", "OrderDateTime" DESC, "InternalID"
   );
LABEL ON INDEX
   "IX_Order_CustomerInternalID_Status_OrderDateTime_InternalID"
   IS 'Customer Internal ID and Status';

CREATE INDEX
   "IX_Order_ShippingAddressInternalID_OrderDateTime_InternalID"
   FOR SYSTEM NAME "YD1OIX09"
   ON "Order" (
   "ShippingAddressInternalID", "OrderDateTime" DESC, "InternalID"
   );
LABEL ON INDEX 
   "IX_Order_ShippingAddressInternalID_OrderDateTime_InternalID"
   IS 'Shipping Address Internal ID';

CREATE INDEX "IX_Order_CustomerInternalID_InternalID"
   FOR SYSTEM NAME "YD1OIX10"
   ON "Order" (
   "CustomerInternalID", "InternalID"
   );
LABEL ON INDEX "IX_Order_CustomerInternalID_InternalID"
   IS 'Customer Internal ID';

-- Views
-- CREATE OR REPLACE VIEW "VW_AccountTable_<Descriptors>"
--     FOR SYSTEM NAME "FACCTV01" AS
--          < View Definition >
-- ;
-- LABEL ON TABLE "VVW_AccountTable_<Descriptors>"
--    IS 'View Description';

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> TEXT IS 'View Column Description'
--      );

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> IS 'View Column Description'
--      );

-- GRANT SELECT
-- ON "VW_AccountTable_<Descriptors>" TO PUBLIC WITH GRANT OPTION ;

-- GRANT ALTER, REFERENCES, SELECT
-- ON "VW_AccountTable_<Descriptors>" TO QPGMR WITH GRANT OPTION ;
   
-- Aliases
-- CREATE OR REPLACE ALIAS {AliasName} FOR "AccountTable";

-- Triggers
CREATE OR REPLACE TRIGGER "Order_InsertStamps"
   NO CASCADE BEFORE INSERT ON "Order"
   REFERENCING NEW AS NEW_ROW
   FOR EACH ROW MODE DB2ROW
   SET NEW_ROW."CreatedBy" = COALESCE(NEW_ROW."CreatedBy", SESSION_USER),
       NEW_ROW."CreatedWith" = COALESCE(NEW_ROW."CreatedWith", CURRENT CLIENT_APPLNAME);

-- SET SCHEMA DEFAULT;

/*******************************************************************************

CONFIDENTIAL AND PROPRIETARY INFORMATION

The receipt or possession of this document does not convey any rights to
reproduce, disclose its contents or manufacture, use or sell anything it may
describe.  Reproduction, disclosure, or use without the specific written
authorization of Surround Technologies, LLC is strictly forbidden.

Copyright ....: (C) Surround Technologies, LLC 1998 - 2021
                9197 Estero River Circle
                Estero, FL 33928
                973-743-1277
                http://www.surroundtech.com/
                 
================================================================================

Source File...: QDBSRC
Source Member.: "OrdItm"
Created by ...: Lee Paul
Created on ...: August 29, 2021
Object Type ..: Table Definition
Description ..: Order Item

BUILD COMMAND.:
RUNSQLSTM SRCFILE(EASYBUYDM3/QDBSRC) SRCMBR("OrdItm")
    COMMIT(*NONE) ERRLVL(20)

================================================================================
                             Amendment Details
                             -----------------
Date       Programmer      Description
---------- --------------- -----------------------------------------------------


*******************************************************************************
Notes:

To see the next identity value use the following SQL 
SELECT NEXT_IDENTITY_VALUE
    FROM QSYS2.SYSPARTITIONSTAT
    WHERE Table_Schema = 'EasyBuyCycles'
          AND Table_Name = 'Customer'

To see the last Value in the table use the following SQL
SELECT MAX("InternalID")
    FROM "EasyBuyCycles"."Customer";

To set the Customer Table Autoincrementing Identity Value use the follwing SQL
ALTER TABLE "EasyBuyCycles"."Customer"
   ALTER COLUMN "InternalID" RESTART WITH <the number you want>

*******************************************************************************/

-- SET SCHEMA "EasyBuyCycles";
-- SET SCHEMA "EasyBuyCyclesDev";

-- ALTER TABLE "OrderItem"
--    DROP CONSTRAINT "PK_OrderItem";
--    DROP CONSTRAINT "FK_OrderItem_{ReferenceTable}";

-- DROP INDEX IF EXISTS "UQ_OrderItem_{IndexDescriptor}";
DROP INDEX IF EXISTS "IX_OrderItem_OrderInternalID_ProductInternalID_InternalID";
DROP INDEX IF EXISTS "IX_OrderItem_ProductInternalID_OrderInternalID_InternalID";
DROP INDEX IF EXISTS "IX_OrderItem_OrderInternalID_InternalID";

-- DROP VIEW IF EXISTS "VW_{ViewName}_{ViewDescriptor}";

-- DROP ALIAS IF EXISTS "{AliasName}";

-- DROP TABLE IF EXISTS "OrderItem";
-- Warnng: Dropping a table will lose the data within it.

CREATE OR REPLACE TABLE "OrderItem"
    FOR SYSTEM NAME "OrdItm"  (
     "InternalID"           FOR "YD1IIID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(MINVALUE 5000 INCREMENT BY 1 CYCLE),
     "OrderInternalID"      FOR "YD1I1OID" INT NOT NULL,
     "ProductInternalID"    FOR "YD1I1PID" INT NOT NULL,
     "Quantity"             FOR "YD1IQT" NUMERIC(4,0) NOT NULL,
     "UnitPrice"            FOR "YD1IPRUN" NUMERIC(8,2),
     "DiscountPercent"      FOR "YD1IDSPC" NUMERIC(4,1),
     "Memo"                 FOR "YD1IM1" NVARCHAR(100),
    
     -- Audit Stamps
     "CreatedAt"            FOR "YD1SCRDT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "CreatedBy"            FOR "YD1SCRUS" VARCHAR(128) NOT NULL,
     "CreatedWith"          FOR "YD1SCRAP" VARCHAR(255) NOT NULL,
     "LastModifiedAt"       FOR "YD1SLCDT" TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL,
     "LastModifiedBy"       FOR "YD1SLCUS" VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER),
     "LastModifiedWith"     FOR "YD1SLCAP" VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME),

      -- Primary Key Constraint
      CONSTRAINT "PK_OrderItem"
         PRIMARY KEY ("InternalID"),

      -- Referential Foreign Key Constraints
      CONSTRAINT "FK_OrderItem_Order"
         FOREIGN KEY ("OrderInternalID")
         REFERENCES "Order"("InternalID")
         ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT "FK_OrderItem_Product"
         FOREIGN KEY ("ProductInternalID")
         REFERENCES "Product"("InternalID")
         ON DELETE RESTRICT ON UPDATE RESTRICT
   )
RCDFMT YD1IPR
ON REPLACE PRESERVE ROWS;

-- Table Description
LABEL ON TABLE "OrderItem"
   IS 'Order Item';

-- Column Labels - Description (50 Chars)
LABEL ON COLUMN "OrderItem" (
     "InternalID"           TEXT IS 'Internal ID',
     "OrderInternalID"      TEXT IS 'Order Internal ID',
     "ProductInternalID"    TEXT IS 'Product Internal ID',
     "Quantity"             TEXT IS 'Quantity',
     "UnitPrice"            TEXT IS 'Unit Price',
     "DiscountPercent"      TEXT IS 'Discount Percent',
     "Memo"                 TEXT IS 'Memo',

     "CreatedAt"            TEXT IS 'Created At',
     "CreatedBy"            TEXT IS 'Created By',
     "CreatedWith"          TEXT IS 'Created With',
     "LastModifiedAt"       TEXT IS 'Modified At',
     "LastModifiedBy"       TEXT IS 'Modified By',
     "LastModifiedWith"     TEXT IS 'Modified With'
     );

-- Column Labels - Column Headings (3 x 20 Chars)
LABEL ON COLUMN "OrderItem" (
--                             |1-------------------2-------------------3-------------------|
     "InternalID"           IS 'Internal ID',
     "OrderInternalID"      IS 'Order               Internal ID',
     "ProductInternalID"    IS 'Product             Internal ID',
     "Quantity"             IS 'Quantity',
     "UnitPrice"            IS 'Unit Price',
     "DiscountPercent"      IS 'Discount Percent',
     "Memo"                 IS 'Memo',

     "CreatedAt"            IS 'Created At',
     "CreatedBy"            IS 'Created By',
     "CreatedWith"          IS 'Created With',
     "LastModifiedAt"       IS 'Modified At',
     "LastModifiedBy"       IS 'Modified By',
     "LastModifiedWith"     IS 'Modified With'
     );

-- Grant Table Access
GRANT DELETE, INSERT, SELECT, UPDATE
ON "OrderItem" TO PUBLIC WITH GRANT OPTION ;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE
ON "OrderItem" TO QPGMR WITH GRANT OPTION ;

-- Unique Indexes
-- CREATE UNIQUE |WHERE NOT NULL| INDEX "UQ_OrderItem_#"
--    FOR SYSTEM NAME "{IndexSystemName}"
--    ON "OrderItem" (
--    {IndexColumns}
--    WHERE {FilterCondition}
--    );
-- LABEL ON INDEX "UQ_OrderItem_#"
--    IS 'Sort by {IndexColumnDescriptions}';

-- Indexes
CREATE INDEX "IX_OrderItem_OrderInternalID_ProductInternalID_InternalID"
   FOR SYSTEM NAME "YD1IIX01"
   ON "OrderItem" (
   "OrderInternalID", "ProductInternalID", "InternalID"
   );
LABEL ON INDEX "IX_OrderItem_OrderInternalID_ProductInternalID_InternalID"
   IS 'Order and Product Internal IDs';

CREATE INDEX "IX_OrderItem_ProductInternalID_OrderInternalID_InternalID"
   FOR SYSTEM NAME "YD1IIX02"
   ON "OrderItem" (
   "ProductInternalID", "OrderInternalID", "InternalID"
   );
LABEL ON INDEX "IX_OrderItem_ProductInternalID_OrderInternalID_InternalID"
   IS 'Product and Order Internal IDs';

CREATE INDEX "IX_OrderItem_OrderInternalID_InternalID"
   FOR SYSTEM NAME "YD1IIX03"
   ON "OrderItem" (
   "OrderInternalID", "InternalID"
   );
LABEL ON INDEX "IX_OrderItem_OrderInternalID_InternalID"
   IS 'Order Internal ID';

-- Views
-- CREATE OR REPLACE VIEW "VW_AccountTable_<Descriptors>"
--     FOR SYSTEM NAME "FACCTV01" AS
--          < View Definition >
-- ;
-- LABEL ON TABLE "VVW_AccountTable_<Descriptors>"
--    IS 'View Description';

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> TEXT IS 'View Column Description'
--      );

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> IS 'View Column Description'
--      );

-- GRANT SELECT
-- ON "VW_AccountTable_<Descriptors>" TO PUBLIC WITH GRANT OPTION ;

-- GRANT ALTER, REFERENCES, SELECT
-- ON "VW_AccountTable_<Descriptors>" TO QPGMR WITH GRANT OPTION ;
   
-- Aliases
-- CREATE OR REPLACE ALIAS {AliasName} FOR "AccountTable";

-- Triggers
CREATE OR REPLACE TRIGGER "OrderItem_InsertStamps"
   NO CASCADE BEFORE INSERT ON "OrderItem"
   REFERENCING NEW AS NEW_ROW
   FOR EACH ROW MODE DB2ROW
   SET NEW_ROW."CreatedBy" = COALESCE(NEW_ROW."CreatedBy", SESSION_USER),
       NEW_ROW."CreatedWith" = COALESCE(NEW_ROW."CreatedWith", CURRENT CLIENT_APPLNAME);

-- SET SCHEMA DEFAULT;