/*******************************************************************************

CONFIDENTIAL AND PROPRIETARY INFORMATION

The receipt or possession of this document does not convey any rights to
reproduce, disclose its contents or manufacture, use or sell anything it may
describe.  Reproduction, disclosure, or use without the specific written
authorization of Surround Technologies, LLC is strictly forbidden.

Copyright ....: (C) Surround Technologies, LLC 1998 - 2021
                9197 Estero River Circle
                Estero, FL 33928
                973-743-1277
                http://www.surroundtech.com/
                 
================================================================================

Source File...: QDBSRC
Source Member.: IBM i DDL EasyBuyCyclesModern Customer.sql
Created by ...: Lee Paul
Created on ...: September 14, 2022
Object Type ..: Table Definition
Description ..: Customer

BUILD COMMAND.:
RUNSQLSTM SRCFILE(EASYBUYDM3/QDBSRC) SRCMBR("Customer")
    COMMIT(*NONE) ERRLVL(20)

================================================================================
                             Amendment Details
                             -----------------
Date       Programmer      Description
---------- --------------- -----------------------------------------------------


*******************************************************************************
Notes:

To see the next identity value use the following SQL 
SELECT NEXT_IDENTITY_VALUE
    FROM QSYS2.SYSPARTITIONSTAT
    WHERE Table_Schema = 'EasyBuyCycles'
          AND Table_Name = 'Customer'

To see the last Value in the table use the following SQL
SELECT MAX("InternalID")
    FROM "EasyBuyCycles"."Customer";

To set the Customer Table Autoincrementing Identity Value use the follwing SQL
ALTER TABLE "EasyBuyCycles"."Customer"
   ALTER COLUMN "InternalID" RESTART WITH <the number you want>

*******************************************************************************/

SET SCHEMA "EasyBuyCycles";
--SET SCHEMA "EasyBuyCyclesDev";

-- ALTER TABLE "Customer"
--    DROP CONSTRAINT "PK_Customer",
--    DROP CONSTRAINT "FK_Customer_{ReferenceTable}";

DROP INDEX IF EXISTS "UQ_Customer_Name";
DROP INDEX IF EXISTS "IX_Customer_ParentInternalID_Name";
DROP INDEX IF EXISTS "IX_Customer_LegalName_Name";
DROP INDEX IF EXISTS "IX_Customer_ContactLastName_ContactFirstName_Name";
DROP INDEX IF EXISTS "IX_Customer_BillingPostalCode_Name";
DROP INDEX IF EXISTS "IX_Customer_Telephone_Name";
DROP INDEX IF EXISTS "IX_Customer_PurchasePoints_Name";

-- DROP VIEW IF EXISTS "VW_{ViewName}";

-- DROP ALIAS IF EXISTS "{AliasName}";

-- DROP TABLE IF EXISTS "Customer";
-- Warnng: Dropping a table will lose the data within it.

CREATE OR REPLACE TABLE "Customer"
    (
     "InternalID"           FOR "YD1CIID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(MINVALUE 5000 INCREMENT BY 1 CYCLE),
     "ParentInternalID"     FOR "YD1CPTID" INT,
     "ParentRelationship"   FOR "YD1CPTRL" NVARCHAR(20),
     "Name"                 FOR "YD1CNM" NVARCHAR(50) NOT NULL,
     "LegalName"            FOR "YD1CNMLG" NVARCHAR(50),
     "ContactLastName"      FOR "YD1CCNLN" NVARCHAR(50) NOT NULL,
     "ContactFirstName"     FOR "YD1CCNFN" NVARCHAR(50) NOT NULL,
     "ContactMiddleName"    FOR "YD1CCNMN" NVARCHAR(50),
     "ContactNickName"      FOR "YD1CCNNN" NVARCHAR(50),
     "BillingAddress1"      FOR "YD1CBLA1" NVARCHAR(30) NOT NULL,
     "BillingAddress2"      FOR "YD1CBLA2" NVARCHAR(30) NOT NULL,
     "BillingAddress3"      FOR "YD1CBLA3" NVARCHAR(30) NOT NULL,
     "BillingPostalCode"    FOR "YD1CBLPC" NVARCHAR(10) NOT NULL,
     "BillingCountry"       FOR "YD1CBLCY" NVARCHAR(50) NOT NULL,
     "Telephone"            FOR "YD1CTL" NVARCHAR(20),
     "Email"                FOR "YD1CEM" NVARCHAR(50),
     "Memo"                 FOR "YD1CM1" NVARCHAR(100),
     "PurchasePoints"       FOR "YD1CPRPT" NUMERIC(8,0) DEFAULT 0,
    
     -- Audit Stamps
     "CreatedAt"            FOR "YD1CCRDT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "CreatedBy"            FOR "YD1CCRUS" VARCHAR(128) NOT NULL,
     "CreatedWith"          FOR "YD1CCRAP" VARCHAR(255) NOT NULL,
     "LastModifiedAt"       FOR "YD1CLCDT" TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL,
     "LastModifiedBy"       FOR "YD1CLCUS" VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER),
     "LastModifiedWith"     FOR "YD1CLCAP" VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME),

      -- Primary Key Constraint
      CONSTRAINT "PK_Customer"
         PRIMARY KEY ("InternalID"),

      -- Referential Foreign Key Constraints
      CONSTRAINT "FK_Customer_ParentCustomer"
         FOREIGN KEY ("ParentInternalID")
         REFERENCES "Customer"("InternalID")
         ON DELETE RESTRICT ON UPDATE RESTRICT
   )
RCDFMT YD1CPR
ON REPLACE PRESERVE ROWS;

-- Table Description
LABEL ON TABLE "Customer"
   IS 'Customer';

-- Column Labels - Description (50 Chars)
LABEL ON COLUMN "Customer" (
     "InternalID"           TEXT IS 'Internal ID',
     "ParentInternalID"     TEXT IS 'Parent Internal ID',
     "ParentRelationship"   TEXT IS 'Parent Relationship',
     "Name"                 TEXT IS 'Name',
     "LegalName"            TEXT IS 'Legal Name',
     "ContactLastName"      TEXT IS 'Contact Last Name',
     "ContactFirstName"     TEXT IS 'Contact First Name',
     "ContactMiddleName"    TEXT IS 'Contact Middle Name',
     "ContactNickName"      TEXT IS 'Contact Nick Name',
     "BillingAddress1"      TEXT IS 'Billing Address 1',
     "BillingAddress2"      TEXT IS 'Billing Address 2',
     "BillingAddress3"      TEXT IS 'Billing Address 3',
     "BillingPostalCode"    TEXT IS 'Billing Postal Code',
     "BillingCountry"       TEXT IS 'Billing Country',
     "Telephone"            TEXT IS 'Telephone',
     "Email"                TEXT IS 'Email',
     "Memo"                 TEXT IS 'Memo',
     "PurchasePoints"       TEXT IS 'Purchase Points',

     "CreatedAt"            TEXT IS 'Created At',
     "CreatedBy"            TEXT IS 'Created By',
     "CreatedWith"          TEXT IS 'Created With',
     "LastModifiedAt"       TEXT IS 'Modified At',
     "LastModifiedBy"       TEXT IS 'Modified By',
     "LastModifiedWith"     TEXT IS 'Modified With'
     );

-- Column Labels - Column Headings (3 x 20 Chars)
LABEL ON COLUMN "Customer" (
--                             |1-------------------2-------------------3-------------------|
     "InternalID"           IS 'Internal ID',
     "ParentInternalID"     IS 'Parent              Internal ID',
     "ParentRelationship"   IS 'Parent              Relationship',
     "Name"                 IS 'Name',
     "LegalName"            IS 'Legal Name',
     "ContactLastName"      IS 'Contact             Last Name',
     "ContactFirstName"     IS 'Contact             First Name',
     "ContactMiddleName"    IS 'Contact             Middle Name',
     "ContactNickName"      IS 'Contact             Nick Name',
     "BillingAddress1"      IS 'Billing             Address 1',
     "BillingAddress2"      IS 'Billing             Address 2',
     "BillingAddress3"      IS 'Billing             Address 3',
     "BillingPostalCode"    IS 'Billing             Postal Code',
     "BillingCountry"       IS 'Billing             Country',
     "Telephone"            IS 'Telephone',
     "Email"                IS 'Email',
     "Memo"                 IS 'Memo',
     "PurchasePoints"       IS 'Purchase Points',

     "CreatedAt"            IS 'Created At',
     "CreatedBy"            IS 'Created By',
     "CreatedWith"          IS 'Created With',
     "LastModifiedAt"       IS 'Modified At',
     "LastModifiedBy"       IS 'Modified By',
     "LastModifiedWith"     IS 'Modified With'
     );

-- Grant Table Access
GRANT DELETE, INSERT, SELECT, UPDATE
ON "Customer" TO PUBLIC WITH GRANT OPTION ;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE
ON "Customer" TO QPGMR WITH GRANT OPTION ;

-- Unique Indexes
CREATE UNIQUE INDEX "UQ_Customer_Name"
   FOR SYSTEM NAME "YD1CIXU1" ON "Customer" (
   "Name"
   );
LABEL ON INDEX "UQ_Customer_Name"
   IS 'Name';

-- Indexes
CREATE INDEX "IX_Customer_ParentInternalID_Name"
   FOR SYSTEM NAME "YD1CIX02"
   ON "Customer" (
   "ParentInternalID", "Name"
   );
LABEL ON INDEX "IX_Customer_ParentInternalID_Name"
   IS 'Parrent Internal ID';

CREATE INDEX "IX_Customer_LegalName_Name"
   FOR SYSTEM NAME "YD1CIX03"
   ON "Customer" (
   "LegalName", "Name"
   );
LABEL ON INDEX "IX_Customer_LegalName_Name"
   IS 'Legal Name';

CREATE INDEX "IX_Customer_ContactLastName_ContactFirstName_Name"
   FOR SYSTEM NAME "YD1CIX04"
   ON "Customer" (
   "ContactLastName", "ContactFirstName", "Name"
   );
LABEL ON INDEX "IX_Customer_ContactLastName_ContactFirstName_Name"
   IS 'Contact Last and First Names';

CREATE INDEX "IX_Customer_BillingPostalCode_Name"
   FOR SYSTEM NAME "YD1CIX05"
   ON "Customer" (
   "BillingPostalCode", "Name"
   );
LABEL ON INDEX "IX_Customer_BillingPostalCode_Name"
   IS 'Billing Postal Code';

CREATE INDEX "IX_Customer_Telephone_Name"
   FOR SYSTEM NAME "YD1CIX06"
   ON "Customer" (
   "Telephone", "Name"
   );
LABEL ON INDEX "IX_Customer_Telephone_Name"
   IS 'Telephone';

CREATE INDEX "IX_Customer_PurchasePoints_Name"
   FOR SYSTEM NAME "YD1CIX07"
   ON "Customer" (
   "PurchasePoints", "Name"
   );
LABEL ON INDEX "IX_Customer_PurchasePoints_Name"
   IS 'Purchase Points';

-- Views
-- CREATE OR REPLACE VIEW "VW_AccountTable_<Descriptors>"
--     FOR SYSTEM NAME "FACCTV01" AS
--          < View Definition >
-- ;
-- LABEL ON TABLE "VVW_AccountTable_<Descriptors>"
--    IS 'View Description';

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> TEXT IS 'View Column Description'
--      );

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> IS 'View Column Description'
--      );

-- GRANT SELECT
-- ON "VW_AccountTable_<Descriptors>" TO PUBLIC WITH GRANT OPTION ;

-- GRANT ALTER, REFERENCES, SELECT
-- ON "VW_AccountTable_<Descriptors>" TO QPGMR WITH GRANT OPTION ;
   
-- Aliases
-- CREATE OR REPLACE ALIAS {AliasName} FOR "AccountTable";

-- Triggers
CREATE OR REPLACE TRIGGER "Customer_InsertStamps"
   NO CASCADE BEFORE INSERT ON "Customer"
   REFERENCING NEW AS NEW_ROW
   FOR EACH ROW MODE DB2ROW
   SET NEW_ROW."CreatedBy" = COALESCE(NEW_ROW."CreatedBy", SESSION_USER),
       NEW_ROW."CreatedWith" = COALESCE(NEW_ROW."CreatedWith", CURRENT CLIENT_APPLNAME);

SET SCHEMA DEFAULT;