/*******************************************************************************

CONFIDENTIAL AND PROPRIETARY INFORMATION

The receipt or possession of this document does not convey any rights to
reproduce, disclose its contents or manufacture, use or sell anything it may
describe.  Reproduction, disclosure, or use without the specific written
authorization of Surround Technologies, LLC is strictly forbidden.

Copyright ....: (C) Surround Technologies, LLC 1998 - 2021
                9197 Estero River Circle
                Estero, FL 33928
                973-743-1277
                http://www.surroundtech.com/
                 
================================================================================

Source File...: QDBSRC
Source Member.: "Product"
Created by ...: Lee Paul
Created on ...: August 29, 2021
Object Type ..: Table Definition
Description ..: Product

BUILD COMMAND.:
RUNSQLSTM SRCFILE(EASYBUYDM3/QDBSRC) SRCMBR("Product")
    COMMIT(*NONE) ERRLVL(20)

================================================================================
                             Amendment Details
                             -----------------
Date       Programmer      Description
---------- --------------- -----------------------------------------------------


*******************************************************************************
Notes:

To see the next identity value use the following SQL 
SELECT NEXT_IDENTITY_VALUE
    FROM QSYS2.SYSPARTITIONSTAT
    WHERE Table_Schema = 'EasyBuyCycles'
          AND Table_Name = 'Customer'

To see the last Value in the table use the following SQL
SELECT MAX("InternalID")
    FROM "EasyBuyCycles"."Customer";

To set the Customer Table Autoincrementing Identity Value use the follwing SQL
ALTER TABLE "EasyBuyCycles"."Customer"
   ALTER COLUMN "InternalID" RESTART WITH <the number you want>

*******************************************************************************/

SET SCHEMA "EasyBuyCycles";
-- SET SCHEMA "EasyBuyCyclesDev";

-- ALTER TABLE "Product"
--    DROP CONSTRAINT "PK_Product",
--    DROP CONSTRAINT "FK_Product_{ReferenceTable}";

DROP INDEX IF EXISTS "UQ_Product_Name";
DROP INDEX IF EXISTS "UQ_Product_Code";
DROP INDEX IF EXISTS "IX_Product_Description_Name";
DROP INDEX IF EXISTS "IX_Product_Category_Name";
DROP INDEX IF EXISTS "IX_Product_Discontinued_Name";
DROP INDEX IF EXISTS "IX_Product_ListPrice_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_";

-- DROP VIEW IF EXISTS "VW_{ViewName}_{ViewDescriptor}";

-- DROP ALIAS IF EXISTS "{AliasName}";

-- DROP TABLE IF EXISTS "Product";
-- Warnng: Dropping a table will lose the data within it.

CREATE OR REPLACE TABLE "Product"
    (
     "InternalID"           FOR "YD1PIID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(MINVALUE 5000 INCREMENT BY 1 CYCLE),
     "Code"                 FOR "YD1PCD" NVARCHAR(25) NOT NULL,
     "Name"                 FOR "YD1PNM" NVARCHAR(50) NOT NULL,
     "Description"          FOR "YD1PDS" NVARCHAR(256),
     "Category"             FOR "YD1PCT" NVARCHAR(50),
     "StandardCost"         FOR "YD1PSTCS" NUMERIC(10,2),
     "ListPrice"            FOR "YD1PLSPR" NUMERIC(10,2) NOT NULL,
     "ReorderLevel"         FOR "YD1PROLV" NUMERIC(4,0),
     "TargetLevel"          FOR "YD1PTGLV" NUMERIC(4,0),
     "MinimumReorderQuantity" FOR "YD1PMRQT" NUMERIC(4,0),
     "Discontinued"         FOR "YD1PDC" CHAR(1),
     "Memo"                 FOR "YD1PM1" NVARCHAR(100),
     "ImagePath"            FOR "YD1PIMPT" NVARCHAR(256),
    
     -- Audit Stamps
     "CreatedAt"            FOR "YD1SCRDT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "CreatedBy"            FOR "YD1SCRUS" VARCHAR(128) NOT NULL,
     "CreatedWith"          FOR "YD1SCRAP" VARCHAR(255) NOT NULL,
     "LastModifiedAt"       FOR "YD1SLCDT" TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL,
     "LastModifiedBy"       FOR "YD1SLCUS" VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER),
     "LastModifiedWith"     FOR "YD1SLCAP" VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME),


      -- Primary Key Constraint
      CONSTRAINT "PK_Product"
         PRIMARY KEY ("InternalID")

      -- Referential Constraints
      -- CONSTRAINT FK_Product_{ReferenceTable}
      --    FOREIGN KEY ({ForeignKeys})
      --    REFERENCES {ReferenceTable}({ReferenceColumns})
      --    {OnDeleteAction} {OnUpdateAction}
   )
RCDFMT YD1PPR
ON REPLACE PRESERVE ROWS;

-- Table Description
LABEL ON TABLE "Product"
   IS 'Product';

-- Column Labels - Description (50 Chars)
LABEL ON COLUMN "Product" (
     "InternalID"           TEXT IS 'Internal ID',
     "Code"                 TEXT IS 'Code',
     "Name"                 TEXT IS 'Name',
     "Description"          TEXT IS 'Description',
     "Category"             TEXT IS 'Category',
     "StandardCost"         TEXT IS 'Standard Cost',
     "ListPrice"            TEXT IS 'List Price',
     "ReorderLevel"         TEXT IS 'Reorder Level',
     "TargetLevel"          TEXT IS 'Target Level',
     "MinimumReorderQuantity" TEXT IS 'Minimum Reorder Quantity',
     "Discontinued"         TEXT IS 'Discontinued',
     "Memo"                 TEXT IS 'Memo',
     "ImagePath"            TEXT IS 'Image Path',

     "CreatedAt"            TEXT IS 'Created At',
     "CreatedBy"            TEXT IS 'Created By',
     "CreatedWith"          TEXT IS 'Created With',
     "LastModifiedAt"       TEXT IS 'Modified At',
     "LastModifiedBy"       TEXT IS 'Modified By',
     "LastModifiedWith"     TEXT IS 'Modified With'
     );

-- Column Labels - Column Headings (3 x 20 Chars)
LABEL ON COLUMN "Product" (
--                             |1-------------------2-------------------3-------------------|
     "InternalID"           IS 'Internal ID',
     "Code"                 IS 'Code',
     "Name"                 IS 'Name',
     "Description"          IS 'Description',
     "Category"             IS 'Category',
     "StandardCost"         IS 'Standard Cost',
     "ListPrice"            IS 'List Price',
     "ReorderLevel"         IS 'Reorder Level',
     "TargetLevel"          IS 'Target Level',
     "MinimumReorderQuantity" IS 'Minimum             Reorder Quantity',
     "Discontinued"         IS 'Discontinued',
     "Memo"                 IS 'Memo',
     "ImagePath"            IS 'Image Path',

     "CreatedAt"            IS 'Created At',
     "CreatedBy"            IS 'Created By',
     "CreatedWith"          IS 'Created With',
     "LastModifiedAt"       IS 'Modified At',
     "LastModifiedBy"       IS 'Modified By',
     "LastModifiedWith"     IS 'Modified With'
     );

-- Grant Table Access
GRANT DELETE, INSERT, SELECT, UPDATE
ON "Product" TO PUBLIC WITH GRANT OPTION ;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE
ON "Product" TO QPGMR WITH GRANT OPTION ;

-- Unique Indexes
CREATE UNIQUE INDEX "UQ_Product_Name"
   FOR SYSTEM NAME "YD1PIXU1" ON "Product" (
   "Name"
   );
LABEL ON INDEX "UQ_Product_Name"
   IS 'Product Name';

CREATE UNIQUE INDEX "UQ_Product_Code"
   FOR SYSTEM NAME "YD1PIXU2" ON "Product" (
   "Code"
   );
LABEL ON INDEX "UQ_Product_Code"
   IS 'Product Code';

-- Indexes
CREATE INDEX "IX_Product_Description_Name"
   FOR SYSTEM NAME "YD1PIX03"
   ON "Product" (
   "Description", "Name"
   );
LABEL ON INDEX "IX_Product_Description_Name"
   IS 'Description, Name';

CREATE INDEX "IX_Product_Category_Name"
   FOR SYSTEM NAME "YD1PIX04"
   ON "Product" (
   "Category", "Name"
   );
LABEL ON INDEX "IX_Product_Category_Name"
   IS 'Category, Name';

CREATE INDEX "IX_Product_Discontinued_Name"
   FOR SYSTEM NAME "YD1PIX05"
   ON "Product" (
   "Discontinued", "Name"
   );
LABEL ON INDEX "IX_Product_Discontinued_Name"
   IS 'Discontinued, Name';

CREATE INDEX "IX_Product_ListPrice_Name"
   FOR SYSTEM NAME "YD1PIX06"
   ON "Product" (
   "ListPrice", "Name"
   );
LABEL ON INDEX "IX_Product_ListPrice_Name"
   IS 'List Price, Name';

-- Views
-- CREATE OR REPLACE VIEW "VW_AccountTable_<Descriptors>"
--     FOR SYSTEM NAME "FACCTV01" AS
--          < View Definition >
-- ;
-- LABEL ON TABLE "VVW_AccountTable_<Descriptors>"
--    IS 'View Description';

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> TEXT IS 'View Column Description'
--      );

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> IS 'View Column Description'
--      );

-- GRANT SELECT
-- ON "VW_AccountTable_<Descriptors>" TO PUBLIC WITH GRANT OPTION ;

-- GRANT ALTER, REFERENCES, SELECT
-- ON "VW_AccountTable_<Descriptors>" TO QPGMR WITH GRANT OPTION ;
   
-- Aliases
-- CREATE OR REPLACE ALIAS {AliasName} FOR "AccountTable";

-- Triggers
CREATE OR REPLACE TRIGGER "Product_InsertStamps"
   NO CASCADE BEFORE INSERT ON "Product"
   REFERENCING NEW AS NEW_ROW
   FOR EACH ROW MODE DB2ROW
   SET NEW_ROW."CreatedBy" = COALESCE(NEW_ROW."CreatedBy", SESSION_USER),
       NEW_ROW."CreatedWith" = COALESCE(NEW_ROW."CreatedWith", CURRENT CLIENT_APPLNAME);

SET SCHEMA DEFAULT;