/*******************************************************************************

CONFIDENTIAL AND PROPRIETARY INFORMATION

The receipt or possession of this document does not convey any rights to
reproduce, disclose its contents or manufacture, use or sell anything it may
describe.  Reproduction, disclosure, or use without the specific written
authorization of Surround Technologies, LLC is strictly forbidden.

Copyright ....: (C) Surround Technologies, LLC 1998 - 2021
                9197 Estero River Circle
                Estero, FL 33928
                973-743-1277
                http://www.surroundtech.com/
                 
================================================================================

Source File...: QDBSRC
Source Member.: IBM i DDL EasyBuyCyclesModern ShippingAddress.sql
Created by ...: Lee Paul
Created on ...: September 14, 2022
Object Type ..: Table Definition
Description ..: Shipping Address

BUILD COMMAND.:
RUNSQLSTM SRCFILE(EASYBUYDM3/QDBSRC) SRCMBR("ShpAddr")
    COMMIT(*NONE) ERRLVL(20)

================================================================================
                             Amendment Details
                             -----------------
Date       Programmer      Description
---------- --------------- -----------------------------------------------------


*******************************************************************************
Notes:

To see the next identity value use the following SQL 
SELECT NEXT_IDENTITY_VALUE
    FROM QSYS2.SYSPARTITIONSTAT
    WHERE Table_Schema = 'EasyBuyCycles'
          AND Table_Name = 'Customer'

To see the last Value in the table use the following SQL
SELECT MAX("InternalID")
    FROM "EasyBuyCycles"."Customer";

To set the Customer Table Autoincrementing Identity Value use the follwing SQL
ALTER TABLE "EasyBuyCycles"."Customer"
   ALTER COLUMN "InternalID" RESTART WITH <the number you want>

*******************************************************************************/

SET SCHEMA "EasyBuyCycles";
-- SET SCHEMA "EasyBuyCyclesDev";

-- ALTER TABLE "ShippingAddress"
--    DROP CONSTRAINT "PK_ShippingAddress",
--    DROP CONSTRAINT "FK_ShippingAddress_{ReferenceTable}";

DROP INDEX IF EXISTS "UQ_ShippingAddress_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_PostalCode_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_ContactLastName_ContactFirstName_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_Telephone_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_Email_Name";
DROP INDEX IF EXISTS "IX_ShippingAddress_CustomerInternalID_Name";

-- DROP VIEW IF EXISTS "VW_{ViewName}_{ViewDescriptor}";

-- DROP ALIAS IF EXISTS "{AliasName}";

-- DROP TABLE IF EXISTS "ShippingAddress";
-- Warnng: Dropping a table will lose the data within it.

CREATE OR REPLACE TABLE "ShippingAddress"
    FOR SYSTEM NAME "ShpAddr"  (
     "InternalID"           FOR "YD1SIID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(MINVALUE 5000 INCREMENT BY 1 CYCLE),
     "CustomerInternalID"   FOR "YD1S1CID" INT NOT NULL,
     "Name"                 FOR "YD1SNM" NVARCHAR(50) NOT NULL,
     "ContactLastName"      FOR "YD1SCNLN" NVARCHAR(50) NOT NULL,
     "ContactFirstName"     FOR "YD1SCNFN" NVARCHAR(50) NOT NULL,
     "ContactMiddleName"    FOR "YD1SCNMN" NVARCHAR(50),
     "ContactNickName"      FOR "YD1SCNNN" NVARCHAR(50),
     "Address1"             FOR "YD1SSHA1" NVARCHAR(30) NOT NULL,
     "Address2"             FOR "YD1SSHA2" NVARCHAR(30) NOT NULL,
     "Address3"             FOR "YD1SSHA3" NVARCHAR(30) NOT NULL,
     "PostalCode"           FOR "YD1SSHPC" NVARCHAR(10) NOT NULL,
     "Country"              FOR "YD1SSHCY" NVARCHAR(50) NOT NULL,
     "Telephone"            FOR "YD1STL" NVARCHAR(20),
     "Email"                FOR "YD1SEM" NVARCHAR(50),
     "Memo"                 FOR "YD1SM1" NVARCHAR(100),
     "PurchasePoints"       FOR "YD1SPRPT" NUMERIC(8,0),
    
     -- Audit Stamps
     "CreatedAt"            FOR "YD1SCRDT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "CreatedBy"            FOR "YD1SCRUS" VARCHAR(128) NOT NULL,
     "CreatedWith"          FOR "YD1SCRAP" VARCHAR(255) NOT NULL,
     "LastModifiedAt"       FOR "YD1SLCDT" TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL,
     "LastModifiedBy"       FOR "YD1SLCUS" VARCHAR(128) GENERATED ALWAYS AS (SESSION_USER),
     "LastModifiedWith"     FOR "YD1SLCAP" VARCHAR(255) GENERATED ALWAYS AS (CURRENT CLIENT_APPLNAME),

      -- Primary Key Constraint
      CONSTRAINT "PK_ShippingAddress"
         PRIMARY KEY ("InternalID"),

      -- Referential Foreign Key Constraints
      CONSTRAINT "FK_ShippingAddress_Customer"
         FOREIGN KEY ("CustomerInternalID")
         REFERENCES "Customer"("InternalID")
         ON DELETE RESTRICT ON UPDATE RESTRICT
   )
RCDFMT YD1SPR
ON REPLACE PRESERVE ROWS;

-- Table Description
LABEL ON TABLE "ShippingAddress"
   IS 'Shipping Address';

-- Column Labels - Description (50 Chars)
LABEL ON COLUMN "ShippingAddress" (
     "InternalID"           TEXT IS 'Internal ID',
     "CustomerInternalID"   TEXT IS 'Customer Internal ID',
     "Name"                 TEXT IS 'Name',
     "ContactLastName"      TEXT IS 'Contact Last Name',
     "ContactFirstName"     TEXT IS 'Contact First Name',
     "ContactMiddleName"    TEXT IS 'Contact Middle Name',
     "ContactNickName"      TEXT IS 'Contact Nick Name',
     "Address1"             TEXT IS 'Address 1',
     "Address2"             TEXT IS 'Address 2',
     "Address3"             TEXT IS 'Address 3',
     "PostalCode"           TEXT IS 'Postal Code',
     "Country"              TEXT IS 'Country',
     "Telephone"            TEXT IS 'Telephone',
     "Email"                TEXT IS 'Email',
     "Memo"                 TEXT IS 'Memo',
     "PurchasePoints"       TEXT IS 'Purchase Points',

     "CreatedAt"            TEXT IS 'Created At',
     "CreatedBy"            TEXT IS 'Created By',
     "CreatedWith"          TEXT IS 'Created With',
     "LastModifiedAt"       TEXT IS 'Modified At',
     "LastModifiedBy"       TEXT IS 'Modified By',
     "LastModifiedWith"     TEXT IS 'Modified With'
     );

-- Column Labels - Column Headings (3 x 20 Chars)
LABEL ON COLUMN "ShippingAddress" (
--                             |1-------------------2-------------------3-------------------|
     "InternalID"           IS 'Internal ID',
     "CustomerInternalID"   IS 'Customer            Internal ID',
     "Name"                 IS 'Name',
     "ContactLastName"      IS 'Contact             Last Name',
     "ContactFirstName"     IS 'Contact             First Name',
     "ContactMiddleName"    IS 'Contact             Middle Name',
     "ContactNickName"      IS 'Contact             Nick Name',
     "Address1"             IS 'Address 1',
     "Address2"             IS 'Address 2',
     "Address3"             IS 'Address 3',
     "PostalCode"           IS 'Postal Code',
     "Country"              IS 'Country',
     "Telephone"            IS 'Telephone',
     "Email"                IS 'Email',
     "Memo"                 IS 'Memo',
     "PurchasePoints"       IS 'Purchase Points',

     "CreatedAt"            IS 'Created At',
     "CreatedBy"            IS 'Created By',
     "CreatedWith"          IS 'Created With',
     "LastModifiedAt"       IS 'Modified At',
     "LastModifiedBy"       IS 'Modified By',
     "LastModifiedWith"     IS 'Modified With'
     );

-- Grant Table Access
GRANT DELETE, INSERT, SELECT, UPDATE
ON "ShippingAddress" TO PUBLIC WITH GRANT OPTION ;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE
ON "ShippingAddress" TO QPGMR WITH GRANT OPTION ;

-- Unique Indexes
CREATE UNIQUE INDEX "UQ_ShippingAddress_Name"
   FOR SYSTEM NAME "YD1SIXU1" ON "ShippingAddress" (
   "Name"
   );
LABEL ON INDEX "UQ_ShippingAddress_Name"
   IS 'Shipping Address Name';

-- Indexes
CREATE INDEX "IX_ShippingAddress_PostalCode_Name"
   FOR SYSTEM NAME "YD1SIX02"
   ON "ShippingAddress" (
   "PostalCode", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_PostalCode_Name"
   IS 'Postal Code, Name';

CREATE INDEX "IX_ShippingAddress_ContactLastName_ContactFirstName_Name"
   FOR SYSTEM NAME "YD1SIX03"
   ON "ShippingAddress" (
   "ContactLastName", "ContactFirstName", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_ContactLastName_ContactFirstName_Name"
   IS 'Contact Last and First Name, Name';

CREATE INDEX "IX_ShippingAddress_Telephone_Name"
   FOR SYSTEM NAME "YD1SIX04"
   ON "ShippingAddress" (
   "Telephone", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_Telephone_Name"
   IS 'Telephone, Name';

CREATE INDEX "IX_ShippingAddress_Email_Name"
   FOR SYSTEM NAME "YD1SIX05"
   ON "ShippingAddress" (
   "Email", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_Email_Name"
   IS 'Email, Name';

CREATE INDEX "IX_ShippingAddress_CustomerInternalID_Name"
   FOR SYSTEM NAME "YD1SIX06"
   ON "ShippingAddress" (
   "CustomerInternalID", "Name"
   );
LABEL ON INDEX "IX_ShippingAddress_CustomerInternalID_Name"
   IS 'Customer ID, Name';

-- Views
-- CREATE OR REPLACE VIEW "VW_AccountTable_<Descriptors>"
--     FOR SYSTEM NAME "FACCTV01" AS
--          < View Definition >
-- ;
-- LABEL ON TABLE "VVW_AccountTable_<Descriptors>"
--    IS 'View Description';

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> TEXT IS 'View Column Description'
--      );

-- LABEL ON COLUMN "VW_AccountTable_<Descriptors>" (
--      <ViewColumnName> IS 'View Column Description'
--      );

-- GRANT SELECT
-- ON "VW_AccountTable_<Descriptors>" TO PUBLIC WITH GRANT OPTION ;

-- GRANT ALTER, REFERENCES, SELECT
-- ON "VW_AccountTable_<Descriptors>" TO QPGMR WITH GRANT OPTION ;
   
-- Aliases
-- CREATE OR REPLACE ALIAS {AliasName} FOR "AccountTable";

-- Triggers
CREATE OR REPLACE TRIGGER "ShippingAddress_InsertStamps"
   NO CASCADE BEFORE INSERT ON "ShippingAddress"
   REFERENCING NEW AS NEW_ROW
   FOR EACH ROW MODE DB2ROW
   SET NEW_ROW."CreatedBy" = COALESCE(NEW_ROW."CreatedBy", SESSION_USER),
       NEW_ROW."CreatedWith" = COALESCE(NEW_ROW."CreatedWith", CURRENT CLIENT_APPLNAME);

SET SCHEMA DEFAULT;