//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOS.OrderManagement.ViewModels.Customer.ServiceProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeOffset", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateTimeOffset : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private short OffsetMinutesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                if ((this.DateTimeField.Equals(value) != true))
                {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short OffsetMinutes
        {
            get
            {
                return this.OffsetMinutesField;
            }
            set
            {
                if ((this.OffsetMinutesField.Equals(value) != true))
                {
                    this.OffsetMinutesField = value;
                    this.RaisePropertyChanged("OffsetMinutes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BOS.OrderManagement.ViewModels.Customer.ServiceProxy.ICustomerBPServiceContract")]
    public interface ICustomerBPServiceContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "Insert", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "InsertResponse")]
        A4DN.Core.BOS.Base.AB_InsertReturnArgs<BOS.CustomerDataEntity.CustomerEntity> Insert(A4DN.Core.BOS.Base.AB_InsertInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchInsert", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchInsertResponse")]
        A4DN.Core.BOS.Base.AB_BatchInsertReturnArgs<BOS.CustomerDataEntity.CustomerEntity> BatchInsert(A4DN.Core.BOS.Base.AB_BatchInsertInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "Fetch", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "FetchResponse")]
        A4DN.Core.BOS.Base.AB_FetchReturnArgs<BOS.CustomerDataEntity.CustomerEntity> Fetch(A4DN.Core.BOS.Base.AB_FetchInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "Delete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_PermDeleteReturnArgs Delete(A4DN.Core.BOS.Base.AB_PermDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs BatchDelete(A4DN.Core.BOS.Base.AB_BatchPermDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "SoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "SoftDeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_SoftDeleteReturnArgs SoftDelete(A4DN.Core.BOS.Base.AB_SoftDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchSoftDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs BatchSoftDelete(A4DN.Core.BOS.Base.AB_BatchSoftDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "RestoreSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "RestoreSoftDeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs))]
        A4DN.Core.BOS.Base.AB_RestoreSoftDeleteReturnArgs RestoreSoftDelete(A4DN.Core.BOS.Base.AB_RestoreSoftDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchRestoreSoftDelete", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchRestoreSoftDeleteResponse")]
        A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs BatchRestoreSoftDelete(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "Select", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "SelectResponse")]
        A4DN.Core.BOS.Base.AB_SelectReturnArgs<BOS.CustomerDataEntity.CustomerEntity> Select(A4DN.Core.BOS.Base.AB_SelectInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "Update", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "UpdateResponse")]
        A4DN.Core.BOS.Base.AB_UpdateReturnArgs<BOS.CustomerDataEntity.CustomerEntity> Update(A4DN.Core.BOS.Base.AB_UpdateInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchUpdate", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "BatchUpdateResponse")]
        A4DN.Core.BOS.Base.AB_BatchUpdateReturnArgs<BOS.CustomerDataEntity.CustomerEntity> BatchUpdate(A4DN.Core.BOS.Base.AB_BatchUpdateInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "ProcessRequest", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "ProcessRequestResponse")]
        A4DN.Core.BOS.Base.AB_ProcessRequestReturnArgs<BOS.CustomerDataEntity.CustomerEntity> ProcessRequest(A4DN.Core.BOS.Base.AB_ProcessRequestInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "am_GetTitleService", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "am_GetTitleServiceResponse")]
        A4DN.Core.BOS.Base.AB_GetTitleReturnArgs am_GetTitleService(A4DN.Core.BOS.Base.AB_GetTitleInputArgs InputArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "am_GetMessageTextForRecordService", ReplyAction="http://tempuri.org/AB_IBusinessObjectProcessBaseServiceContractOf_CustomerEntity/" +
            "am_GetMessageTextForRecordServiceResponse")]
        A4DN.Core.BOS.Base.AB_GetMessageForRecordReturnArgs am_GetMessageTextForRecordService(A4DN.Core.BOS.Base.AB_GetMessageTextForRecordInputArgs InputArgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerBPServiceContractChannel : BOS.OrderManagement.ViewModels.Customer.ServiceProxy.ICustomerBPServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerBPServiceContractClient : System.ServiceModel.ClientBase<BOS.OrderManagement.ViewModels.Customer.ServiceProxy.ICustomerBPServiceContract>, BOS.OrderManagement.ViewModels.Customer.ServiceProxy.ICustomerBPServiceContract
    {
        
        public CustomerBPServiceContractClient()
        {
        }
        
        public CustomerBPServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CustomerBPServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CustomerBPServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CustomerBPServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public A4DN.Core.BOS.Base.AB_InsertReturnArgs<BOS.CustomerDataEntity.CustomerEntity> Insert(A4DN.Core.BOS.Base.AB_InsertInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.Insert(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchInsertReturnArgs<BOS.CustomerDataEntity.CustomerEntity> BatchInsert(A4DN.Core.BOS.Base.AB_BatchInsertInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.BatchInsert(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_FetchReturnArgs<BOS.CustomerDataEntity.CustomerEntity> Fetch(A4DN.Core.BOS.Base.AB_FetchInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.Fetch(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_PermDeleteReturnArgs Delete(A4DN.Core.BOS.Base.AB_PermDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.Delete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchPermDeleteReturnArgs BatchDelete(A4DN.Core.BOS.Base.AB_BatchPermDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.BatchDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_SoftDeleteReturnArgs SoftDelete(A4DN.Core.BOS.Base.AB_SoftDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.SoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchSoftDeleteReturnArgs BatchSoftDelete(A4DN.Core.BOS.Base.AB_BatchSoftDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.BatchSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_RestoreSoftDeleteReturnArgs RestoreSoftDelete(A4DN.Core.BOS.Base.AB_RestoreSoftDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.RestoreSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteReturnArgs BatchRestoreSoftDelete(A4DN.Core.BOS.Base.AB_BatchRestoreSoftDeleteInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.BatchRestoreSoftDelete(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_SelectReturnArgs<BOS.CustomerDataEntity.CustomerEntity> Select(A4DN.Core.BOS.Base.AB_SelectInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.Select(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_UpdateReturnArgs<BOS.CustomerDataEntity.CustomerEntity> Update(A4DN.Core.BOS.Base.AB_UpdateInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.Update(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_BatchUpdateReturnArgs<BOS.CustomerDataEntity.CustomerEntity> BatchUpdate(A4DN.Core.BOS.Base.AB_BatchUpdateInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.BatchUpdate(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_ProcessRequestReturnArgs<BOS.CustomerDataEntity.CustomerEntity> ProcessRequest(A4DN.Core.BOS.Base.AB_ProcessRequestInputArgs<BOS.CustomerDataEntity.CustomerEntity> InputArgs)
        {
            return base.Channel.ProcessRequest(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_GetTitleReturnArgs am_GetTitleService(A4DN.Core.BOS.Base.AB_GetTitleInputArgs InputArgs)
        {
            return base.Channel.am_GetTitleService(InputArgs);
        }
        
        public A4DN.Core.BOS.Base.AB_GetMessageForRecordReturnArgs am_GetMessageTextForRecordService(A4DN.Core.BOS.Base.AB_GetMessageTextForRecordInputArgs InputArgs)
        {
            return base.Channel.am_GetMessageTextForRecordService(InputArgs);
        }
    }
}
