name: easybuy-pr-build

on:
  pull_request:
    types: [opened, reopened]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  # Folder to use for build artifcats and deployment location
  # BUILD_DIRECTORY: test
  # IIS_DIRECTORY: NIMMetalsBP_f1
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions: write-all

jobs:
  deploy-dev: 
    runs-on: [self-hosted, Windows]
    environment: dev
    needs: call-build-workflow
    steps:
      - name: Update Version Config
        run: .\\DB2Legacy\OrderManagement\BuildScripts\Build.ps1