name: increment-revision
on:
  workflow_call:
    inputs:
      env-name: 
        required: true
        type: string
    outputs: 
      version: 
        value: ${{ jobs.increment_version_vars.outputs.version }}
jobs:
  increment_version_vars:
    runs-on: [ubuntu-latest]
    environment: ${{inputs.env-name}}
    outputs: 
      version: ${{ steps.output_version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    - name: list current version
      run: 'echo "Incrementing current version ${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.${{ vars.VERSION_BUILD }}.${{ vars.VERSION_REVISION }}"'
    - name: increment revision
      id: increment_revision
      run: 'echo "REVISION=$((${{ vars.VERSION_REVISION }} + 1))" >> $GITHUB_OUTPUT'
    - name: update revision
      run: 'curl -L -X PATCH -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/NIM-Group/Metals/actions/variables/VERSION_REVISION -d ''{"name": "VERSION_REVISION", "value": "${{ steps.increment_revision.outputs.REVISION }}" }'''
    - name: output version
      id: output_version
      run: |
        "version=${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.${{ vars.VERSION_BUILD }}.${{ vars.VERSION_REVISION }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
